const escape = (s: string) => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const css = `:root{font-family:-apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif;background:#fdfdfc;color:#242421;color-scheme:light}*{box-sizing:border-box}body{margin:0}main{max-width:620px;padding:80px 26px;margin:auto}header{font-size:14px;color:#777;margin-bottom:80px;letter-spacing:.1em}h1{font-size:40px;font-weight:550;letter-spacing:-.04em;line-height:1.3;margin:0 0 22px}.en{font-size:12px;letter-spacing:.09em;color:#777;margin-bottom:24px}.intro{font-size:16px;line-height:1.9;color:#666;margin-bottom:45px}label{display:block;font-size:14px;margin:0 0 12px}input{width:100%;border:1px solid #ccc;background:transparent;border-radius:0;padding:16px;font:inherit;color:inherit;font-size:17px}button{border:0;background:#242421;color:#fafaf7;padding:16px 28px;font:inherit;font-size:15px;cursor:pointer;margin-top:16px}button:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid #777;outline-offset:4px}.error{color:#a43129;font-size:14px;line-height:1.7}.link{display:block;color:inherit;text-decoration:none;border-top:1px solid #ddd;padding:25px 0}.link strong{font-size:24px;font-weight:550}.link span{display:block;font-size:14px;color:#777;margin-top:10px;line-height:1.8}.logout button{background:none;color:#777;padding:10px 0;font-size:13px}footer{font-size:12px;color:#888;border-top:1px solid #ddd;margin-top:60px;padding-top:20px;line-height:1.8}@media(max-width:600px){main{padding-top:40px}header{margin-bottom:60px}h1{font-size:34px}}@media(prefers-color-scheme:dark){:root{background:#242625;color:#f1f0e9;color-scheme:dark}.intro,.en,header,.link span{color:#b0b2a9}input,.link,footer{border-color:#50524c}button{background:#eee;color:#242625}.error{color:#ffb3a7}}`;
function shell(title: string, body: string) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${escape(title)} · HA7CH</title><style>${css}</style></head><body><main><header>HA7CH / FDE CAMP</header>${body}<footer>2026.09.13 · Build in the field. Hatch into impact.</footer></main></body></html>`;
}
export function loginView(next: string, error = '') {
  return shell('课程资料', `<div class="en">AI NATIVE COMPANY</div><h1>一起把 ANC 讲透。</h1><p class="intro">部署自己的 ANC、制作 Skill，配套步骤讲解与现场课件。<br>输入课程密码后继续。</p><form method="post" action="/fde-camp/login"><input type="hidden" name="next" value="${escape(next)}"><label for="password">访问密码</label><input id="password" name="password" type="password" required maxlength="256" autocomplete="current-password" autofocus>${error?`<p class="error" role="alert">${escape(error)}</p>`:''}<button type="submit">进入课程 →</button></form>`);
}
export function indexView() {
  return shell('ANC 课程资料', `<div class="en">AI NATIVE COMPANY</div><h1>ANC · FDE Camp</h1><p class="intro">从自己的 AWS 和 Codex 开始，做出第一份 Skill，再把工作经验留下来。</p><a class="link" href="/fde-camp/setup"><strong>部署自己的 ANC ↗</strong><span>AWS → Codex 登录 → 第一份 Skill → 飞书接入。<br>每一步的命令、解释、成功标志与排错。</span></a><a class="link" href="/fde-camp/lesson"><strong>边做边讲 ↗</strong><span>从一次真实工作讲清 Context、Skill、项目责任与结果证据。<br>逐步讲解 · 课堂练习</span></a><a class="link" href="/fde-camp/book"><strong>备课全书 ↗</strong><span>14 章长文、来源索引与讲师研究附录。<br>FIELD BOOK</span></a><a class="link" href="/fde-camp/slides"><strong>现场课件 ↗</strong><span>57 页讲授课件 · 左右键翻页，F 全屏。<br>LECTURE SLIDES</span></a><form class="logout" method="post" action="/fde-camp/logout"><button type="submit">退出访问</button></form>`);
}
