import type { Article } from "./types";

const article: Article = {
  slug: "ai-transformation-capital",
  titleZh: "AI 改造资本：Ha7ch 最新商业模式的正式定义",
  titleEn: "AI Transformation Capital: Ha7ch's New Business Model",
  date: "2026-08-15",
  dateDisplay: "Aug 15",
  descriptionZh:
    "资本不只寻找已经增长的公司，而是带着 FDE 和组织能力进入传统企业，亲手把增长做出来，并把企业、FDE 与 Ha7ch 绑成长期利益共同体。",
  description:
    "Capital does not merely select companies that are already growing. It enters traditional enterprises with FDEs, creates growth, and binds the enterprise, the FDE, and Ha7ch into a long-term community of interest.",
  keywords: [
    "AI 改造资本",
    "AI Transformation Capital",
    "FDE",
    "利益共同体",
    "enterprise transformation",
    "traditional enterprise",
    "equity",
    "HA7CH",
  ],
  zh: [
    "Ha7ch 最新的商业模式，正式命名为：**AI 改造资本（AI Transformation Capital）**。",
    "它的定义是：Ha7ch 先通过 FDE 深入传统企业，在真实合作中判断企业、发现 AI 可以创造的价值；再选择其中少数值得长期合作的企业投入资本，并让真正完成改造的 FDE 获得长期权益。企业、FDE 与 Ha7ch 最终共同分享企业被 AI 重做以后产生的长期价值。",
    "压缩成一句话：",
    "> **VC 投资新公司，AI 改造资本重做老公司。**",
    "一、资本过去只能选择公司，现在可以改造公司",
    "过去，一家投资机构最重要的能力是选择。",
    "它通过行业研究、财务报表、管理层访谈和商业尽调，判断哪家公司更有可能增长。投资完成以后，企业继续经营，投资人等待结果。",
    "这套模式默认了一件事：投资人能够判断价值，却很难亲自创造价值。",
    "AI 改变了这个前提。",
    "今天，一家传统企业的很多增长空间，不再完全取决于它原来所在的行业。它可能藏在报价、生产、财务、销售、供应链、客户服务和组织协作里。过去需要几十个人反复完成的工作，可能被重新设计；过去因为人力、速度和错误率无法承接的业务，可能变成新的收入；过去只存在于老员工脑中的经验，可能成为整个组织可以持续调用的能力。",
    "但这些价值不会因为企业购买了几个大模型账号就自动出现。它需要有人真正进入企业，把业务、产品、工程和组织一起重新做一遍。",
    "所以 Ha7ch 想做的不是一家站在企业外面挑选赢家的投资机构，而是一种新的资本：先进入企业，发现改变它的方法，再用资本把这种改变放大。",
    "这就是 AI 改造资本。",
    "二、FDE 是 AI 改造资本的现场尽调",
    "传统投资人主要通过企业主动提供的信息理解企业。FDE 则在解决真实问题的过程中理解企业。",
    "一个 FDE 真正进入企业以后，会同时看见三个层面。",
    "他会看见高层有没有远见，能不能根据事实作出行动；会看见中层有没有管理与执行能力，部门之间能不能协同；也会看见基层每天的工作到底如何发生，哪些流程只是表面上数字化，实际上仍然依赖复制、粘贴、纸质材料和口头经验。",
    "他还会看见这家企业的数据是否可信，业务处在什么生态位，未来有没有增长空间；AI 到底能够改造哪些流程，又能给收入、成本、效率和风险带来多大的真实变化。",
    "这些信息不会完整地出现在一份商业计划书里。它们藏在 PDF、Excel、CAD、纸质单据、系统切换、异常处理和跨部门扯皮里。",
    "因此，FDE 不只是企业 AI 项目的交付者。",
    "> **FDE 是离企业经营现场最近的技术尽调者，也是 AI 价值的第一发现人。**",
    "一家企业值不值得投资，不再只通过会议室里的故事判断，也可以通过双方真实共事以后留下的结果判断。",
    "如果 Ha7ch 真正服务十家、二十家企业，就有机会从中发现三家、五家值得长期投资的企业。这比在会议室里听二十家公司讲 AI 故事，更接近真实。",
    "三、AI 改造资本如何运行",
    "这套商业模式从一笔正常的企业服务开始。",
    "企业提出真实问题，FDE 进入企业完成诊断、设计和交付。FDE 该收 10 万元服务费，就收 10 万元；该收 20 万元，就收 20 万元。Ha7ch 不从 FDE 与企业之间的正常合作中抽成。",
    "对大多数企业而言，合作可以停留在项目层面。企业获得结果，FDE 获得收入，双方继续复购或者结束合作。",
    "但其中少数企业会进入 Ha7ch 的长期筛选。",
    "Ha7ch 会在真实合作中判断：这家企业是否愿意开放真实问题，管理层是否能够根据证据行动，组织是否具备执行能力，已经完成的改造是否产生了可核验结果，以及更大范围的增长是否可能发生。",
    "只有通过这些判断的企业，才会进入投资阶段。",
    "投资以后，Ha7ch 不再只是服务关系中的第三方，而是和企业站在同一张长期利益表上。真正承担改造责任的 FDE，也会获得与阶段性目标绑定、逐步归属的长期权益。",
    "于是三方的关系发生变化。",
    "企业不再只是购买一套 AI 服务；FDE 不再只是完成一笔外包；Ha7ch 也不再只是介绍双方认识的平台。三方开始共同做大同一家公司未来的价值。",
    "四、把三方绑成一个利益共同体",
    "AI 改造资本最核心的作用，是把企业、FDE 与 Ha7ch 从一次性的交易关系，绑成一个长期利益共同体。",
    "企业通过 AI 改造获得增长，FDE 通过长期权益分享自己创造的价值，Ha7ch 通过投资获得股权增值。三方不再分别优化采购成本、项目收入和平台抽成，而是共同优化同一个结果：把这家企业做得更有价值。",
    "> **这不是靠合同把三方锁在一起，而是靠利益结构让三方站在一起。**",
    "企业增长，三方共同获益；企业没有增长，三方共同承担机会成本与投资风险。风险与收益来自同一件事，利益共同体才真正成立。",
    "五、AI 改造资本赚什么钱",
    "传统服务公司的收入，主要跟交付规模有关。项目越多、报价越高、人天越长，收入越高。",
    "但企业真正关心的从来不是服务方写了多少代码、做了多少页面，而是经营结果有没有变化。",
    "一个 20 万元的项目，可能帮助企业每年节省 500 万元；一个 200 万元的项目，也可能只留下一个没有员工使用的 Demo。只按项目收费时，服务方优化的是签单和交付，企业优化的却是收入、成本和利润。双方并没有真正站在同一个结果上。",
    "AI 改造资本把两笔账分开。",
    "服务费支付已经完成的劳动。FDE 完成真实交付，就获得相应收入。这部分收入属于 FDE 或负责交付的团队，Ha7ch 不依靠抽成赚钱。",
    "股权对应未来仍然持续创造的价值。当 Ha7ch 判断一家企业值得长期合作，就投入自己的资本获得股权，与企业一起承担风险，也分享企业未来的增长。",
    "FDE 的长期权益，则让最了解现场、真正完成改造的人，不只因为做完项目获得一次收入，也因为企业长期成长获得回报。",
    "> **服务费买已经完成的工作，股权买未来仍然持续发生的价值。**",
    "Ha7ch 真正要赚的钱，不是 FDE 的劳动差价，而是被投企业完成 AI 改造以后产生的股权增值。",
    "六、300 万与 30 万只是一个解释模型",
    "我们此前举过一个假设。",
    "一家传统企业估值 4 亿元。Ha7ch 在真实服务并完成判断以后，投入 300 万元，获得相应股权；同时从相关权益中预留价值 30 万元的部分，按照阶段性改造目标逐步激励给驻场 FDE。",
    "如果企业未来从 4 亿元增长到 8 亿元，Ha7ch 的股权与 FDE 的长期权益都会随之增长。如果企业没有产生预期增长，Ha7ch 也要承担投资损失。",
    "这组数字只是用来解释机制。它不是固定报价，不是已经签署的标准条款，也不是收益承诺。每一家企业仍然需要独立完成尽调、估值、谈判和合规设计。",
    "真正重要的不是 300 万或 30 万，而是三方的收益第一次来自同一个结果：企业长期价值的增长。",
    "七、三方分别投入什么",
    "企业投入真实业务、管理授权、组织配合和一部分长期权益。它得到的不是一次 AI 演示，而是一支愿意和它共同承担结果的外部改造力量。",
    "FDE 投入业务判断、产品定义、工程实现、现场沟通和长期执行。他获得正常服务收入，也有机会获得与实际贡献绑定的长期权益。",
    "Ha7ch 投入资本、品牌、企业资源、FDE 网络、跨企业经验、技术能力与持续组织能力。它的回报不来自抽走 FDE 的劳动收入，而来自所投资企业的长期成长。",
    "企业保留经营主体和绝大多数增长价值；FDE 获得与贡献相匹配的长期回报；Ha7ch 通过资本与持续能力获得股权增值。",
    "这不是一次性交付关系，而是一套把服务、尽调、投资和企业改造连接起来的商业结构。",
    "八、企业为什么不能直接挖走 FDE",
    "准确地说，企业当然可以直接聘用一个 FDE。甚至在某些阶段，这可能正是合理选择。",
    "如果 Ha7ch 的价值只是介绍一个 FDE 给一家企业，那么双方建立信任以后绕过 Ha7ch，是完全理性的。任何只完成一次撮合的平台，都无法靠合同永久封住这个漏洞。",
    "所以 Ha7ch 必须持续提供单个 FDE 无法独立提供的东西：新的 Builder、跨企业经验、持续更新的技术和方法、复杂项目的协同、人才培养、品牌信用、资本支持，以及下一阶段改造需要的完整资源。",
    "> **一个人可以被雇佣，一张持续进化的网络很难被一家企业独自复制。**",
    "如果 Ha7ch 无法继续创造这些价值，企业和 FDE 就没有理由把 Ha7ch 留在关系里。这个问题不能主要靠排他条款解决，只能靠持续价值解决。",
    "Ha7ch 要建立的不是一个派单平台，而是一张能够持续生产 FDE、组织 AI 交付、积累行业方法并共同投资企业的服务网络。",
    "九、什么样的企业值得进入投资阶段",
    "AI 改造资本不是所有客户的默认合作方式。",
    "大部分企业可以继续按项目合作，只有少数企业会进入投资阶段。真正值得长期投资的企业，需要愿意开放真实业务与真实流程，管理层能够根据证据行动，业务中存在足够大的可验证价值，并且愿意让创造长期价值的人分享长期价值。",
    "我们已经在赛车协作、财会知识与材料处理、湾区制造业报价和生产流程中反复看到同一件事：企业最有价值的 AI 机会，通常不会以一份清晰的需求文档出现。它需要有人进入现场，从大量琐碎、重复、跨系统但又直接影响经营的工作中挖出来。",
    "因此，Ha7ch 未来既要筛选优秀的 FDE，也要筛选优秀的传统企业。",
    "就像一家创业公司会说自己拿到了 YC 的投资一样，未来一家优秀的传统企业也可以说：我们拿到了 Ha7ch 的投资。",
    "这句话意味着的不是它购买过几个 AI 工具，而是 Ha7ch 已经通过真实合作完成了判断，并愿意把自己的资本、人才与信用一起押在这家企业的 AI 转型上。",
    "十、AI 改造资本不是什么法律结构",
    "AI 改造资本首先是一个商业模式的名字，不是基金产品名称，也不是某一种固定的法律载体。",
    "具体项目可以根据企业、投资人和资金来源，采用直接股权投资、项目公司、专项载体或者其他合规结构。Ha7ch 本身如何融资、外部投资人如何参与、资金最终如何进入企业，也需要在具体项目中分别完成法律、税务和合规设计。",
    "但无论采用什么结构，底层逻辑不变：先通过真实服务理解企业，再投资经过验证的企业；让完成改造的 FDE 获得长期权益，让企业、FDE 与 Ha7ch 一起分享企业价值增长。",
    "十一、最终定义",
    "AI 改造资本，是一种以 FDE 为现场尽调与改造力量、以传统企业为投资对象、以企业长期价值增长为主要回报，并把企业、FDE 与 Ha7ch 绑成长期利益共同体的商业模式。",
    "它把过去彼此分离的四件事连接到了一起：服务企业、理解企业、改造企业、投资企业。",
    "普通资本寻找已经存在的增长。AI 改造资本进入企业，亲手把增长做出来。",
    "> **我们不会为 PPT 里的 AI 故事下注。我们先一起做出真实结果，再把自己的资本放进去。**",
    "Ha7ch 最终要做的，不是把更多 AI 工具卖给传统企业。",
    "Ha7ch 要用 AI 改造资本，批量重做下一代公司。",
  ],
  en: [
    "Ha7ch's latest business model has a formal name: **AI Transformation Capital**.",
    "Ha7ch first uses FDEs to enter traditional enterprises, understand them through real work, and discover the value AI can create. It then invests in the small number worth backing for the long term, while the FDEs who carry the transformation receive long-term incentives. The enterprise, the FDE, and Ha7ch share the value created by rebuilding the company with AI.",
    "> **Venture capital funds new companies. AI Transformation Capital rebuilds existing ones.**",
    "1. Capital used to select companies. It can now transform them",
    "Traditional investment firms create value primarily through selection. They study industries, financial statements, and management teams, invest, and wait for the company to execute.",
    "AI changes that premise. Much of a traditional enterprise's latent value sits inside quotation, production, finance, sales, supply chains, customer service, and organizational coordination. Unlocking it requires people who can redesign business, product, engineering, and organization together.",
    "Ha7ch therefore does not want to stand outside enterprises and select winners. It enters the company, discovers how it can change, and uses capital to scale that change.",
    "2. The FDE is field diligence for AI Transformation Capital",
    "A conventional investor understands an enterprise mainly through information the company presents. An FDE understands it while solving real problems.",
    "Field work reveals the judgment of senior leadership, the execution of middle management, the reality of frontline work, the credibility of data, the ability of departments to collaborate, and the actual effect AI can have on revenue, cost, efficiency, and risk.",
    "> **The FDE is the technical diligence layer closest to operations and the first discoverer of AI value.**",
    "If Ha7ch serves ten or twenty enterprises deeply, it may discover three or five worth backing for the long term. That is closer to reality than hearing twenty AI stories in a meeting room.",
    "3. How AI Transformation Capital works",
    "The model begins with an ordinary enterprise engagement. The enterprise pays for real diagnosis, design, and delivery. The FDE receives the service fee. Ha7ch does not take a commission from normal cooperation between the enterprise and the FDE.",
    "Most engagements may remain projects. A small number enter Ha7ch's long-term selection process, based on whether the enterprise opens real problems, acts on evidence, executes organizationally, and produces verifiable results.",
    "After investment, Ha7ch stands on the same long-term outcome as the enterprise. The FDE receives incentives that vest against transformation milestones. The enterprise, the FDE, and Ha7ch begin growing the same pool of value.",
    "4. Turning three parties into one community of interest",
    "The core of AI Transformation Capital is to bind the enterprise, the FDE, and Ha7ch into a long-term community of interest instead of leaving them in a one-off transaction.",
    "The enterprise gains growth through AI transformation. The FDE shares the value created through long-term incentives. Ha7ch earns equity appreciation through investment. The three parties stop optimizing separately for procurement cost, project income, and platform commission, and begin optimizing for one result: making the enterprise more valuable.",
    "> **The three parties are not locked together by a contract. They are aligned by an incentive structure.**",
    "If the enterprise grows, all three benefit. If it does not, all three bear opportunity cost and investment risk. Risk and reward come from the same result, which is what makes the community of interest real.",
    "5. How AI Transformation Capital makes money",
    "The model separates two accounts.",
    "Service fees pay for work already completed and belong to the FDE or delivery team. Ha7ch does not build its economics on labor arbitrage.",
    "Equity represents value that will continue to be created. When Ha7ch identifies an enterprise worth backing, it invests its own capital, shares the risk, and participates in the future growth.",
    "The FDE's long-term incentives ensure that the person closest to the field earns not only once for completing a project, but also from the enterprise's long-term growth.",
    "> **Service fees buy completed work. Equity buys value that will continue to be created.**",
    "Ha7ch's real return does not come from the FDE's labor margin. It comes from equity appreciation after the invested enterprise completes its AI transformation.",
    "6. RMB 3 million and RMB 300,000 are an explanatory model",
    "In one hypothetical example, an enterprise is valued at RMB 400 million. After a real engagement and diligence, Ha7ch invests RMB 3 million for a corresponding stake and reserves RMB 300,000 worth of related rights for the on-site FDE, vesting against milestones.",
    "If the company grows from RMB 400 million to RMB 800 million, both Ha7ch's stake and the FDE's long-term incentive grow. If the expected growth does not appear, Ha7ch bears the investment loss.",
    "The figures explain the mechanism only. They are not standard pricing, signed terms, or a return promise. Every company still requires independent diligence, valuation, negotiation, and compliance design.",
    "The point is not RMB 3 million or RMB 300,000. It is that all three parties finally earn from the same result: long-term growth in enterprise value.",
    "7. What each party contributes",
    "The enterprise contributes real operations, management authority, organizational cooperation, and long-term rights. The FDE contributes business judgment, product definition, engineering, communication, and execution. Ha7ch contributes capital, brand, enterprise access, its FDE network, cross-company knowledge, technology, and continuing organizational capacity.",
    "The enterprise retains control and most of the value. The FDE earns long-term reward aligned with contribution. Ha7ch earns equity appreciation through capital and continuous capability.",
    "This is not a one-off delivery relationship. It is a commercial structure connecting service, diligence, investment, and enterprise transformation.",
    "8. Why the enterprise cannot simply hire the FDE away",
    "It can. If Ha7ch contributes only one introduction, bypassing Ha7ch is rational and no exclusivity clause can permanently solve that problem.",
    "Ha7ch must continue supplying what one FDE cannot provide alone: new Builders, cross-company learning, evolving methods and technology, complex-project coordination, talent development, brand trust, capital, and the full resources required for the next phase.",
    "> **One person can be hired. A continuously evolving network is difficult for one enterprise to reproduce alone.**",
    "9. Which enterprises deserve investment",
    "AI Transformation Capital is not the default structure for every customer. Most enterprises can continue on a project basis. Only a small number advance to investment.",
    "A company worth backing must open real operations and workflows, act on evidence, contain meaningful verifiable value, and allow those who create long-term value to share in it.",
    "Across race-team collaboration, accounting knowledge and document processing, and quotation and production workflows in a Greater Bay Area manufacturer, we have repeatedly seen the same pattern: the most valuable AI opportunity rarely arrives as a clean requirements document. It has to be discovered in the field.",
    "10. AI Transformation Capital is not a fixed legal structure",
    "It is the name of a business model, not a fund product or a single legal vehicle. A specific project may use direct equity, a project company, a dedicated vehicle, or another compliant structure.",
    "The underlying logic remains the same: understand the enterprise through real service, invest only after validation, give the FDE long-term rights, and let the enterprise, the FDE, and Ha7ch share the growth in enterprise value.",
    "11. Final definition",
    "AI Transformation Capital uses FDEs as field diligence and transformation operators, invests in traditional enterprises, and uses long-term enterprise value growth as its primary return while binding the enterprise, the FDE, and Ha7ch into a long-term community of interest.",
    "It connects four activities that used to be separate: serving the enterprise, understanding the enterprise, transforming the enterprise, and investing in the enterprise.",
    "Ordinary capital searches for growth that already exists. AI Transformation Capital enters the enterprise and creates growth with it.",
    "> **We do not invest in AI stories told through slides. We first create a real result together, then put our own capital behind it.**",
    "Ha7ch will use AI Transformation Capital to rebuild the next generation of companies at scale.",
  ],
};

export default article;

