import type { Article } from "./types";

const article: Article = {
  slug: "ai-upside-partner",
  titleZh: "AI 增量合伙人：Ha7ch 最新商业模式的正式定义",
  titleEn: "AI Upside Partner: Ha7ch's New Business Model",
  date: "2026-08-15",
  dateDisplay: "Aug 15",
  descriptionZh:
    "Ha7ch 不从 FDE 与企业的正常合作中抽成，而是从真实服务过的传统企业中选择少数值得长期投资的对象，让企业、FDE 与 Ha7ch 共同分享 AI 改造创造的长期增量。",
  description:
    "Ha7ch does not take a cut from ordinary work between FDEs and enterprises. It selects a small number of companies it has served and understood deeply, invests in them, and aligns the enterprise, the FDE, and Ha7ch around the long-term upside created through AI transformation.",
  keywords: [
    "AI 增量合伙人",
    "AI Upside Partner",
    "FDE",
    "AI Native Company",
    "AI Native investor",
    "enterprise AI",
    "traditional enterprise",
    "equity",
    "HA7CH",
  ],
  zh: [
    "Ha7ch 最新的商业模式，正式命名为：AI 增量合伙人。",
    "它的定义很简单：Ha7ch 不依靠 FDE 的外包收入赚钱，而是从真实服务过的传统企业中，选择少数值得长期投资的对象，让企业、FDE 与 Ha7ch 共同分享 AI 改造创造的长期增量。",
    "压缩成一句话：先一起把增量做出来，再一起持有增量。",
    "一、我们要分享的不是项目收入，而是企业增量",
    "今天企业 AI 服务最常见的收入，仍然来自软件订阅、项目报价和人天费用。做一个知识库收一笔钱，部署一个 Agent 收一笔钱，派一个 FDE 驻场再收一笔钱。",
    "这套模式可以养活一家服务公司，却存在一个根本问题：服务方的收益与交付规模相关，不与企业最终获得的价值相关。",
    "一个项目可能只收 20 万元，却帮助企业每年节省 500 万元；也可能收了 200 万元，最后只留下一个没人使用的 Demo。只按项目收费时，服务方真正优化的是签单和交付，企业真正关心的却是经营结果。",
    "AI 增量合伙人模式要重新对齐这两个目标。",
    "FDE 正常完成的工作，仍然按照正常价格收费。价值 10 万元的工作就收 10 万元，价值 20 万元的工作就收 20 万元。Ha7ch 不从 FDE 与企业之间的正常合作中抽成。",
    "Ha7ch 真正要获得的回报，来自服务之外：当我们确认一家企业具备 AI Native 增长潜力，就投入自己的资本，获得相应股权，和企业一起承担风险，也一起分享未来价值。",
    "服务费支付已经完成的劳动，股权对应未来仍然持续创造的价值。两笔账必须同时存在，也必须清楚分开。",
    "二、为什么 FDE 能够发现传统投资人看不到的企业",
    "传统投资人主要通过财务报表、管理层访谈、行业数据和短期尽调理解一家企业。FDE 对企业的理解方式完全不同。",
    "FDE 要真正进入企业解决问题。他会看到高层有没有远见，能不能根据事实作出行动；中层有没有管理和执行能力；基层每天的真实工作如何发生。",
    "他也会看到这家企业的数据是否可信，流程是否能够被改造，部门之间如何协作，员工是否愿意使用新工具，以及 AI 到底能给收入、成本、效率和风险带来多大的真实变化。",
    "这些信息不会完整地出现在一份商业计划书里。它们藏在 PDF、Excel、CAD、纸质单据、系统切换、口头经验、异常处理和跨部门扯皮里。",
    "所以 FDE 不只是交付者。他也是最接近经营现场的技术尽调者，是 AI 增量的第一发现人。",
    "如果 Ha7ch 真正服务十家、二十家企业，就有机会从中发现三家、五家值得长期投资的公司。这比在会议室里听二十家企业讲 AI 故事，更接近真实。",
    "三、这套商业模式如何运行",
    "第一步，企业和 FDE 按照正常商业规则合作。企业购买真实交付，FDE 获得服务收入，Ha7ch 不抽佣。",
    "第二步，Ha7ch 在真实合作中持续判断企业。我们关心的不是老板会不会讲 AI，而是企业是否愿意开放真实问题、组织是否能够执行、改造是否已经产生可核验结果，以及更大范围的增长是否可能发生。",
    "第三步，Ha7ch 只对少数通过验证的企业进行投资。投资以后，Ha7ch 不再只是服务关系中的第三方，而是和企业站在同一张长期利益表上。",
    "第四步，为真正承担改造责任的 FDE 配置长期权益。权益按照阶段性目标逐步归属，让 FDE 不只因为完成一个项目获得收入，也因为持续创造企业价值获得回报。",
    "第五步，Ha7ch 继续为企业提供新的 FDE、方法、案例、技术能力、组织支持和下一阶段改造资源。投资不是合作的终点，而是长期关系的开始。",
    "四、300 万与 30 万只是一个解释模型",
    "我们此前举过一个假设：一家传统企业估值 4 亿元，Ha7ch 投入 300 万元取得相应股权，并从相关权益中预留价值 30 万元的部分，分阶段激励驻场 FDE。",
    "如果企业未来从 4 亿元增长到 8 亿元，Ha7ch 的股权与 FDE 的长期权益都会随之增长；如果改造没有产生预期价值，Ha7ch 也必须承担投资损失。",
    "这组数字的作用只是解释机制。它不是固定报价，不是已经签署的标准条款，也不是收益承诺。每一家企业都需要独立完成尽调、估值、谈判和合规设计。",
    "真正重要的不是 300 万或 30 万，而是三方的收益终于来自同一个结果：企业长期价值的增长。",
    "五、三方各自投入什么，又分别得到什么",
    "企业投入真实场景、业务资料、管理授权、组织配合与长期权益。它得到的不是一次演示，而是一支愿意和它共同承担结果的外部 AI 能力。",
    "FDE 投入业务判断、产品定义、工程实现、现场沟通和长期执行。他得到正常服务收入，同时有机会获得与阶段性结果绑定的长期权益。",
    "Ha7ch 投入资本、品牌、企业资源、FDE 网络、跨企业经验、技术基础设施和持续组织能力。Ha7ch 的回报不来自抽走 FDE 的劳动收入，而来自所投资企业的长期成长。",
    "企业保留经营主体和绝大多数增长价值，FDE 获得与贡献相匹配的长期回报，Ha7ch 通过资本与持续能力获得股权增值。三方不是一次性交付关系，而是共同做大同一块增量。",
    "六、为什么企业不能直接把 FDE 挖走",
    "准确地说，企业当然可以直接聘用一个 FDE。甚至在某些阶段，这可能正是合理选择。",
    "如果 Ha7ch 的价值只是介绍一次人，那么企业和 FDE 建立信任以后绕过 Ha7ch，是完全理性的。任何只完成一次撮合的平台，都无法靠合同永久封住这个漏洞。",
    "所以 Ha7ch 必须持续提供单个 FDE 无法独立提供的东西：新的 Builder、跨企业经验、持续更新的方法和技术、复杂项目的协同、人才培养、品牌信用、资本支持，以及下一阶段改造所需的完整资源。",
    "一个人可以被雇佣，一张持续进化的网络很难被一家企业独自复制。",
    "如果 Ha7ch 无法继续创造这些价值，企业和 FDE 就没有理由把 Ha7ch 留在关系里。这个问题不能主要靠排他条款解决，只能靠持续价值解决。",
    "七、Ha7ch 选择什么样的企业",
    "AI 增量合伙人不是所有客户的默认合作方式。大部分企业可以继续按项目合作，只有少数企业会进入投资阶段。",
    "值得长期投资的企业，至少需要表现出四个信号：愿意开放真实材料与真实流程；管理层能够根据证据行动；业务中存在足够大的可验证增量；企业愿意让创造长期价值的人分享长期价值。",
    "我们已经在赛车协作、财会知识与材料处理、湾区制造业报价和生产流程中反复看到同一件事：企业最有价值的 AI 机会，通常不会以一份清晰需求文档出现。它要靠人进入现场，从大量琐碎、重复、跨系统但又直接影响经营的工作里挖出来。",
    "因此，Ha7ch 未来既要筛选优秀的 FDE，也要筛选优秀的传统企业。",
    "就像一家创业公司会说自己拿到了 YC 的投资一样，未来一家优秀的传统企业也可以说：我们拿到了 Ha7ch 的投资。",
    "这句话意味着的不是它买过几个 AI 工具，而是 Ha7ch 已经用真实合作完成判断，并愿意把自己的资本、人才与信用一起押在这家企业的 AI Native 增长上。",
    "八、最终定义",
    "AI 增量合伙人不是一个基金名称，也不是某一种固定法律载体。它首先是一套商业关系：FDE 深入企业发现价值，Ha7ch 投资经过验证的企业，企业、FDE 与 Ha7ch 共同分享 AI 改造带来的长期增量。",
    "具体项目可以采用股权投资、项目公司、专项载体或其他合规结构，但底层关系不变。",
    "我们不会为 PPT 里的 AI 故事下注。我们先一起做出真实结果，再把自己的资本放进去。",
    "Ha7ch 不只帮助企业使用 AI。Ha7ch 要成为企业的 AI 增量合伙人。",
  ],
  en: [
    "Ha7ch's latest business model now has a formal name: AI Upside Partner.",
    "The definition is simple. Ha7ch does not make money by taking a cut from FDE outsourcing income. It selects a small number of traditional enterprises it has genuinely served, invests in those worth backing for the long term, and aligns the enterprise, the FDE, and Ha7ch around the upside created through AI transformation.",
    "In one sentence: create the upside together, then own the upside together.",
    "1. The value to share is enterprise upside, not project revenue",
    "Most enterprise AI revenue still comes from software subscriptions, project fees, and billable days. A knowledge base produces one fee, an Agent deployment another, and an on-site FDE another.",
    "That model can sustain a service business, but it has a fundamental problem: the provider's revenue tracks the scale of delivery rather than the value the enterprise ultimately receives.",
    "A RMB 200,000 project may save an enterprise RMB 5 million every year. Another project may charge RMB 2 million and leave behind a demo nobody uses. Under project pricing alone, the provider optimizes for sales and delivery while the enterprise cares about operating results.",
    "The AI Upside Partner model aligns those objectives again.",
    "FDE work is still paid at normal rates. Work worth RMB 100,000 earns RMB 100,000; work worth RMB 200,000 earns RMB 200,000. Ha7ch does not take a cut from ordinary cooperation between the FDE and the enterprise.",
    "Ha7ch earns its real return outside the service contract. When we confirm that an enterprise has AI-native growth potential, we invest our own capital for equity, take risk alongside the enterprise, and share in its future value.",
    "Service fees pay for work already completed. Equity corresponds to value still being created. The two must coexist and remain clearly separated.",
    "2. Why FDEs can discover companies conventional investors miss",
    "Conventional investors mainly understand a company through financial statements, management interviews, industry data, and short diligence processes. An FDE learns about a company in a completely different way.",
    "The FDE enters the enterprise and solves real problems. This reveals whether senior leaders have vision and act on facts, whether middle management can execute, and how frontline work actually happens.",
    "It also reveals whether data can be trusted, workflows can be changed, departments can collaborate, employees will adopt new tools, and how much AI can change revenue, cost, productivity, and risk.",
    "This information rarely appears in a complete business plan. It lives inside PDFs, spreadsheets, CAD files, paper forms, system switching, tacit knowledge, exception handling, and cross-functional friction.",
    "The FDE is therefore more than a delivery engineer. The FDE is the technical diligence layer closest to operations and the first discoverer of AI upside.",
    "If Ha7ch genuinely serves ten or twenty enterprises, it may discover three or five worth backing for the long term. That is closer to reality than hearing twenty AI stories in a meeting room.",
    "3. How the model works",
    "First, the enterprise and the FDE work together under normal commercial terms. The enterprise buys real delivery, the FDE earns service revenue, and Ha7ch takes no commission.",
    "Second, Ha7ch continuously evaluates the enterprise through the real engagement. We care less about whether the founder can talk about AI than whether the company opens real problems, the organization can execute, the transformation produces verifiable results, and larger growth may follow.",
    "Third, Ha7ch invests only in a small number of enterprises that pass this validation. After investing, Ha7ch is no longer merely a third party in a service relationship. It stands on the same long-term cap table as the enterprise.",
    "Fourth, the FDEs who carry real transformation responsibility receive long-term incentives that vest against milestones. They earn income for completing a project and upside for continuing to create enterprise value.",
    "Fifth, Ha7ch continues providing new FDEs, methods, cases, technical capabilities, organizational support, and resources for the next phase. Investment is not the end of the relationship. It is the beginning of a long-term one.",
    "4. RMB 3 million and RMB 300,000 are an explanatory model",
    "We previously offered a hypothetical example: a traditional enterprise is valued at RMB 400 million; Ha7ch invests RMB 3 million for a corresponding stake and reserves RMB 300,000 worth of the related equity as a staged incentive for the on-site FDE.",
    "If the enterprise later grows from RMB 400 million to RMB 800 million, both Ha7ch's stake and the FDE's long-term incentive grow with it. If the transformation fails to create the expected value, Ha7ch must also bear the investment loss.",
    "These figures only explain the mechanism. They are not fixed pricing, signed standard terms, or a return promise. Every enterprise requires independent diligence, valuation, negotiation, and compliance design.",
    "The important point is not RMB 3 million or RMB 300,000. It is that all three parties finally earn from the same result: long-term growth in enterprise value.",
    "5. What each party contributes and receives",
    "The enterprise contributes real operating environments, business material, management authority, organizational cooperation, and long-term equity. It receives an external AI capability willing to share responsibility for outcomes, not a one-off demonstration.",
    "The FDE contributes business judgment, product definition, engineering, field communication, and long-term execution. The FDE earns normal service revenue and may receive long-term incentives tied to staged results.",
    "Ha7ch contributes capital, brand, enterprise access, an FDE network, cross-company knowledge, technical infrastructure, and continuous organizational capacity. Its return comes from the growth of the enterprises it invests in, not from taking the FDE's labor income.",
    "The enterprise retains control and most of the value it creates. The FDE receives long-term reward aligned with contribution. Ha7ch earns equity appreciation through capital and continuing capability. The three parties are growing the same pool of upside rather than completing a one-off delivery.",
    "6. Why the enterprise cannot simply hire the FDE away",
    "Strictly speaking, the enterprise can hire an FDE directly. At some stages, that may even be the right decision.",
    "If Ha7ch's only value is one introduction, bypassing Ha7ch after the enterprise and FDE establish trust is completely rational. No marketplace that performs only one match can permanently close that gap with a contract.",
    "Ha7ch must therefore keep providing what one FDE cannot provide alone: new Builders, cross-enterprise knowledge, continuously updated methods and technology, coordination for complex projects, talent development, brand trust, capital support, and the complete resources required for the next phase.",
    "One person can be hired. A continuously evolving network is difficult for one enterprise to reproduce alone.",
    "If Ha7ch cannot continue creating this value, neither the enterprise nor the FDE has a reason to keep Ha7ch in the relationship. This problem cannot be solved primarily through exclusivity. It can only be solved through continuous value.",
    "7. Which enterprises Ha7ch will choose",
    "An AI Upside Partnership is not the default arrangement for every customer. Most enterprises may continue working on a project basis. Only a small number will advance to investment.",
    "An enterprise worth backing should show at least four signals: it opens real materials and workflows; management acts on evidence; the business contains meaningful, verifiable upside; and the enterprise lets the people who create long-term value share in that value.",
    "Across race-team collaboration, accounting knowledge and document processing, and quotation and production workflows in a Greater Bay Area manufacturer, we have repeatedly seen the same pattern: the most valuable AI opportunity rarely arrives as a clean requirements document. It must be discovered in the field, inside work that appears mundane, repetitive, fragmented across systems, and yet directly affects operations.",
    "Ha7ch will therefore select both exceptional FDEs and exceptional traditional enterprises.",
    "Just as a startup may say it received investment from YC, an exceptional traditional enterprise may one day say: we received investment from Ha7ch.",
    "That statement would not mean it purchased a few AI tools. It would mean Ha7ch completed its judgment through real work and chose to place its own capital, talent, and credibility behind the enterprise's AI-native growth.",
    "8. Final definition",
    "AI Upside Partner is not the name of a fund or a fixed legal vehicle. It is first a commercial relationship: FDEs enter enterprises and discover value; Ha7ch invests in companies that have passed real validation; and the enterprise, the FDE, and Ha7ch share the long-term upside created through AI transformation.",
    "A specific engagement may use direct equity investment, a project company, a dedicated vehicle, or another compliant structure. The underlying relationship remains the same.",
    "We do not invest in an AI story told through slides. We first create a real result together, then place our own capital behind it.",
    "Ha7ch does more than help enterprises use AI. Ha7ch becomes their AI Upside Partner.",
  ],
};

export default article;
