import type { Article } from "./types";

const article: Article = {
  slug: "ai-upside-partner",
  titleZh: "AI 增量合伙人：Ha7ch 最新商业模式的正式定义",
  titleEn: "AI Upside Partner: Ha7ch's New Business Model",
  date: "2026-08-15",
  dateDisplay: "Aug 15",
  descriptionZh:
    "AI 增量合伙人，是一套由 48H FDE、ANC 与股权共同组成的长期合作机制：先证明 AI 增量，再共同完成增量，最后由企业、FDE 与 Ha7ch 共同持有增量。",
  description:
    "An AI Upside Partnership combines 48H FDE, ANC, and equity in one long-term mechanism: prove the AI upside, build it together, and let the enterprise, the FDE, and Ha7ch share what is created.",
  keywords: [
    "AI 增量合伙人",
    "AI Upside Partner",
    "FDE",
    "48H FDE",
    "AI Native Company",
    "ANC",
    "enterprise AI",
    "traditional enterprise",
    "equity",
    "HA7CH",
  ],
  zh: [
    "Ha7ch 最新的商业模式，正式命名为：AI 增量合伙人。",
    "它的运行公式是：48H FDE × ANC × Equity。",
    "AI 增量合伙人，是 Ha7ch 与具备 AI Native 增长潜力的传统企业建立长期利益关系：先由 FDE 进入真实现场，找到 AI 能够创造的可核验增量；再通过 ANC 把一次改造沉淀成企业持续运转的能力；最后通过股权，让企业、FDE 与 Ha7ch 共同持有这部分长期增量。",
    "压缩成一句话：先证明增量，再共同完成增量，最后共同持有增量。",
    "一、AI 增量不是一个功能，而是企业价值的变化",
    "企业购买一个模型账号、上线一个知识库、做出一个报价 Agent，都不自动等于产生了 AI 增量。",
    "只有当一个真实经营指标发生变化，增量才成立。它可以是报价周期从三天缩短到三小时，可以是五百份材料从人工整理两周变成一天完成，可以是新人上手时间缩短，可以是错误率下降，也可以是企业第一次把原来无法承接的订单变成收入。",
    "因此，AI 增量必须同时满足三个条件：发生在真实流程里；能够被企业自己核验；最终指向降本、增效、增收或风险控制中的至少一个结果。",
    "模型能力只是输入。功能上线只是过程。经营结果的变化，才是增量。",
    "二、为什么第一步必须是 48H FDE",
    "传统投资人主要通过报表、管理层访谈和行业数据理解一家企业。FDE 则在解决真实问题的过程中理解企业。",
    "他会同时看到高层是否愿意根据证据行动，中层是否具备管理和执行能力，基层的真实工作如何发生；也会看到数据是否可信、流程是否能够被改造、组织是否愿意采用，以及 AI 到底能够创造多少价值。",
    "这些信息无法只靠会议室里的尽调获得。它们藏在 PDF、Excel、CAD、纸质单据、系统切换、口头经验、异常处理和跨部门扯皮里。",
    "48H FDE 的任务，是用一个面和一个点完成第一轮判断。一个面，是把多角色共同参与的真实工作流摸清楚；一个点，是用真实材料跑通一条足够窄、但端到端闭环的链路，并留下可回到原件的证据。",
    "48 小时不是承诺完成改造，而是用最低成本回答两个更重要的问题：这里有没有真实的 AI 增量？这家企业是否值得双方继续投入？",
    "FDE 因而不只是交付者。他也是最接近经营现场的技术尽调者，是 AI 增量的第一发现人。",
    "三、为什么只有 FDE 还不够",
    "一个优秀的 FDE 可以在现场做出结果，但一次结果不会自动变成一家 AI Native Company。",
    "如果知识仍然留在个人电脑里，工作方法仍然依赖某个驻场的人，Agent 无法读取统一的企业 Context，权限、评测和反馈没有沉淀，那么 FDE 一旦离场，改造就可能停止。",
    "ANC 的作用，是把 FDE 在现场发现的方法变成企业自己的基础设施。企业的文件、数据和人的经验进入 Context；可重复的方法被写成 Skills；Agent 通过 Harness 执行任务；飞书、钉钉、WPS、Web 和 API 成为 Gateway；权限、Evals 与审计共同约束系统边界。",
    "48 小时找到第一条证据，48 天让它进入真实使用，48 周让企业围绕经过验证的人机协作重新分配责任。",
    "FDE 负责把 AI 带进现场，ANC 负责让 AI 留在组织里。",
    "四、为什么最后必须进入 Equity",
    "如果 Ha7ch 只按项目收费，它得到的收入与交付工时相关；如果企业因为这次改造获得了数年的增长，双方的收益仍然没有真正对齐。",
    "AI 增量合伙人模式会保留正常的服务费用。FDE 完成价值 10 万元的工作，就应该获得相应的交付收入。Ha7ch 不从 FDE 与企业之间的正常合作中抽成。",
    "但在服务之外，Ha7ch 会从已经完成真实验证的企业里，选择少数值得长期投入的对象，通过投资获得股权，并为关键 FDE 设计分阶段归属的长期权益。",
    "例如，在我们此前提出的假设模型里，Ha7ch 向一家传统企业投入 300 万元，并从相关权益中预留价值 30 万元的部分，用于激励完成阶段性改造目标的驻场 FDE。这里的金额只是解释机制的示例，不是固定报价、已签条款或收益承诺。每一家企业仍然需要独立尽调、估值、谈判和合规设计。",
    "服务费支付已经完成的劳动，股权奖励未来仍然持续创造的价值。两者必须同时存在，也必须被清楚分开。",
    "当 AI 增量最终没有出现，Ha7ch 的投资也要承担损失；当企业真正完成增长，企业原有股东、FDE 与 Ha7ch 一起分享结果。这才叫利益对齐。",
    "五、三方各自投入什么",
    "企业投入真实场景、业务资料、管理授权与组织配合，并允许改造进入核心流程。它不能只提供一批脱敏样例，然后要求外部团队表演一个成功 Demo。",
    "FDE 投入现场判断、产品定义、工程实现、组织沟通和结果复盘。他对一个具体结果负责，而不是对功能数量负责。",
    "Ha7ch 投入资本、ANC 基础设施、FDE 网络、跨企业案例、Skills 的持续更新、评测与治理方法，以及帮助企业继续找到下一位合适 Builder 的能力。",
    "三方的关系不是甲方、平台和外包工程师，而是企业经营者、增量发现者与长期能力提供者。",
    "六、这套模式必须解决一个最危险的问题",
    "如果 Ha7ch 的价值只是把一个 FDE 介绍给一家企业，那么双方在建立信任后绕过 Ha7ch，是完全理性的。企业也可能直接用更高薪资或股权把 FDE 留下。任何只完成一次撮合的平台，都无法靠合同永久封住这个漏洞。",
    "所以 AI 增量合伙人模式成立的前提，是 Ha7ch 必须成为持续增值层。一个 FDE 可以被企业直接聘用，但企业仍然需要新的 Builder、不断更新的 Skills、ANC 的版本演进、跨行业经验、评测与治理、资本支持和下一阶段改造能力。",
    "如果 Ha7ch 无法持续提供这些价值，企业和 FDE 就没有理由继续把 Ha7ch 留在关系里。这个问题不能靠排他条款掩盖，只能靠持续创造价值解决。",
    "Ha7ch 要聚拢的不是一批等待被派单的人，而是一张任何单个企业都难以独自复制的 FDE 与 ANC 网络。",
    "七、Ha7ch 选择什么样的企业",
    "不是所有企业都适合进入 AI 增量合伙人模式。服务十家、二十家企业，最后只选择其中三家、五家长期投资，是这套模式正常的筛选结果。",
    "真正值得进入下一阶段的企业，至少会表现出四个信号：愿意开放真实材料与真实流程；管理层能够根据证据作出行动；业务中存在足够大的可验证增量；企业愿意让创造长期价值的人分享长期价值。",
    "我们已经在赛车协作、财会知识与材料处理、湾区制造业报价和生产流程中反复验证同一件事：企业最有价值的 AI 机会，通常不会以一份清晰需求文档出现。它要靠人进入现场，从大量琐碎、重复、跨系统但又直接影响经营的工作里被挖出来。",
    "因此，Ha7ch 未来既要筛选 FDE，也要筛选企业。一个企业获得 Ha7ch 的投资，不只意味着它买过 AI，而意味着它已经用自己的真实业务证明：这里存在可以被共同创造、共同持有的 AI 增量。",
    "八、最终定义",
    "AI 增量合伙人不是一个基金名称，也不是某一种固定的法律载体。它首先是一套商业关系：Ha7ch 用 48H FDE 发现增量，用 ANC 固化增量，用 Equity 对齐增量。具体项目可以根据企业与资金来源，分别采用股权投资、项目公司、专项载体或其他合规结构，但底层关系不变。",
    "我们不会为一个 PPT 里的 AI 故事下注。我们先进入现场，找到证据，再把自己的资本、系统和人放进去。",
    "Ha7ch 不只帮助企业使用 AI。Ha7ch 要成为企业的 AI 增量合伙人。",
  ],
  en: [
    "Ha7ch's latest business model now has a formal name: AI Upside Partner.",
    "Its operating formula is: 48H FDE × ANC × Equity.",
    "An AI Upside Partnership is a long-term alignment between Ha7ch and a traditional enterprise with the potential for AI-native growth. An FDE first enters the real operating environment and identifies verifiable upside that AI can create. ANC then turns a one-off intervention into a capability the enterprise can keep using. Equity finally allows the enterprise, the FDE, and Ha7ch to share the long-term value they create together.",
    "In one sentence: prove the upside, build the upside together, and share ownership of the upside.",
    "1. AI upside is not a feature. It is a change in enterprise value",
    "Buying model accounts, launching a knowledge base, or building a quotation agent does not automatically create AI upside.",
    "Upside exists only when a real operating metric changes. A quotation cycle may fall from three days to three hours. Five hundred documents that once required two weeks of manual work may be processed in one day. Onboarding time may shrink, errors may fall, or the company may turn previously unreachable orders into revenue.",
    "AI upside therefore has three conditions: it occurs inside a real workflow, the enterprise can verify it independently, and it ultimately contributes to lower cost, higher productivity, more revenue, or better risk control.",
    "Model capability is an input. Shipping a feature is a step. A measurable change in operations is the upside.",
    "2. Why the first step must be 48H FDE",
    "A conventional investor mainly learns about a company through financial statements, management interviews, and industry data. An FDE learns about the company while solving a real problem with it.",
    "The FDE sees whether senior leaders act on evidence, whether middle management can execute, and how frontline work actually happens. The FDE also sees whether the data can be trusted, whether the workflow can be changed, whether the organization will adopt the result, and how much value AI can realistically create.",
    "This information cannot be recovered from a meeting-room diligence process alone. It lives inside PDFs, spreadsheets, CAD files, paper forms, system switching, tacit knowledge, exception handling, and cross-functional friction.",
    "The job of 48H FDE is to complete the first judgment through one surface and one point. The surface maps the real workflow across roles. The point uses real material to complete one narrow but end-to-end chain, with evidence that links every result back to its source.",
    "Forty-eight hours is not a promise to complete the transformation. It is the lowest-cost way to answer two more important questions: is there real AI upside here, and is this enterprise worth further investment from both sides?",
    "The FDE is therefore more than a delivery engineer. The FDE is the technical diligence layer closest to operations and the first discoverer of AI upside.",
    "3. Why an FDE alone is not enough",
    "A strong FDE can create a result on site, but one result does not automatically create an AI Native Company.",
    "If knowledge remains on one person's computer, methods still depend on whoever is deployed, Agents cannot access a shared enterprise Context, and permissions, evaluation, and feedback are never captured, the transformation may stop as soon as the FDE leaves.",
    "ANC turns what the FDE learns in the field into infrastructure owned by the enterprise. Files, data, and human expertise enter Context. Repeatable methods become Skills. Agents execute through a Harness. Feishu, DingTalk, WPS, the web, and APIs act as Gateways. Permissions, Evals, and audit records define the boundaries.",
    "Forty-eight hours finds the first piece of evidence. Forty-eight days puts it into real use. Forty-eight weeks reallocates responsibility around validated human-Agent collaboration.",
    "The FDE brings AI into the field. ANC keeps AI inside the organization.",
    "4. Why the final layer must be Equity",
    "If Ha7ch charges only for projects, its revenue remains tied to delivery hours. If the enterprise gains years of growth from the transformation, the economics are still not fully aligned.",
    "The AI Upside Partner model preserves normal service fees. If an FDE completes RMB 100,000 worth of work, the FDE should receive the corresponding delivery income. Ha7ch does not take a cut from ordinary work between the FDE and the enterprise.",
    "Beyond the service engagement, however, Ha7ch will select a small number of enterprises that have passed real-world validation, invest for equity, and create staged long-term incentives for the key FDEs responsible for transformation milestones.",
    "In the hypothetical model we previously introduced, Ha7ch invests RMB 3 million in a traditional enterprise and reserves RMB 300,000 worth of the related equity to reward an on-site FDE as transformation milestones are completed. These figures illustrate the mechanism. They are not fixed pricing, signed terms, or a return promise. Every enterprise still requires independent diligence, valuation, negotiation, and compliance design.",
    "Service fees pay for work already completed. Equity rewards value that continues to be created. The two must coexist, and they must remain clearly separated.",
    "If the AI upside never appears, Ha7ch's investment must bear the loss. If the enterprise grows, its existing shareholders, the FDE, and Ha7ch share the outcome. That is real alignment.",
    "5. What each party contributes",
    "The enterprise contributes real operating environments, business material, management authority, and organizational cooperation. It cannot offer only sanitized samples and ask an outside team to perform a successful demo.",
    "The FDE contributes field judgment, product definition, engineering, organizational communication, and outcome reviews. The FDE owns a concrete result, not a feature count.",
    "Ha7ch contributes capital, ANC infrastructure, an FDE network, cross-enterprise cases, continuously updated Skills, evaluation and governance methods, and the ability to bring in the next suitable Builder as the transformation expands.",
    "The three parties are not a client, a marketplace, and an outsourced engineer. They are the operator of the enterprise, the discoverer of upside, and the long-term capability provider.",
    "6. The model must solve its most dangerous problem",
    "If Ha7ch's only value is introducing one FDE to one enterprise, bypassing Ha7ch after trust is established is rational. The enterprise may also retain the FDE directly with a higher salary or equity. No marketplace that performs only one introduction can permanently close this gap with a contract.",
    "The model therefore works only if Ha7ch becomes a continuous value layer. An enterprise may hire one FDE directly and still need new Builders, updated Skills, ANC version upgrades, cross-industry knowledge, evaluation and governance, capital support, and the capability for the next phase of transformation.",
    "If Ha7ch cannot keep delivering that value, neither the enterprise nor the FDE has a reason to keep Ha7ch in the relationship. This cannot be hidden behind exclusivity clauses. It can only be solved by continuously creating value.",
    "Ha7ch is not assembling a pool of people waiting for jobs. It is building an FDE and ANC network that no single enterprise can easily reproduce alone.",
    "7. Which enterprises Ha7ch will choose",
    "Not every enterprise belongs in an AI Upside Partnership. Serving ten or twenty companies and selecting only three or five for long-term investment is a normal outcome of the model.",
    "An enterprise worth advancing should show at least four signals: it opens real materials and workflows; management acts on evidence; the business contains meaningful, verifiable upside; and the enterprise is willing to let the people who create long-term value share in that value.",
    "Across race-team collaboration, accounting knowledge and document processing, and quotation and production workflows in a Greater Bay Area manufacturer, we have repeatedly seen the same pattern: the most valuable AI opportunity rarely arrives as a clean requirements document. It has to be discovered in the field, inside work that appears mundane, repetitive, fragmented across systems, and yet directly affects operations.",
    "Ha7ch will therefore select both FDEs and enterprises. When an enterprise receives investment from Ha7ch, it does not merely mean that the company purchased AI. It means the company has proved through its own operations that there is AI upside worth creating and owning together.",
    "8. Final definition",
    "AI Upside Partner is not the name of a fund or a fixed legal vehicle. It is first a commercial relationship: Ha7ch uses 48H FDE to discover upside, ANC to compound upside, and Equity to align upside. Depending on the enterprise and source of capital, a project may use direct equity investment, a project company, a dedicated vehicle, or another compliant structure. The underlying relationship remains the same.",
    "We do not invest in an AI story told through slides. We enter the field, find the evidence, and then deploy our own capital, systems, and people.",
    "Ha7ch does more than help enterprises use AI. Ha7ch becomes their AI Upside Partner.",
  ],
};

export default article;
