import type { Article } from "./types";

const article: Article = {
  slug: "anc-architecture",
  titleZh: "ANC 架构：AI Native Company 的 Harness",
  titleEn: "The ANC Architecture: The Harness for an AI Native Company",
  date: "2026-08-15",
  dateDisplay: "Aug 15",
  descriptionZh:
    "AI Native Company 是新的公司形态，ANC 架构是支撑它运行的 Harness：DATA 保留真实，CONTEXT 形成理解，HARNESS 组织行动，GATEWAY 接入工作。",
  description:
    "An AI Native Company is a new form of company. The ANC Architecture is its harness: DATA preserves reality, CONTEXT forms understanding, HARNESS organizes action, and GATEWAY connects the system to work.",
  keywords: [
    "ANC 架构",
    "AI Native Company",
    "ANC Architecture",
    "DATA",
    "CONTEXT",
    "HARNESS",
    "GATEWAY",
    "48 理论",
    "FDE",
    "HA7CH",
  ],
  zh: [
    "AI Native Company 是一种新的公司形态；ANC 架构，是支撑这种公司形态运行的 Harness。",
    "如果只记住一句话，可以记住这一句：AI Native Company 不是一家大量使用 AI 的公司，而是一家能够把真实工作持续压缩成企业 Context、Skills、Workflow、Evals 与权限系统，并让人和 Agent 共同在这套系统上工作的公司。",
    "ANC 架构也不是某一个模型、某一个 Agent、某一个知识库，或者某一套 SaaS。它是企业内部的一套可执行认知基础设施：DATA 负责保留事实，CONTEXT 负责组织事实，HARNESS 负责让事实进入行动，GATEWAY 负责让行动进入真实工作。",
    "DATA → CONTEXT → HARNESS → GATEWAY。",
    "这四层共同决定了一家公司是否只是「在用 AI」，还是开始成为一家 AI Native Company。",
    "一、AI Native Company 不是使用 AI 的公司",
    "今天几乎所有公司都可以说自己在用 AI。员工用大模型写邮件，市场用 AI 生成文案，财务用 AI 读表格，老板用 AI 总结会议。单点效率确实提高了，但公司的结构通常没有改变。",
    "知识仍然散落在个人电脑、聊天记录、共享盘和人的脑子里；流程仍然依赖老员工记得下一步该做什么；结果仍然要靠经理逐层确认；一个人离职，经验也跟着离开；一个项目结束，现场学到的东西很少进入下一次项目。",
    "这类公司只是 AI-enabled，不是 AI Native。",
    "AI Native 的分界线，不是模型能力有多强，而是组织是否具备学习能力。",
    "传统公司完成一次工作，得到一个结果。AI Native Company 完成一次工作，至少留下两样东西：结果，以及下一次能够直接复用的组织能力。",
    "一次客户问答，留下新的事实与来源；一次交付，留下新的 Skill 与 Workflow；一次判断失误，留下新的 Eval；一次权限事故，留下新的边界；一次人工接管，留下下一轮自动化的训练材料。",
    "因此，AI Native Company 最重要的指标不是「用了多少 AI」，而是：公司每工作一天，是否比昨天更懂自己。",
    "二、ANC 架构不是知识库，而是公司的 Harness",
    "很多企业建设 AI 的第一反应是做知识库。把 PDF、Excel、合同、制度、会议纪要和项目材料放进去，再接一个问答框。",
    "知识库解决的是「能不能找到一段内容」，但公司运行解决的是另一组问题：这段内容来自哪里？哪个版本有效？谁可以使用？它对应哪个客户、项目、设备或合同？找到以后应该触发什么动作？谁来确认？执行失败以后如何回退？",
    "只回答，不执行；只检索，不判断版本；只生成，不记录来源；只自动化，不定义责任边界。这样的系统不能成为公司的基础设施。",
    "Harness 的含义，是把模型约束在真实业务可以承受的轨道上。它不追求让 Agent 看起来无所不能，而是让 Agent 知道自己能看什么、能做什么、何时必须停下、何时必须把控制权交还给人。",
    "因此，ANC 架构的核心不是「把所有资料喂给 AI」，而是把企业事实、业务语义、执行方法、评测标准、权限边界和工作入口组织成一套可持续运行的系统。",
    "三、ANC 架构的四层结构",
    "第一层，DATA：原始事实层。",
    "DATA 包括 PDF、Excel、CAD、邮件、代码、合同、订单、财务凭证、系统数据库，也包括尚未被写下来的人的经验。它的第一原则不是清洗，而是保真：原件永远保留，来源永远可追溯，任何加工结果都不能覆盖原始事实。",
    "没有 DATA，AI 只能依赖公共世界知识；DATA 不可信，后面的所有智能都是更快地产生错误。",
    "第二层，CONTEXT：企业语义层。",
    "CONTEXT 不是把文档切块以后做向量检索。它要回答企业内部的「这是什么」：业务实体是什么，版本是什么，来源是什么，状态是什么，谁负责，谁能看，它与哪些客户、项目、合同、设备、人员和决策相关。",
    "同一句话，在制度、合同草案、已签合同和现场口述里，权威性完全不同；同一份报价，在讨论中、审批中、已发出和已作废四种状态下，也不能被系统当成同一个事实。",
    "CONTEXT 的目标，是建立企业的单一事实源。不是把所有信息集中到一个文件夹，而是让每一条重要信息都拥有身份、关系、状态、来源与责任。",
    "第三层，HARNESS：可执行能力层。",
    "HARNESS 由 Agent、Skills、Workflow、Evals、人工确认、权限与审计组成。它把「知道」变成「做到」。",
    "Skill 是企业经过验证的方法，Workflow 是这些方法在时间与角色上的编排，Agent 是持续读取 Context 并执行任务的运行单元，Eval 是判断结果能不能被接受的标准，人工确认是不可自动跨越的责任边界。",
    "一个成熟的 Harness 不以自动化率为唯一目标。它更关心正确任务有没有被正确的人和 Agent 在正确上下文里完成，并且全过程可观察、可中断、可恢复、可追责。",
    "第四层，GATEWAY：工作入口层。",
    "GATEWAY 是飞书、钉钉、Bot、WPS、Web、API，以及员工已经在使用的业务系统。它决定 ANC 架构是停留在演示里，还是进入每天真实发生的工作。",
    "企业不应该要求所有人先学习一个新的 AI 后台，再去寻找 AI 可以帮什么。Agent 应该进入原有入口：在项目群里响应，在表格里回写，在审批流里等待确认，在业务系统里读取状态，在必要时把任务交给人。",
    "DATA 决定系统知道什么，CONTEXT 决定系统如何理解，HARNESS 决定系统如何行动，GATEWAY 决定系统如何被使用。缺少任何一层，企业 AI 都会退化成 Demo。",
    "四、公司的信息只有三种归宿",
    "在 ANC 架构里，一条新信息进入公司以后，不能永远停在聊天记录里。它最终只有三种归宿。",
    "第一，进入事实层。它成为一个可追溯、带版本和状态的企业事实。",
    "第二，进入能力层。它被提炼成 Skill、Workflow、Eval 或权限规则，改变公司下一次如何工作。",
    "第三，被明确丢弃。它被判断为噪音、重复、失效或没有组织价值，并留下必要的处置记录。",
    "真正危险的不是信息被丢弃，而是信息既没有成为事实，也没有成为能力，却长期滞留在某个人的脑子、某个群聊或某张临时表里。传统公司的大量组织损耗，就发生在这个灰区。",
    "所以 ANC 架构不是一套存储系统，而是一套组织记忆的编译器：把现场发生的非结构化工作，编译成下一次可以执行的公司能力。",
    "五、一人一 Agent，全公司共享一个大脑",
    "ANC 架构不意味着全公司只部署一个万能 Agent。更合理的结构是：一人一 Agent，或者一岗一组 Agent；不同 Agent 拥有不同权限、目标和工作界面，但共享同一个经过治理的企业 Context。",
    "销售 Agent 理解客户、报价和跟进状态，财务 Agent 理解凭证、项目台账和审计规则，工程 Agent 理解代码、设备和变更记录，管理者 Agent 理解目标、风险和资源。但它们不能各自维护一套互相矛盾的公司事实。",
    "个人 Agent 解决的是工作界面，公共 Context 解决的是组织一致性。前者让每个人获得自己的执行杠杆，后者让整家公司共享一个大脑。",
    "这也是 ANC 架构与普通个人 Copilot 的根本区别。Copilot 让一个人更快；ANC 架构让一群人和 Agent 在同一事实、同一方法、同一责任系统上协作。",
    "六、三个案例证明的是同一套架构",
    "Climax Vault 是 Lawted 为跨时区赛车团队建立的知识协作系统。它以 2026 赛季指导手册为权威源，连接 Claude 与飞书，为不同角色提供入口，并稳定生成固定 11 个模块的中英双语 Team Guide。GitHub 中的更新会在最多约 15 分钟内同步到团队使用的系统。",
    "它证明的不是「AI 会读赛车资料」，而是公共规则、团队经验与角色化任务可以被组织成持续运行的 Context 与 Harness。资料更新以后，团队看到的是同一版本；不同角色进入以后，得到的是与职责相关的答案与行动。",
    "榆林专业服务企业的场景，是财会知识库与托管任务系统。48 小时内，团队围绕全所 68 个项目主台账、生产部署中的 5 个项目、4.4GB 原件、12 个财会 Skills 与 500 份 PDF 样例，做出了可验证 Demo；48H 验证后，双方签署了后续合作合同。",
    "这里最重要的也不是问答准确率，而是项目、原件、专业规则、任务与责任能否进入同一套可追溯系统。财会工作不能接受一个「大概正确」的答案，它要求来源、版本、项目归属、人工确认与审计链同时成立。",
    "湾区制造业的场景，把同一套架构放进制造企业的真实资料与流程中。48H 阶段验证完成后，双方签署了后续合同。",
    "制造业的难点不是缺少 PDF，而是图纸、表格、设备、报价、订单、变更和现场经验之间存在大量关系。系统必须知道哪一份是原件，哪一版有效，哪一个动作可以自动执行，哪一个判断必须由工程、业务或管理人员确认。",
    "三个案例表面上分别属于赛车协作、财会专业服务和湾区制造业，底层却是同一件事：把散落的 DATA 变成可理解的 CONTEXT，把可理解的 CONTEXT 变成受约束的 HARNESS，再通过原有 GATEWAY 进入真实工作。",
    "案例的意义不是证明某个行业已经被 AI 改造完成，而是证明 ANC 架构可以在不同业务现场，用同一套骨架建立可验证的第一条闭环。",
    "七、48 理论是 ANC 架构的建设顺序",
    "ANC 架构不能靠一场半年咨询从顶层设计出来。企业真正的 Context 藏在文件、系统、例外、责任冲突和人的动作里，必须通过真实工作被发现。",
    "所以第一阶段是 48 小时：找到一个高价值、可验收、可接入原始数据的最小闭环。目标不是完成转型，而是证明 DATA、CONTEXT、HARNESS、GATEWAY 四层能够在一个真实任务上连起来。",
    "第二阶段是 48 天：把一次性 Demo 变成可重复运行的系统。补齐数据治理、版本、权限、评测、人工确认、异常处理和更新机制，让组织开始积累自己的 Skills 与 Context。",
    "第三阶段是 48 周：让越来越多岗位与流程进入同一架构，重构信息如何流动、责任如何分配、经验如何沉淀。这个阶段改变的不是一个工具，而是公司的组织形态。",
    "48 小时验证闭环，48 天形成能力，48 周改变公司。",
    "48 理论不是对交付周期的营销承诺，而是对认知风险的控制：先用最小真实任务验证架构，再扩大系统边界；先证明公司能学习，再讨论公司能自动化多少。",
    "八、判断一家公司有没有 ANC 架构，看五个问题",
    "第一，事实是否可追溯？Agent 给出的关键答案，能否回到原件、版本、时间和责任人。",
    "第二，经验是否可执行？一个优秀员工的方法，能否被沉淀为其他人和 Agent 可以重复使用的 Skill、Workflow 与 Eval。",
    "第三，系统是否有边界？Agent 是否知道自己的权限、停止条件、人工确认点与失败回退路径。",
    "第四，工作是否进入原有入口？能力是否真正出现在员工每天使用的群、表格、审批和业务系统里，而不是只存在于演示后台。",
    "第五，公司是否会因为工作而更新自己？每一次交付、错误、接管和例外，是否会改变下一次系统如何行动。",
    "如果这五个问题都没有答案，再多 Agent 也只是工具堆叠。如果这五个问题开始被系统性回答，公司就已经在形成自己的 ANC 架构。",
    "结语",
    "AI Native Company 不是把 AI 加进旧公司的每一个角落，而是重新定义一家公司如何拥有事实、形成理解、执行任务与积累经验。",
    "ANC 架构就是这套新公司形态的 Harness：DATA 保留真实，CONTEXT 形成理解，HARNESS 组织行动，GATEWAY 接入工作。",
    "它最终要解决的不是「AI 能不能替人做一件事」，而是一个更硬的问题：一家公司能不能把每一次真实工作，都变成下一次可以复用的私有能力。",
    "当答案是能，这家公司才真正开始 AI Native。"
],
  en: [
    "An AI Native Company is a new form of company. The ANC Architecture is the harness that allows that company to operate.",
    "If you remember only one sentence, remember this: an AI Native Company is not a company that uses a lot of AI. It is a company that continuously compresses real work into enterprise Context, Skills, Workflows, Evals, and permission systems, then lets people and agents work together on top of them.",
    "The ANC Architecture is not a model, an agent, a knowledge base, or a SaaS stack. It is an executable cognitive infrastructure inside the enterprise: DATA preserves facts, CONTEXT organizes facts, HARNESS turns facts into action, and GATEWAY brings action into real work.",
    "DATA → CONTEXT → HARNESS → GATEWAY.",
    "These four layers determine whether a company merely uses AI or has begun to become an AI Native Company.",
    "1. An AI Native Company Is Not a Company That Uses AI",
    "Almost every company can now claim to use AI. Employees use models to write email, marketing teams generate copy, finance teams read spreadsheets, and executives summarize meetings. Local productivity improves, while the structure of the company usually remains unchanged.",
    "Knowledge is still scattered across personal computers, chat histories, shared drives, and people's heads. Processes still depend on a veteran remembering what comes next. Managers still confirm outcomes layer by layer. When someone leaves, their experience leaves too. When a project ends, little of what the team learned in the field enters the next project.",
    "That company is AI-enabled, not AI Native.",
    "The dividing line is not the intelligence of the model. It is whether the organization itself can learn.",
    "A traditional company completes a task and gets an outcome. An AI Native Company completes a task and leaves behind at least two things: the outcome and an organizational capability that can be reused next time.",
    "A customer question leaves a new fact and source. A delivery leaves a new Skill and Workflow. A bad judgment leaves a new Eval. A permission incident leaves a new boundary. A human takeover leaves training material for the next round of automation.",
    "The most important metric is therefore not how much AI a company uses, but whether every day of work leaves the company understanding itself better than it did yesterday.",
    "2. The ANC Architecture Is Not a Knowledge Base. It Is the Company's Harness",
    "The first instinct in enterprise AI is often to build a knowledge base: load PDFs, spreadsheets, contracts, policies, meeting notes, and project files, then attach a chat box.",
    "A knowledge base answers whether a passage can be found. A company must answer a different set of questions: Where did it come from? Which version is valid? Who may use it? Which customer, project, asset, or contract does it belong to? What action should follow? Who must confirm it? How does the system fall back when execution fails?",
    "A system that answers but cannot act, retrieves without judging versions, generates without recording sources, or automates without defining responsibility cannot become company infrastructure.",
    "A harness constrains a model to tracks the business can withstand. It does not try to make an agent appear omnipotent. It makes the agent know what it may see, what it may do, when it must stop, and when control must return to a person.",
    "The core of the ANC Architecture is not feeding every file to AI. It is organizing enterprise facts, business semantics, methods, evaluation standards, permission boundaries, and work interfaces into one durable operating system.",
    "3. The Four Layers of the ANC Architecture",
    "Layer one, DATA: the raw fact layer.",
    "DATA includes PDFs, spreadsheets, CAD files, email, code, contracts, orders, accounting evidence, system databases, and the experience that still exists only in people's heads. Its first principle is not cleaning but fidelity: originals are always retained, provenance is always traceable, and processed output never overwrites raw facts.",
    "Without DATA, AI can rely only on public world knowledge. When DATA is unreliable, every downstream intelligence layer merely produces errors faster.",
    "Layer two, CONTEXT: the enterprise semantic layer.",
    "CONTEXT is not vector retrieval over document chunks. It must answer what something means inside this company: the business entity, version, source, status, owner, access rules, and its relationships with customers, projects, contracts, assets, people, and decisions.",
    "The same sentence has completely different authority in a policy, a draft contract, a signed contract, and a field conversation. The same quotation cannot be treated as one fact when it is under discussion, awaiting approval, issued, or void.",
    "The goal of CONTEXT is an enterprise single source of truth. That does not mean putting everything in one folder. It means giving every important fact an identity, relationships, state, provenance, and owner.",
    "Layer three, HARNESS: the executable capability layer.",
    "HARNESS consists of agents, Skills, Workflows, Evals, human approvals, permissions, and audit trails. It turns knowing into doing.",
    "A Skill is a verified enterprise method. A Workflow orchestrates methods across time and roles. An agent continuously reads Context and performs tasks. An Eval defines whether the result is acceptable. Human approval marks a responsibility boundary automation may not cross.",
    "A mature harness does not optimize only for automation rate. It asks whether the right task was completed by the right combination of people and agents, in the right context, with the whole process observable, interruptible, recoverable, and accountable.",
    "Layer four, GATEWAY: the work interface layer.",
    "GATEWAY includes Feishu, DingTalk, bots, WPS, web interfaces, APIs, and the business systems employees already use. It determines whether the ANC Architecture remains a demo or enters daily work.",
    "Employees should not have to learn a new AI console before discovering what AI can do. Agents should enter existing interfaces: respond in project groups, write back to spreadsheets, wait inside approval flows, read state from business systems, and hand tasks to people when needed.",
    "DATA determines what the system knows. CONTEXT determines how it understands. HARNESS determines how it acts. GATEWAY determines how it is used. Remove any layer and enterprise AI collapses back into a demo.",
    "4. Information Has Only Three Valid Destinations",
    "Under the ANC Architecture, new information cannot remain forever in a chat history. It must end in one of three places.",
    "First, the fact layer: it becomes a traceable enterprise fact with a version and state.",
    "Second, the capability layer: it is distilled into a Skill, Workflow, Eval, or permission rule that changes how the company works next time.",
    "Third, explicit rejection: the company marks it as noise, duplication, expiration, or organizationally irrelevant, with any necessary disposition record.",
    "The dangerous case is not discarded information. It is information that becomes neither fact nor capability and remains inside one person's head, one group chat, or one temporary sheet. Much of a traditional company's organizational loss occurs in this gray zone.",
    "The ANC Architecture is therefore not a storage system. It is a compiler for organizational memory: it compiles unstructured field work into company capabilities that can execute next time.",
    "5. One Agent per Person, One Brain for the Company",
    "The ANC Architecture does not imply one universal agent for the entire company. A better structure is one agent per person, or a group of agents per role. Different agents have different permissions, goals, and interfaces, while sharing the same governed enterprise Context.",
    "A sales agent understands customers, quotations, and follow-up state. A finance agent understands evidence, project ledgers, and audit rules. An engineering agent understands code, equipment, and change records. A management agent understands goals, risks, and resources. They cannot maintain contradictory versions of company reality.",
    "Personal agents solve the work-interface problem. Shared Context solves organizational consistency. The former gives each person execution leverage; the latter gives the whole company one brain.",
    "This is the fundamental difference between the ANC Architecture and a personal copilot. A copilot makes one person faster. The ANC Architecture lets a group of people and agents collaborate on the same facts, methods, and responsibility system.",
    "6. Three Cases, One Architecture",
    "Climax Vault is the cross-time-zone racing knowledge collaboration system Lawted built for a racing team. It uses the 2026 season guide as an authoritative source, connects Claude and Feishu, provides role-specific entry points, and reliably generates a fixed 11-module bilingual Team Guide. Updates in GitHub synchronize to the team's system within roughly 15 minutes at most.",
    "It does not merely prove that AI can read racing material. It proves that public rules, team experience, and role-specific work can be organized into durable Context and Harness. When the source changes, the team sees one version. When different roles enter, they receive answers and actions relevant to their responsibilities.",
    "The Yulin professional-services case is a financial and accounting knowledge base with managed task execution. In 48 hours, the team built a verifiable demo around a master ledger of 68 projects, five projects in production deployment, 4.4 GB of original files, 12 accounting Skills, and a 500-PDF sample set. After the 48H validation, the two parties signed a follow-up cooperation contract.",
    "The important result was not merely question-answer accuracy. It was whether projects, originals, professional rules, tasks, and responsibility could enter the same traceable system. Accounting work cannot accept an approximately correct answer. Provenance, version, project ownership, human approval, and the audit chain must all hold at once.",
    "The Bay Area manufacturing case placed the same architecture inside real manufacturing documents and workflows. After completing the 48H-stage validation, the two parties signed a follow-up contract.",
    "The difficulty in manufacturing is not a shortage of PDFs. It is the dense web of relationships among drawings, spreadsheets, equipment, quotations, orders, revisions, and field experience. The system must know which file is original, which version is valid, which action may run automatically, and which judgment must be confirmed by engineering, business, or management.",
    "These cases appear to cover racing collaboration, professional accounting services, and Bay Area manufacturing. Underneath, they do the same thing: turn scattered DATA into understandable CONTEXT, understandable CONTEXT into constrained HARNESS, and HARNESS into real work through existing GATEWAYS.",
    "The cases do not prove that any industry has been fully transformed by AI. They prove that the same ANC skeleton can establish the first verifiable closed loop across very different business settings.",
    "7. The 48 Theory Is the Build Order",
    "The ANC Architecture cannot be produced by six months of top-down consulting. Real enterprise Context is hidden in files, systems, exceptions, conflicts of responsibility, and human actions. It must be discovered through real work.",
    "The first stage is 48 hours: find one high-value, testable minimum loop connected to raw data. The goal is not to complete a transformation. It is to prove that DATA, CONTEXT, HARNESS, and GATEWAY can connect around one real task.",
    "The second stage is 48 days: turn the one-off demo into a repeatable system. Complete data governance, versioning, permissions, evaluation, human approvals, exception handling, and update mechanisms so the organization begins to accumulate its own Skills and Context.",
    "The third stage is 48 weeks: bring more roles and workflows into the same architecture and reconstruct how information moves, responsibility is allocated, and experience accumulates. At this stage the change is not a tool. It is the form of the company.",
    "48 hours to validate the loop. 48 days to form a capability. 48 weeks to change the company.",
    "The 48 Theory is not a marketing promise about delivery speed. It is a method for controlling epistemic risk: validate the architecture with the smallest real task before expanding the system boundary; prove the company can learn before debating how much it can automate.",
    "8. Five Tests for an ANC Architecture",
    "First, are facts traceable? Can every important agent answer return to an original source, version, time, and owner?",
    "Second, is experience executable? Can a strong employee's method become a Skill, Workflow, and Eval that other people and agents can repeat?",
    "Third, does the system have boundaries? Does an agent know its permissions, stopping conditions, human approval points, and failure fallback path?",
    "Fourth, does the capability enter existing interfaces? Does it appear in the groups, spreadsheets, approval flows, and business systems employees use every day, rather than only in a demo console?",
    "Fifth, does the company update itself through work? Does every delivery, error, takeover, and exception change how the system acts next time?",
    "If these five questions have no answer, more agents only create a larger pile of tools. When a company begins to answer them systematically, it is beginning to form its ANC Architecture.",
    "Conclusion",
    "An AI Native Company does not add AI to every corner of an old company. It redefines how a company owns facts, forms understanding, executes work, and accumulates experience.",
    "The ANC Architecture is the harness for this new form: DATA preserves reality, CONTEXT forms understanding, HARNESS organizes action, and GATEWAY connects the system to work.",
    "Its final question is not whether AI can do one task for a person. It is a harder question: can a company turn every instance of real work into a private capability it can reuse next time?",
    "When the answer is yes, that company has truly begun to become AI Native."
],
};

export default article;
