import type { Article } from "./types";

const article: Article = {
  slug: "attention-is-all-you-need",
  titleZh: "Attention is All You Need",
  titleEn: "Attention is All You Need",
  date: "2026-05-11",
  dateDisplay: "May 11",
  zh: [
    "我觉得编程自媒体时代已经到来了。",
    "原来我们做一个项目，需要花很长时间。设计、开发、测试、再发布，整个流程跑下来动辄几个月，甚至几年。但是现在，你可以做得非常快。Vibe coding 一下，几个小时就是一个 MVP。",
    "这有点像写书。原来你写一本书，需要发版、需要选题、约稿、编辑、校对、印刷、发行，一两年是一个常态。但是现在你可以发布得非常的快，公众号、博客、推特，写完就发，几秒钟就完事了。",
    "在这种时候，最重要的事情就变了。它就像自媒体一样，最重要的是要找到你的用户。",
    "Attention is all you need.",
    "就像你拍了一个很好的电影，走过了所有流程，花了很长时间，终于他妈的大家可以在电影院里面看到了。结果你发现，没有人看你的电影。反而小杨哥的直播间非常的土，但却有一群人在看。",
    "但是很多人创业的时候还是会想：我先不需要找用户，推广不重要。我先把东西搭出来，先把工作流搭出来，然后再通过这套东西去找投资人，找完投资人拿到钱，拿了钱以后再去做推广。",
    "我去年其实也是这个想法。后来发现，这个想法大错特错。因为这个时代已经过去了。",
    "两年前你可以这么做，但是现在你不能。",
    "为什么？因为前两年大家都在炒概念，AI 很新。你可以先说，「哎，我要做一个 AI browser，我要做一个 AI 加他妈的医疗，AI 加什么健康」，AI 加什么、AI 加什么，你都能很快融到种子轮。然后种子轮的人会告诉你如何继续包装这个概念，帮他融到 A 轮，让种子轮的人能从中赚钱退出。",
    "这是原来的逻辑。但是现在，逻辑已经发生了翻天覆地的变化。",
    "现在的投资人已经非常务实了。你没有 ARR、没有 traction，他基本上不会给你一分钱。",
    "现在大家需要做的，如果是 toC，那就要做一些真正有用的东西。不然的话，不如回到 toB 上面来。",
    "By the way，我现在一直很看好 FDE 这个角色。在中国叫 AIBP，在美国叫 FDE。我自己在深圳就在做 FDE。下一篇文章有机会再和大家讲一讲这个内容。",
    "那回到普通人。我前面几篇文章其实已经说过了，你应该先把东西做一个 MVP，然后丢到社交媒体上，看有没有人感兴趣。有用户用了，你再继续做。而不是一上来就背一堆代码债。",
    "对于普通人而言，现在 code 这么便宜，你自己 vibe coding 写一些东西就好，不要一上来就搭什么工作流、什么复杂的系统。",
    "第一，它不一定是大家想要的。",
    "第二，这样会让你启动得非常慢。你会花一堆时间去想这个工作流应该怎么搭，甚至你会害怕做一个那么大的东西。",
    "对一个普通人而言，最重要的就是你能多快启动。今天下午能不能 ship 出去？睡觉之前能不能 ship 出去？这件事情决定了你的产品能多快到用户面前，多快抓住他们的注意力。",
  ],
  en: [
    "I think the era of programming we-media has arrived.",
    "In the past, when we wanted to do a project, it would take a lot of time. Design, develop, test, publish — the whole process needed a few months, or even a fucking year. But right now, you can do it in a real quick vibe-coding session, and ship an MVP within a couple hours.",
    "It's like writing a book. In the past, when you wanted to publish an idea, you had to choose the topic, do the editing, proofread, print, distribute. It took a long time. But right now you can publish in a real quick. Just post your idea on Twitter. A couple seconds.",
    "And at this moment, the most important thing changes. Just like I said — we are entering the we-media era.",
    "Attention is all you need.",
    "Imagine you make a great movie. You go through all the processes, you spend a lot of time, and finally people can see it in the cinema. But there is fucking no one. Meanwhile some random livestream is on, and a bunch of people are watching, dropping comments, even sending gifts.",
    "But a lot of people, when they're starting a business, are still thinking: I don't need to find users first. Promotion is not that important. I just need to build the stuff, build the workflow, and use that to find a VC, get the money. Then I'll use that pile of money to do promotion afterwards.",
    "Honestly, I was trapped in this exact idea last year. But I figured out it's fucking wrong. Because this era has already passed.",
    "You could do this two years ago. You can't do it now.",
    "Why? Because two years ago everybody was caring about the concept. AI was pretty new. So you'd say, \"Okay, we'll do an AI browser. We'll do AI plus fucking medicine, AI plus fucking health.\" AI plus this, AI plus that — you'd quickly raise a seed round. Then the seed-stage guy would tell you how to wrap this fucking idea to help you raise a Series A, so he could exit and make money.",
    "That was the old logic. Right now this logic has been turned upside down.",
    "Investors right now are very grounded. If you don't have ARR, no traction, they won't give you any fucking money.",
    "What you need to do now — if you're going toC, it has to be something genuinely useful. Otherwise, you might as well come back to toB.",
    "By the way, I really like the FDE role. In China it's called AIBP, in the US it's called FDE. I'm doing FDE in Shenzhen right now. I'll talk about this with everyone in the next post.",
    "Now back to normal people. I've talked a lot in previous essays about how you should just build an MVP and throw it on social media to test if anyone is interested. If you get a user, keep going. Don't build a fucking heavy code shit on day one.",
    "For normal people — code is pretty cheap right now. You can just vibe-code something. Don't go build some workflow or some complicated system on day one.",
    "First, it might not be what people want.",
    "Second, it's gonna make you start really fucking slow. You'll spend a lot of time thinking about how the workflow should be built. You might even be afraid of building something that big.",
    "For normal people, the most important thing is how fast you can start. Can you ship it this afternoon? Can you ship it before you go to sleep tonight? That's what determines how fast your product can land in front of users, and how fast it can catch their attention.",
  ],
};

export default article;
