import type { Article } from "./types";

const article: Article = {
  slug: "baseball-and-the-blame-game",
  titleZh: "棒球与职场甩锅",
  titleEn: "Baseball and the Blame Game",
  date: "2026-05-14",
  dateDisplay: "May 14",
  zh: [
    "我从去年开始喜欢看棒球，意识到棒球和职场其实是一回事。一样的规则、玩法，没人在看。",
    "---",
    "球场上九个人对你一个。轮到你打球的时候，你一个人面对所有人。职场也是——你以为有同事，其实没有。",
    "只有一种情况他们会真正关心你：他已经站上了某个位置，需要你别砸，需要你把他往前推。利益捆在一起的那一刻，他才在乎。剩下的时候，没人替你挡球。",
    "---",
    "每一次投球，是一次甩锅。",
    "锅飞过来，你不知道它是不是冲着你来的。没飞进你的区域，那是坏球——你不动，扔锅的人自己心虚。但你只要挥棒，这口锅就是你的。",
    "所以最重要的是看清楚有没有飞向你的区域。新人最容易犯的错，就是慌着挥。",
    "---",
    "飞向你了，你必须挥。挥不是为了把球打回去，是把锅甩出去。",
    "但不能甩到别人手里——那叫接杀，所有人都看见是你甩的。",
    "要嘛打出场外，全垒打，锅找都找不着。要嘛打到没人接得住的地方，自己冲上去安全上垒。",
    "安全上垒，就是抱住了领导的大腿。锅还在场上，但你站稳了。",
    "---",
    "但是站稳不等于赢。",
    "人会一直来找你茬。三振出局，这一轮就完了。",
    "三振出局是怎么发生的？你的同事都知道你会甩锅。他们已经在场上每一个位置都站好了——你想往哪甩，他们就在哪等着。你挥棒的方向、力度，他们早就预判过。",
    "真正能打出场外的全垒打，很少。大多数球，都落进他们的射程里，伸手就接住。",
    "---",
    "棒球的难，不在挥，在判断什么时候不挥。",
    "但还有一个更难的判断——你今天到底是在场上，还是在看台上。",
    "这不是工种的区别，是心态的区别。同一家公司里，有人在场上为这一棒拼命，有人在看台上嗑着瓜子把整场看完。",
    "---",
    "但说实话，这两种都不对。",
    "棒球就是棒球。职场不应该是棒球。",
    "球场上九个人玩这场没人看的硬仗，那是他们的本职工作。职场不该是。职场该是一个生产价值的地方——你交付的东西要么跑要么不跑，要么省了人要么没省，要么客户买单要么没买单。这种地方没有锅可甩，因为根本没有锅。",
    "未来几年球场上会多一个人。准确说，是一个 AI 球员。带他上场的人，现在流行叫 FDE（前线部署工程师）。",
    "这个球员同时会投会接、会跑会甩。你的好球带他知道，你想把锅甩到哪他也知道。他可以同时站在场上的九个位置——你打得再准他也伸手就接，全垒打也接得下来。",
    "具体到办公室里，他就是那个每天三个人扯一星期的对接，现在十分钟自己跑完了。",
    "看到这儿你可能想：这不就是来取代我的工作的吗？",
    "对，部分是。但更准确地说——他不是来取代你。他是来取代这场球本身的。这场没人看的比赛，他一个人就能玩。剩下的问题只有一个：你想继续上场挥棒，还是不打这场球。",
    "你可能还会想：就算我不打了，省下来的时间教练也不会让我休息。",
    "对，他不会——如果你还在他的球队里。",
    "换个角度想——AI 球员什么都会做，但他不知道该做哪件。哪个流程最烂、哪个 Excel 大家最恨、哪个对接最折磨人——这些事不在文档里，也不在系统数据里。",
    "它们在茶水间的抱怨里，在群里 5 点 47 分发出来又秒删的那条吐槽里，在同事跟你抽烟时说的「你别跟领导说啊」后面那半句话里。",
    "人只跟人说这种话。这是 AI 拿不走的。",
    "你打了这么多年球。所以你知道。",
    "把这些「只有人才会告诉人」的事，带到另一家公司，再带上 AI 球员——你就是 FDE。",
    "自己接活、做产品、靠手艺单干，也都行。这些人都不在这个球场里。",
    "当然，这些路不一定每条都走得通。也没关系——这场球不是一天散的，你也不必一天就走。看清楚 AI 能干什么、还干不了什么，已经够了。",
    "去哪不要紧。不打就行。",
    "不打的人，累完回家还能去看一场真的。一杯啤酒，一把瓜子，一群朋友。",
  ],
  en: [
    "I got into baseball last year and realized: baseball and the office are basically the same thing. Same rules, same playbook, no one really watching.",
    "---",
    "Nine of them against one of you. When it's your turn, you're alone against all of them. The office is no different — you think you have teammates, but you don't.",
    "There's exactly one situation where a coworker actually cares about you: they've already taken a base, they need you to not strike out, they need you to move them forward. The moment your interests line up, they care. The rest of the time, nobody is catching the ball for you.",
    "---",
    "Every pitch is someone trying to pin something on you.",
    "The ball flies in, you don't know if it's meant for you. If it isn't in your zone, that's a ball — don't move. The blame doesn't land, and the person who threw it just exposed themselves. The second you swing, it's yours.",
    "The most important skill is reading whether it's coming into your zone. The mistake juniors make is panicking and swinging.",
    "---",
    "If it's in your zone, you have to swing. The point isn't to hit the ball back — it's to throw the blame somewhere else.",
    "But you can't put it directly into someone's hands. That's a caught fly ball. Everyone saw it. Everyone knows it came from you.",
    "Either knock it out of the park — home run — and the blame vanishes. Or hit it where nobody can catch it cleanly, then run like hell and get yourself on base.",
    "Getting on base is grabbing onto a boss's leg. The blame is still floating around, but you're standing on something solid.",
    "---",
    "Standing on base isn't winning, though.",
    "People keep coming for you. Three strikes and you're out. The round is over.",
    "How does the strikeout happen so easily? Because your coworkers all know you're going to throw the blame somewhere. They've already taken up every position on the field — wherever you want to throw it, they're already standing there. The angle and force of your swing? They've predicted it.",
    "Real home runs — the ones that actually clear the park — are rare. Most balls land inside their range. They reach out and catch.",
    "---",
    "The hard part of baseball isn't swinging. It's knowing when not to.",
    "But there's a harder call than that — whether you're on the field today, or up in the stands.",
    "It's not a difference in job. It's a difference in posture. In the same company, some people are out there grinding for every at-bat, while others sit in the stands with a beer and watch the whole thing play out.",
    "---",
    "But honestly, neither of those is right.",
    "Baseball is baseball. The office shouldn't be baseball.",
    "Nine guys on the field grinding through a game nobody's watching — that's their job. The office isn't supposed to be like that. The office is supposed to be a place where you produce value. What you ship runs or it doesn't. It saved a headcount or it didn't. A customer paid for it or they didn't. There's no blame to pass, because there's nothing to blame anyone for.",
    "Over the next few years, there's going to be a new player on the field. More specifically: an AI player. The person who brings him onto the field is what's now being called an FDE — a Forward Deployed Engineer.",
    "This player can pitch, catch, run, and deflect — all at once. He knows your strike zone. He knows where you want to throw the blame. He can stand at all nine positions at the same time. Hit it clean and he reaches out and catches. Even a home run — he gets to the wall first.",
    "In the office, he's the handoff that used to take three people a week — now it takes ten minutes.",
    "Reading this, you might be thinking: isn't this exactly the work that's going to replace mine?",
    "Yes. Partly. But more precisely — he's not here to replace you. He's here to replace the game itself. This game nobody was watching, he can play it alone. The only real question left is whether you want to keep stepping up to bat, or stop playing this game.",
    "You might still be thinking: even if I stop, the coach isn't going to let me have any of that saved time off.",
    "He won't — if you're still on his team.",
    "Here's another angle. The AI player can do everything, but he doesn't know what to do. Which process is broken. Which Excel everyone hates. Which handoff is the worst — none of that lives in the documentation. None of it lives in the data.",
    "It lives in the break room complaints. In the 5:47 PM message someone fires into the group chat and deletes a minute later. In the 'don't tell the boss' that a coworker drops over a cigarette right before telling you anyway.",
    "People only say this kind of thing to other people. That's the part AI can't take.",
    "You've been on this field for years. So you know.",
    "Take that — the things only humans tell other humans — into another company, bring the AI player with you, and you're the FDE.",
    "Freelancing, building your own product, working solo with a craft — these count too. None of them put you on this field.",
    "Of course, not every one of those paths will work for everyone. That's OK — this game isn't going to wrap up in a day, and you don't have to leave in one either. Knowing what AI can do, and what it still can't, is enough.",
    "Where you go doesn't matter. Just stop playing.",
    "People who stop playing this game come home tired and can still go watch a real one. A beer, some peanuts, friends.",
  ],
};

export default article;
