import type { Article } from "./types";

const article: Article = {
  slug: "data-security-is-not-a-blocker",
  titleZh: "数据安全不是你停止项目推进的原因",
  titleEn: "Data Security Is Not a Reason to Stop a Project",
  date: "2026-08-10",
  dateDisplay: "Aug 10",
  descriptionZh:
    "数据安全不是企业 AI 项目的抽象否决权。先进入现场、确认任务，再把存储与算力的境外、境内和本地边界做成有价格的工程选项。",
  description:
    "Data security is not an abstract veto on enterprise AI. Enter the site, define the task, then turn storage and compute boundaries into priced engineering choices.",
  keywords: [
    "FDE",
    "AI Native Company",
    "ANC",
    "data security",
    "enterprise AI",
    "data residency",
    "local deployment",
    "permissions",
    "HA7CH",
  ],
  zh: [
  "企业 AI 项目谈数据安全，先不要讨论一百个抽象风险。让客户确认两件事就够了：数据存在哪里，模型在哪里算。",
  "第一，数据存储能放在哪里：",
  "- 允许境外：使用境外云或境外 VPS；",
  "- 仅限境内：使用境内云或境内 VPS；",
  "- 仅限企业本地：使用企业服务器或内网存储。",
  "第二，模型算力能放在哪里：",
  "- 允许境外：调用境外模型 API 或境外 GPU；",
  "- 仅限境内：调用境内模型 API 或境内 GPU；",
  "- 仅限企业本地：使用本地模型和本地 GPU。",
  "严格程度从左到右逐步提高。客户允许境外，就使用境外存储和算力；不能出境，就切换到境内；不能离开企业，就全部部署在本地。要多严格，就上多严格的方案，同时把价格、效果、周期和维护责任讲清楚。",
  "这里需要特别注意：存储在本地，不等于数据没有离开本地。只要调用了境内或境外的云端模型，输入数据在推理过程中就会被发送到对应算力。因此真正的安全方案必须同时确认“数据存在哪里”和“模型在哪里算”，最终边界由两者中更开放的一项决定。",
  "VPS 也不是一个独立的安全等级，它只是承载存储和算力的服务器。境外 VPS 属于境外，境内 VPS 属于境内；只有放在企业控制范围内的服务器或算力，才属于企业本地。",
  "很多企业 AI 项目还没开始，第一句话就是：数据安全怎么办？",
  "客户现场还没去，业务流程还没看，数据长什么样不知道，谁在用不知道，究竟要解决什么问题也不知道，但大家已经开始讨论公有云、私有化部署、数据出境、模型泄密和权限隔离。",
  "听上去很专业，实际上这个问题在此时根本没有答案。",
  "因为数据安全从来不是一个脱离业务、可以单独讨论的问题。没有具体的数据，没有具体的流向，没有具体的使用者，也没有具体的风险对象，所谓“安全”只是一个无限大的抽象词。任何人都可以不断补充新的担忧，直到项目彻底无法推进。",
  "所以我的观点很简单：",
  "数据安全不是你停止项目推进的原因。尤其当你还没有走到客户现场时，拿数据安全追问项目能不能做，很多时候不是在解决问题，而是在给自己找一个不做的理由。",
  "安全不是一道判断题",
  "很多人把数据安全理解成一道判断题：这个项目安不安全？",
  "但真实世界里根本不存在一个脱离条件的“安全”答案。同一份销售日报，放在市场部、财务部和一家上市公司的并购项目里，安全要求完全不同；同一个模型，处理公开招投标文件和处理未披露的患者信息，风险也完全不同。",
  "真正有意义的不是问“安不安全”，而是把它拆成一组具体边界：",
  "- 数据能不能出境；",
  "- 数据能不能上公有云；",
  "- 数据能不能离开企业内网；",
  "- 原始数据、脱敏数据和模型输出分别能存在哪里；",
  "- 算力可以使用境外云、境内云、企业专有云，还是只能使用本地机器；",
  "- 第三方模型是否保存请求日志，是否会将数据用于训练；",
  "- 哪些人可以访问，什么操作需要审批，是否必须保留审计记录；",
  "- 数据需要保存多久，什么时候删除，备份如何处理。",
  "这些问题一旦回答清楚，安全就不再是一个哲学问题，而是一道工程选型题。",
  "可以使用境外模型，就接能力最强、迭代最快的模型；不能出境，就选择境内模型和境内算力；不能使用公有云，就放进企业 VPC 或专有云；数据不能离开内网，就把存储、推理和日志全部放在本地；要求物理隔离，就上本地算力、私有化模型和离线更新。",
  "客户要求多严格，就提供多严格的方案。与此同时，把对应的成本、效果、交付周期和维护代价全部讲清楚。",
  "安全等级越高，通常意味着采购成本更高、部署周期更长、维护负担更重、可调用的模型更少，甚至模型效果也会下降。这不是技术团队应该偷偷替客户做的决定，而是应该摆在桌面上，让客户基于业务价值和风险承担能力做选择。",
  "数据安全不是免费的正确。它是一组有价格的约束。",
  "不是所有数据都要坐运钞车",
  "数据安全更像运输安全。",
  "如果你连要运什么、从哪里运到哪里、由谁接收都不知道，就先问“这批货怎么保证绝对安全”，这个问题同样没有答案。",
  "运普通文件，可以使用快递；运生鲜，需要冷链车；运贵重物品，需要保险、定位和专门押运；运危险品，需要有资质的车辆、司机和固定路线；如果货物要跨境，还要再处理海关、目的地法规和跨境责任。",
  "每一种货物都有相对成熟的运输方案。真正要做的，是先判断货物属于什么等级，再选择对应的包装、车辆、路线、仓库和签收方式。",
  "数据也是一样。",
  "公开资料、内部经营数据、客户隐私、医疗数据和国家秘密，不可能使用同一种保护方式。数据在境内流转还是跨境流转，存放在第三方云仓还是企业自有仓库，由普通员工使用还是只有特定人员可以签收，都可以在确认等级以后匹配对应方案。",
  "最愚蠢的做法，是因为世界上存在贵重物品，就要求所有货物都用运钞车运输。一份公开产品手册也要本地大模型、物理隔离、专线网络和完整审计，最后运输成本比货物本身还贵，项目当然无法成立。",
  "反过来，把贵重物品当普通快递寄走，同样是失职。",
  "FDE 要做的不是坚持所有数据都应该上云，也不是坚持所有数据都必须私有化，而是完成数据分级，然后给每一级数据安排合适的“运输工具”。客户要更高级别的车辆、更严格的路线和更完整的押运，就把价格、时间和能力损失讲清楚。",
  "所以安全不是“这批货还要不要运”，而是“这批货应该怎么运”。只有货物来源不明、运输路径违法，或者没有人愿意对交接负责时，运输才应该真正停下来。",
  "没有客户现场，就没有真正的数据安全问题",
  "在进入客户现场之前，你甚至不知道需要保护的是什么。",
  "有人说工厂的数据不能上云，到了现场才发现第一期要处理的只是已经脱敏的设备说明书；有人说财务资料绝对不能交给模型，最后发现真正需要验证的是一批公开政策文件的分类；有人要求一开始就建设完整的本地大模型平台，但业务部门连第一个高频任务是什么都没有确定。",
  "这时如果团队直接进入私有化部署、权限系统和安全评审，往往会得到一个非常安全、非常昂贵，也完全没人使用的系统。",
  "正确顺序应该是先进入现场，找到任务，再确定数据。",
  "先观察谁在做什么工作，原来的流程花多长时间，输入和输出分别是什么，哪些节点需要判断，哪些步骤可以由 AI 接管。确定了具体任务以后，才知道需要哪些数据、数据从哪里来、经过什么处理、最后流向哪里。",
  "只有到了这一步，数据安全才有了讨论对象。",
  "在早期验证阶段，也完全没有必要为了“安全”停下来。可以先使用公开数据、虚构数据、样例数据或者脱敏后的历史数据，把工作流和技术可行性跑通；如果数据不能上云，就先在客户电脑或本地环境中验证；如果连脱敏数据都不能带走，就在现场完成测试，不复制、不留存。",
  "一个真正想推进项目的 FDE，会把安全约束变成验证条件。一个不想推进项目的人，才会把安全变成一句没有边界的否定。",
  "真正需要设计的是业务架构",
  "相比数据安全，企业 AI 项目里真正需要大量设计的，是 AI 如何进入组织。",
  "模型应该接在哪个流程里，谁负责给它上下文，谁审核它的输出，它如何调用原有系统，出错以后如何回退，人的责任如何变化，新的工作如何被沉淀成 Skill，多个 Agent 之间如何分工，这些才是每一家企业都不同、无法照搬的部分。",
  "同样是合同审核，有的企业需要 AI 给法务提供风险提示，有的企业希望销售先完成自检，有的企业要把结果同步给财务和交付，有的企业还需要把高风险条款送到管理层审批。模型可能相同，业务架构却完全不同。",
  "安全应该作为约束进入架构，但不应该代替架构本身。",
  "我们真正要设计的是数据如何服务任务、Agent 如何参与流程、人如何保留控制权，以及整个系统如何在企业里持续生长。安全负责规定哪些路径可以走，架构负责决定走这条路径以后，企业究竟能得到什么。",
  "如果一个团队整天讨论数据放在哪里，却说不清楚 AI 要替谁完成什么工作，那么它设计的不是 AI Native Company，只是一套昂贵的基础设施。",
  "权限也不是每次从零发明",
  "权限问题同样经常被无限放大。",
  "谁能看哪些数据，谁能调用哪些工具，谁能批准哪些动作，什么行为必须记录，行业里早已有成熟的基本方法：角色权限、属性权限、最小权限、分级审批、操作审计、数据隔离、临时授权。",
  "真正需要梳理的是企业里的责任关系，而不是重新发明一套权限理论。",
  "员工只能读取自己负责的客户，区域负责人可以读取本区域数据，总经理可以查看汇总结果；普通 Agent 可以起草合同，但不能直接发送；涉及付款、删库、对外发布的动作必须由人确认；跨部门取数需要留下审批和调用记录。",
  "这些都可以被做成标准组件。",
  "权限当然要做，但它应该被产品化、模板化、配置化。每个项目真正需要完成的是把客户的组织结构和责任边界映射进去，而不是每次从“权限是什么”重新开始讨论。",
  "把安全做成一张明码标价的菜单",
  "我更倾向于把企业 AI 的安全方案直接做成几个部署档位。",
  "第一档，允许使用公有云和第三方模型。企业采用成熟 SaaS、模型 API 和云存储，关闭数据训练，控制日志留存。这种方案启动最快、成本最低，也最适合验证普通业务任务。",
  "第二档，要求数据留在境内或指定云环境。模型、存储和日志均使用境内服务，通过企业账号、加密和访问控制管理。这会增加一些集成与治理成本，但仍然可以保持较快的迭代速度。",
  "第三档，要求数据不出企业控制域。系统部署在企业 VPC、专有云或指定数据中心，通过私有网关调用模型，敏感数据不经过开放网络。这时企业需要承担更多基础设施和运维责任。",
  "第四档，要求完全本地化甚至物理隔离。模型推理、向量库、业务数据、日志与审计全部部署在本地，更新也通过受控流程完成。这是成本最高、交付最慢、模型选择最少的一档，但确实适合少数高度敏感的场景。",
  "这四档不是安全与不安全的区别，而是不同风险容忍度、不同预算和不同业务价值下的选择。",
  "FDE 不需要替客户信仰某一种方案。FDE 应该告诉客户：你的要求对应什么架构，需要多少钱，要牺牲什么，多久可以上线。如果业务收益覆盖不了这套安全方案的成本，那么应该重新选择场景，而不是把整个 AI 改造无限期暂停。",
  "安全什么时候真的会让项目停下来",
  "数据安全不是停止推进的默认理由，但确实存在必须暂停的情况。",
  "第一，客户无法确认数据的所有权、授权范围和责任人。没人知道这份数据能不能用，也没人愿意承担授权责任。这时缺少的不是技术方案，而是项目成立的基本前提。",
  "第二，业务要求与合规边界发生直接冲突。例如任务必须把敏感数据发送到某个外部服务，但客户的明确规定不允许任何形式的外发，而且又没有可接受的本地替代方案。这时应该更换技术路径或更换场景。",
  "第三，客户要求最高等级的安全，却不愿承担相应的成本、时间和效果损失。既要最强模型、最快上线、最低价格，又要求完全离线和绝对安全，这不是安全问题，而是需求无法同时成立。",
  "除了这些明确阻断条件，大部分所谓“安全问题”都不应该让项目停止，只应该让方案发生变化。",
  "不能出境，就不出境；不能上云，就本地部署；不能带走原始数据，就现场处理；不能开放全部权限，就从最小权限开始；暂时无法完成正式授权，就先用样例数据验证流程。",
  "约束是用来决定下一步怎么走的，不是用来证明哪一步都不能走的。",
  "FDE 应该先做什么",
  "一个 FDE 到达客户现场以后，应该先完成四件事。",
  "第一，找到真实任务。明确是谁、在什么场景下、用什么输入完成什么输出，以及当前成本和错误率。",
  "第二，画出最小数据流。只记录这个任务真正需要的数据从哪里来、经过哪里、由谁处理、最终去哪里，不要一上来给整个集团建设数据中台。",
  "第三，确认安全边界。让业务负责人、IT 和必要的合规负责人对数据、存储、算力、模型、人员访问和日志留存逐项作出明确选择。",
  "第四，给出分档方案。每一种安全等级分别对应部署方式、周期、预算、模型能力和维护责任，由客户确认取舍。",
  "完成这四步以后，项目就应该继续推进。安全要求进入技术方案、合同边界、验收标准和报价，而不是继续停留在会议里反复讨论。",
  "未来 ANC 也应该把这套逻辑变成标准能力。企业在部署之初选择自己的安全 Profile：数据是否出境、是否上云、算力位置、模型供应商、日志策略、权限模型和审计等级。脚手架根据这些配置生成对应的 Gateway、存储、模型路由和权限方案。",
  "安全不再是一场从零开始的辩论，而是 ANC 的一组基础配置。",
  "不要用安全掩盖对业务的无知",
  "很多项目真正的问题，从来不是数据安全。",
  "真正的问题是团队不知道该改造哪个流程，不知道客户为什么愿意付钱，不知道模型输出如何进入实际工作，也不知道系统上线以后由谁使用、谁维护、谁为结果负责。",
  "这些问题很难，所以人们更愿意讨论数据安全。因为安全听起来重要、正确，而且永远可以提出新的风险。只要把安全标准抬得足够高，任何项目都可以被证明不应该开始。",
  "但企业不会因为我们证明了风险存在，就自动完成 AI 转型。",
  "FDE 的工作不是站在客户现场外面想象所有可能发生的问题，而是走进去，看清楚业务，在真实约束下找到一条可以启动、可以验证、可以扩大的路径。",
  "所以，下次有人在项目还没有进入现场时就问“数据安全怎么办”，我们不应该继续陪他讨论一个没有对象的抽象问题。",
  "先问清楚：是什么数据，谁要使用，要完成什么任务，数据准备经过哪里，客户愿意承担什么成本。",
  "回答完这些，方案自然会出现。",
  "数据安全当然需要考虑。但它应该是一张约束清单、一棵决策树和一份明码标价的部署菜单，而不是所有企业 AI 项目开始之前的一堵墙。",
  "数据安全不是你停止项目推进的原因。没有走到客户现场，就先用“安全”否定项目，很多时候不是专业，而是在用一个正确的大词掩盖自己还没有开始理解业务。"
],
  en: [
  "When an enterprise AI project discusses data security, do not begin with a hundred abstract risks. Ask the client to confirm two things: where the data may be stored, and where the model may run.",
  "First, where may the data be stored?",
  "- Overseas allowed: use overseas cloud storage or an overseas VPS.",
  "- Domestic only: use cloud storage or a VPS located in China.",
  "- Enterprise-local only: use company-controlled servers or internal storage.",
  "Second, where may model inference run?",
  "- Overseas allowed: call overseas model APIs or overseas GPUs.",
  "- Domestic only: call model APIs or GPUs located in China.",
  "- Enterprise-local only: run a local model on local GPUs.",
  "Strictness rises as the allowed boundary moves from overseas, to domestic, to enterprise-local. If overseas services are allowed, use overseas storage and compute. If data cannot leave China, switch both to domestic services. If data cannot leave the enterprise, deploy everything locally. Give the client the level it asks for, and make the corresponding price, performance, timeline, and maintenance responsibility explicit.",
  "One detail matters: storing data locally does not mean the data stays local. If the system calls a domestic or overseas cloud model, the input still travels to the place where inference runs. A real security design must therefore confirm both storage location and compute location. The effective boundary is determined by whichever of the two is more open.",
  "A VPS is not a security level. It is simply a server that carries storage and compute. An overseas VPS is overseas. A domestic VPS is domestic. Only infrastructure inside the enterprise's control belongs to the enterprise-local tier.",
  "Many enterprise AI projects have barely begun when someone asks the first question: what about data security?",
  "Nobody has visited the client site. Nobody has seen the workflow, the actual data, the users, or even the problem the project is supposed to solve. Yet the discussion has already jumped to public cloud, private deployment, cross-border transfers, model leakage, and permission isolation.",
  "It sounds professional. At this point, however, the question has no answer.",
  "Data security is never a standalone topic detached from the work. Without specific data, a specific flow, specific users, and a specific threat, “security” becomes an infinitely expandable abstraction. Anyone can keep adding new concerns until the project becomes impossible to start.",
  "My position is simple:",
  "Data security is not a reason to stop a project. Especially before you have entered the client site, asking whether the project can proceed because of “data security” often solves nothing. It merely gives the team a respectable reason not to act.",
  "Security Is Not a Yes-or-No Question",
  "People often treat data security as a binary judgment: is this project secure or not?",
  "There is no meaningful answer without conditions. The same sales report carries different requirements inside a marketing team, a finance team, or an undisclosed acquisition. The same model presents completely different risks when processing public tender documents versus private patient information.",
  "The useful move is not to ask whether the project is “secure.” It is to define concrete boundaries:",
  "- May the data cross national borders?",
  "- May the data enter a public cloud?",
  "- May the data leave the enterprise network?",
  "- Where may raw data, redacted data, and model outputs be stored?",
  "- May compute run on overseas cloud, domestic cloud, a dedicated enterprise cloud, or only local machines?",
  "- Does the model provider retain request logs or use the data for training?",
  "- Who may access the system, which actions require approval, and which actions must be audited?",
  "- How long is data retained, when is it deleted, and how are backups handled?",
  "Once these questions are answered, security stops being a philosophical debate and becomes an engineering selection problem.",
  "If overseas models are allowed, connect the strongest and fastest-moving models. If data cannot cross borders, use domestic models and domestic compute. If public cloud is prohibited, deploy inside a VPC or dedicated cloud. If data cannot leave the enterprise network, keep storage, inference, and logs local. If physical isolation is required, use local compute, a private model, and controlled offline updates.",
  "The client should receive the level of protection it requires. At the same time, the delivery team should explain the cost, capability, delivery time, and maintenance burden of that choice.",
  "Stricter security normally means higher procurement cost, longer deployment, heavier operations, fewer model choices, and sometimes weaker model performance. The technology team should not silently make that trade-off for the client. Put it on the table and let the client choose according to business value and risk tolerance.",
  "Security is not free correctness. It is a set of constraints with a price.",
  "Not All Data Needs an Armored Truck",
  "Data security is more like transportation security.",
  "If you do not know what is being shipped, where it starts, where it ends, or who receives it, asking how to guarantee absolute safety has no answer.",
  "Ordinary documents can travel by courier. Fresh food needs a refrigerated truck. Valuables need insurance, tracking, and professional escort. Hazardous materials require licensed vehicles, qualified drivers, and fixed routes. Cross-border shipments add customs, destination-country rules, and cross-border liability.",
  "Each class of cargo already has relatively mature transportation methods. The job is to classify the cargo first, then choose the right packaging, vehicle, route, warehouse, and handoff process.",
  "Data works the same way.",
  "Public material, internal operating data, customer privacy, medical records, and state secrets cannot use the same protection. Once the class is known, the team can decide whether data travels domestically or internationally, whether it sits in a third-party warehouse or an enterprise-controlled one, and whether ordinary staff or only specific people may receive it.",
  "The foolish approach is to notice that valuables exist and therefore require an armored truck for every package. If a public product manual requires a local foundation model, physical isolation, dedicated networking, and complete audit infrastructure, transportation becomes more expensive than the cargo. The project naturally collapses.",
  "Treating valuables as ordinary parcels is equally irresponsible.",
  "An FDE should not insist that all data belongs in the cloud, nor that all data must be privately deployed. The job is to classify data and assign the right “vehicle” to each class. If the client requests a more secure vehicle, a stricter route, and a fuller escort, explain the additional price, time, and capability loss.",
  "Security is therefore not the question “should this cargo be shipped at all?” It is the question “how should this cargo be shipped?” Transportation should truly stop only when ownership is unclear, the route is illegal, or nobody will take responsibility for the handoff.",
  "Without the Client Site, There Is No Real Security Question",
  "Before entering the client site, you do not even know what needs protection.",
  "A factory may say its data cannot go to the cloud, only for the team to discover that the first task uses already-redacted equipment manuals. A finance team may say no material can touch a model, while the first validation only classifies public policy documents. A company may demand a complete local-model platform even though the business team has not identified one high-frequency task.",
  "If the team immediately starts private deployment, permission systems, and security reviews, it may produce a system that is extremely safe, extremely expensive, and completely unused.",
  "The right order is to enter the site, find the task, and then identify the data.",
  "Observe who performs the work, how long the existing process takes, what goes in, what comes out, where judgment happens, and which steps AI might take over. Only after defining a task can the team know which data is needed, where it originates, how it is processed, and where it ends.",
  "Only then does data security have an object.",
  "Early validation does not need to stop because of security. Use public data, synthetic data, samples, or redacted historical data to prove the workflow. If data cannot enter the cloud, validate on a client machine or local environment. If even redacted data cannot leave, test on site without copying or retaining it.",
  "An FDE who wants to move the project forward converts security into validation conditions. Someone who does not want to move forward turns security into an unbounded rejection.",
  "The Business Architecture Is What Requires Design",
  "Compared with security, the part of an enterprise AI project that truly requires design is how AI enters the organization.",
  "Where does the model join the workflow? Who supplies its Context? Who reviews its outputs? How does it call existing systems? What happens when it fails? How do human responsibilities change? How does new work become a Skill? How do multiple Agents divide responsibility? These questions differ from company to company and cannot be copied wholesale.",
  "Consider contract review. One company may want AI to highlight risks for legal counsel. Another may ask salespeople to run a self-check first. A third may send the result to finance and delivery. A fourth may escalate high-risk clauses to management. The model can be identical while the business architecture is completely different.",
  "Security should constrain the architecture, but it should not replace the architecture.",
  "The real design problem is how data serves a task, how Agents participate in a workflow, how people retain control, and how the system continues to grow inside the enterprise. Security defines which paths are allowed. Architecture determines what the enterprise gains after taking one of those paths.",
  "If a team spends all day discussing where data sits but cannot say whose work AI will change, it is not designing an AI Native Company. It is assembling expensive infrastructure.",
  "Permissions Do Not Need to Be Reinvented Every Time",
  "Permission questions are also routinely inflated.",
  "Who may see which data, who may call which tools, who may approve which actions, and which behavior must be recorded already have mature patterns: role-based access, attribute-based access, least privilege, tiered approvals, audit logs, data isolation, and temporary grants.",
  "The work is to map responsibility inside the enterprise, not to invent a new theory of permissions.",
  "An employee may read only the customers they serve. A regional manager may read regional data. A general manager may see summaries. An ordinary Agent may draft a contract but may not send it. Payments, deletion, and external publication require human confirmation. Cross-department access leaves an approval and invocation record.",
  "These patterns can become standard components.",
  "Permissions matter, but they should be productized, templated, and configured. Each project maps the client's organization and responsibility boundaries into those components instead of restarting the discussion from “what are permissions?”",
  "Turn Security Into a Menu With Prices",
  "Enterprise AI security can be offered as several deployment tiers.",
  "Tier one permits public cloud and third-party models. The company uses mature SaaS, model APIs, and cloud storage, disables provider training where available, and controls log retention. It starts fastest, costs least, and fits ordinary validation tasks.",
  "Tier two requires data to remain in China or in a designated cloud. Models, storage, and logs use domestic services with enterprise accounts, encryption, and access control. Integration and governance cost more, but iteration can remain relatively fast.",
  "Tier three requires data to stay inside an enterprise-controlled domain. The system runs in a VPC, dedicated cloud, or designated data center, with a private model gateway and no sensitive data passing through an open public service. Infrastructure and operational responsibility rise.",
  "Tier four requires full localization or physical isolation. Inference, vector storage, business data, logs, and audits all run locally, and updates follow a controlled process. This tier costs the most, takes the longest, and offers the fewest model choices, but it is appropriate for a small number of highly sensitive scenarios.",
  "These tiers are not “secure” versus “insecure.” They are choices made under different risk tolerances, budgets, and business values.",
  "An FDE does not need to believe in one deployment model. The FDE should tell the client which architecture its requirement implies, how much it costs, what capability it sacrifices, and how long it takes. If the business return cannot cover the security architecture, change the scenario instead of suspending the entire AI transformation indefinitely.",
  "When Security Really Should Stop a Project",
  "Data security is not the default reason to stop, but there are real blocking conditions.",
  "First, the client cannot confirm data ownership, authorization, or a responsible owner. Nobody knows whether the data may be used, and nobody will authorize it. The missing piece is not a technical solution. It is a basic condition for the project to exist.",
  "Second, the business requirement directly conflicts with a binding boundary. The task may require sending sensitive data to an external service while the client explicitly forbids any external transfer and no acceptable local alternative exists. Change the technical route or choose another scenario.",
  "Third, the client demands the highest security level but refuses the corresponding cost, time, and performance trade-offs. The strongest model, fastest launch, lowest price, complete offline operation, and absolute security cannot all be true at once. That is not a security problem. The requirements are mutually incompatible.",
  "Outside these explicit blockers, most security questions should change the design rather than stop the project.",
  "If data cannot cross borders, keep it domestic. If it cannot enter a cloud, deploy locally. If raw data cannot leave, process it on site. If broad permissions are unacceptable, begin with least privilege. If formal authorization is not ready, validate the workflow with sample data.",
  "Constraints determine the next move. They do not prove that no move is possible.",
  "What an FDE Should Do First",
  "After entering the client site, an FDE should complete four things.",
  "First, find the real task. Identify the person, situation, input, output, current cost, and current error rate.",
  "Second, draw the minimum data flow. Record only where the data needed for this task originates, where it travels, who handles it, and where it ends. Do not begin by building a data platform for the entire group.",
  "Third, confirm the security boundary. Ask the business owner, IT, and where necessary compliance to choose explicit rules for data, storage, compute, models, human access, and log retention.",
  "Fourth, present tiered options. Each security level should map to a deployment method, timeline, budget, model capability, and maintenance owner. Let the client confirm the trade-off.",
  "Once these four steps are complete, the project should continue. Security becomes part of the technical design, contract boundary, acceptance criteria, and price instead of remaining an endless meeting topic.",
  "ANC should eventually make this a standard capability. At deployment, the enterprise chooses a security Profile: whether data may cross borders, whether it may enter cloud, where compute runs, which model providers are allowed, how logs are retained, which permission model applies, and what audit level is required. The scaffold then generates the matching Gateway, storage, model routing, and permission design.",
  "Security stops being a debate rebuilt from zero. It becomes a set of baseline ANC configurations.",
  "Do Not Use Security to Hide Ignorance of the Business",
  "The real problem in many projects is not data security.",
  "The team does not know which process to transform, why the client would pay, how model output enters real work, who uses the system after launch, who maintains it, or who owns the result.",
  "Those questions are difficult, so people prefer to discuss security. Security sounds important and unquestionably correct, and there is always another risk to add. Raise the standard high enough and any project can be proven unworthy of starting.",
  "But proving that risk exists does not transform an enterprise.",
  "The FDE's job is not to stand outside the client site imagining every possible failure. The job is to enter, understand the work, and find a path that can start, be verified, and expand under real constraints.",
  "The next time someone asks “what about data security?” before the project has entered the site, do not keep debating an abstraction without an object.",
  "First ask: what data, used by whom, for which task, traveling through which path, under what acceptable cost?",
  "Once those answers exist, the design follows.",
  "Data security must be considered. But it should become a constraint checklist, a decision tree, and a deployment menu with prices—not a wall in front of every enterprise AI project.",
  "Data security is not a reason to stop a project. If someone rejects a project with the correct-sounding word “security” before entering the client site, that is often not professionalism. It is a way to hide the fact that they have not started understanding the business."
],
};

export default article;
