import type { Article } from "./types";

const article: Article = {
  slug: "fde-is-the-future",
  titleZh: "FDE 才是未来",
  titleEn: "FDE Is The Future",
  date: "2026-05-11",
  dateDisplay: "May 11",
  zh: [
    "很多人已经看到，在国外，OpenAI、Anthropic 这些公司已经不再是单纯卖模型、卖 API。他们开始派一批人到企业里面，直接坐在客户旁边，问他每天怎么工作，问他们系统怎么跑，问他们的行业黑话是什么，然后用 AI 把这些流程重新搭一遍、重构一遍，把 AI 完全地植入进去。这就是 FDE，Forward Deployed Engineer。",
    "如果放到中国，我觉得它有一个更好的名字：AI BP，AI Business Partner。",
    "他不是那种传统的咨询，他不给你 PPT，不给你方案。他更不是把一些什么傻逼的 SaaS 账号给你，而就是一个人带着电脑，直接到企业现场，帮老板和员工一条一条地把工作流拆出来，然后用 AI 做成能够真正跑起来的 solution。",
    "---",
    "其实我们经常活在一个错觉里面。我们以为所有人都已经在用 AI 了，以为所有人都会用 Claude Code、都会 vibe coding、都会让 AI 写代码、做表格、整理文档、跑自动化。",
    "但是你只要去深圳的传统行业转一圈，你就会发现完全不是这样。",
    "很多老板连豆包都没有用过。我前段时间给一个老板装了一个豆包，他都高兴得不行。对我们来说这可能是一个再普通不过的东西，但对他来说，直接就像打开了新世界的大门，高兴得要请我们喝茅台。所以在 AI 圈里非常稀疏平常的东西，在传统行业里依然是非常稀缺的技能。",
    "还有一次我跟一个老板谈话，给他介绍我写的产品。他说，你会用 AI 写代码？我说当然啦，废话，现在所有人都在用 AI 写代码。但是突然我也意识到一件事：在他身边，也许连一个会用 AI 写代码的人都没有。于是他立马就握着我的手说，你一定要过来帮我们降本增效。",
    "---",
    "未来两年，所有人都知道有大量工作会被 AI 替代。但是这些岗位到底是怎么被替代的？",
    "是那些连豆包都不会用的老板突然开始学习 vibe coding，然后自己把公司的工作流全部整理出来，自己搭 Agent、自己接 API、自己部署吗？不可能。",
    "真正发生的事情一定是这样：一个年轻人背着 MacBook Air 走进一家传统公司，他坐在办公室里，可能就坐在地上，一个一个地问员工：你每天第一件事干什么？Excel 发给谁？这个字段什么意思？行业术语代表了什么？为什么你每次都要复制粘贴？这些流程里哪一个最繁杂、哪个最容易出错、哪一个最难搞？",
    "然后他把这些东西记下来，用 AI 做成工具。可能是个内部系统，可能是一个 Chrome 插件，可能是一个小工具，可能是一个 Agent，可能是一个 I don't know what the fuck is this。",
    "但是结果是什么？结果就是 AI 不再是一个很酷的东西。老板会发现原来三个人做的事情，现在一个人就可以做。以前一天做不完的，现在 10 分钟就可以做完。以前需要老员工手把手带着才能上手做项目的，现在新员工直接用 AI 开始做。原来需要人一直去盯着、去催的东西，现在 AI 都可以主动去发消息。That's it。",
    "所以这就是 FDE 的本质。",
    "---",
    "我觉得对于普通人来说，这里有非常大的机会。因为传统行业缺的并不是一个更强的大模型。",
    "很多人创业都在跟模型对着干，每天都要担心：下一周 Claude Code 是不是又更新一个东西把我干掉了？但是你仔细想，我们做 FDE，就是模型越强我越强，模型越便宜我越牛逼。",
    "---",
    "当然 FDE 的要求也很高。你要愿意认识这些老板，你要愿意走到现场，你要听得懂他们的话，你要不嫌脏、不嫌乱、不嫌烦，每天从 Excel、微信截图、邮件、手写的单据开始，然后把这些东西全部变成 AI workflow。",
    "而且你要做得非常的快。你上午刚刚跟老板喝完茶，下午就必须要跑出一个 prototype。你今天刚刚理解了一个东西，周末就要开始狂干，然后把它写进系统的逻辑里。",
    "你可以不是这个行业出身，甚至你可以对这个行业一无所知。但是你必须要足够主动，能够钻进去，把 AI 变成生产力。这就是 FDE，这就是 AI BP。",
    "---",
    "未来两年，AI 落地的最后一公里，靠的就是这种人。背着电脑走进现场，让企业真的少花钱、少犯错、少用人。That's it。",
  ],
  en: [
    "A lot of people have already noticed something happening abroad. OpenAI, Anthropic, these companies aren't just selling models or APIs anymore. They started sending people into enterprises, sitting right next to the client, asking how they work each day, how their systems run, what their industry jargon means, and then using AI to rebuild those workflows from the ground up. That's FDE: Forward Deployed Engineer.",
    "Inside China, I think there's a better name for the role: AI BP, AI Business Partner.",
    "They're not traditional consultants. They don't hand you a PPT or a proposal. They sure as hell don't hand you some shitty SaaS account. It's one person with a laptop, on-site at the company, working through the workflow line by line with the boss and the employees, and then turning it into an AI-based solution that actually runs.",
    "---",
    "We live in a bubble most of the time. We assume everyone is already using AI. We assume everyone uses Claude Code, vibe codes, has AI write code, build spreadsheets, organize documents, run automations.",
    "Walk through traditional industries in Shenzhen for a day and you'll see it's nothing like that.",
    "A lot of bosses haven't even used DouBao. A while back I set up DouBao for a boss and he was overjoyed. To us this is a completely ordinary thing. To him it was like a door to a new world opened up, and he wanted to take us out for Moutai. The skills that are completely mundane inside the AI bubble are still rare and valuable in traditional industries.",
    "Another time I was talking to a boss and showing him a product I'd built. He said, you can use AI to write code? I said of course, obviously, everyone uses AI to write code now. But it suddenly hit me: in his entire circle, there might not be a single person who knows how to use AI to write code. He immediately grabbed my hand and said, you have to come help us cut costs and boost efficiency.",
    "---",
    "Over the next two years, everyone knows a huge chunk of jobs will be replaced by AI. But how does that replacement actually happen?",
    "Is it the bosses who haven't even touched DouBao suddenly learning to vibe code, then organizing their entire company's workflow themselves, setting up their own agents, plugging in their own APIs, deploying themselves? No way.",
    "What actually happens is this: a young person walks into a traditional company with a MacBook Air, sits in the office, maybe sits on the floor, and one by one asks the employees. What's the first thing you do every day? Who does this Excel get sent to? What does this field mean? What does that industry term mean? Why do you copy-paste this every time? Which step of this process is the most tedious? Which is the most error-prone? Which is the hardest to handle?",
    "They write it all down and turn it into tools using AI. Maybe it's an internal system, maybe a Chrome extension, maybe a small utility, maybe an agent, maybe an I-don't-know-what-the-fuck-is-this.",
    "But here's the result. AI stops being a cool thing. The boss realizes that what three people used to do, one person can do now. What used to take a day takes ten minutes. What used to require a senior employee mentoring you to ramp up, a new hire can just do with AI. Stuff that used to need someone constantly nagging, AI now proactively messages on its own. That's it.",
    "So that's what FDE actually is.",
    "---",
    "I think this is a huge opportunity for ordinary people. Because what traditional industries are short on isn't a stronger foundation model.",
    "A lot of people building startups are fighting against the model itself. Every week they worry: is Claude Code going to ship some update next week that kills my whole product? But think about it. When you're doing FDE, the stronger the model gets, the stronger you get. The cheaper the model gets, the more powerful you become.",
    "---",
    "FDE asks a lot of you. You have to be willing to meet these bosses. You have to be willing to go on-site. You have to understand what they're saying. You can't mind the dirt, the mess, or the annoyance. Every day starts with Excel files, WeChat screenshots, emails, handwritten receipts, and you turn all of it into an AI workflow.",
    "And you have to be fast. You just had tea with the boss this morning, you need to ship a prototype this afternoon. You just understood something today, this weekend you go heads-down and turn it into system logic.",
    "You don't have to come from the industry. You can know absolutely nothing about it. But you have to be proactive enough to dive in and turn AI into productivity. That's FDE. That's AI BP.",
    "---",
    "Over the next two years, the last mile of AI deployment is going to depend on this kind of person. Carry your laptop into the room. Let companies actually spend less, make fewer mistakes, hire fewer people. That's it.",
  ],
};

export default article;
