import type { Article } from "./types";

const article: Article = {
  slug: "harvard-is-not-harvard",
  titleZh: "哈佛不是哈佛，YC 也不是 YC",
  titleEn: "Harvard Isn't Harvard, YC Isn't YC",
  date: "2026-05-19",
  dateDisplay: "May 19",
  zh: [
    "我们最近一直在聊一件事：ha7ch 到底是什么？",
    "不是商业模式的问题，也不是融资故事的问题。就是很纯粹地在想：我们到底在做一个什么东西？",
    "---",
    "中国有大量中型企业。几十人，上百人，甚至几百人。业务已经复杂到 Excel 顶不住了，但又请不起传统软件公司。",
    "以前他们只有两个选择：花几百万上千万搞中台，或者继续人工硬撑。于是大量行业永远卡在“半数字化”的状态里。",
    "然后 AI native coding 出现了。Claude Code、Cursor、vibe coding……把软件开发成本压到了一个以前不敢想的程度。突然之间，很多原本“不值得做”的需求，现在居然值得做了。",
    "这是我们最早看到的机会。但后来发现，这可能只是表层。",
    "---",
    "后来我们突然意识到：ha7ch 最核心的东西，可能根本不是软件。而是筛人。",
    "现在的大学生不缺教程，不缺课程，不缺 Hackathon。他们缺的是第一次真正进入真实世界。第一次知道：",
    "“原来我写的东西真的有人在用。”",
    "“原来一个系统真的能帮企业省钱。”",
    "“原来我可以靠自己的能力赚到第一桶金。”",
    "Hackathon 做完以后，项目一辈子没人打开第二次。但真实企业不是。企业会天天骂你，天天催你，天天说这里有 bug，天天说流程不对。但也正因为这样，你才真正进入了现实世界。",
    "所以 ha7ch 的本质不是培训班，而是一个 AI native builder 的漏斗。我们在不断筛选：谁真的能沟通，谁真的能进企业，谁真的能理解业务，谁真的能交付，谁真的能把事情做完。",
    "真正的 builder，不是只会写代码的人，而是能把混乱世界变成系统的人。",
    "---",
    "很多人会问：“你们是不是给优秀大学生发钱？”",
    "不是。直接给钱没有意义。真正重要的是，让他第一次赚到钱。那个感觉完全不一样。",
    "一旦一个人发现“卧槽，我靠这个东西真的赚到钱了”，他的世界观会变。而且这种改变是不可逆的。",
    "很多人一辈子都没进入过这种状态。他们只活在 GPA、保研、实习、offer、ranking 的那套游戏里。但真实世界还有另一套游戏。有人适合做 research，有人适合做企业，有人适合创业，有人适合做 0 到 1，有人适合做 1 到 100。",
    "马云也不是清华第一名。不是所有人都要成为学术最顶尖的人。真正重要的是：你有没有找到自己的战场。",
    "---",
    "后来我们想明白了一件事：为什么有些组织最后会变得那么强？",
    "不是因为课程。不是因为 office。不是因为 logo。而是因为那群人。",
    "PayPal Mafia 为什么强？因为那群人后来散落到了整个硅谷，创了 Tesla、LinkedIn、YouTube、Palantir。YC 为什么强？因为它持续在筛选创业者，校友网络越滚越大。哈佛为什么是哈佛？因为哈佛里面是那群人。",
    "如果没有那群人，哈佛也不是哈佛。",
    "所以我们越来越觉得，未来真正值钱的东西不是代码，而是：你和谁一起熬过夜，你和谁一起做过项目，你和谁一起失败过，你和谁一起在深圳的出租屋里赶过 deadline。这些关系会跟着你很多很多年。",
    "---",
    "说实话，我们现在也没想清楚 ha7ch 最终会长成什么样。但有一件事越来越确定：它不一定需要商业化，至少前期不需要。",
    "如果一开始就盯着变现，你会不自觉地去做“能赚钱的事”，而不是“对的事”。我们现在更想做的是，先把人聚起来，先让事情发生，先让年轻人进入真实世界拿到结果。",
    "它更像一个混合体：一个 AI native builder 的社区，一个筛选系统，一个现实世界训练场，一个年轻人的资源网络。",
    "如果非要类比的话，可能更接近早期的 YC。不是一个商业产品，而是一种机制。它的价值不在营收报表里，而在于从里面走出来的那群人。",
    "“我是从 ha7ch 出来的。”我们希望有一天，这句话是有分量的。",
    "---",
    "现在很多人喜欢讨论 AI 会不会替代程序员。",
    "但我们越来越觉得，真正难替代的是另一种能力：你能不能和老板聊天，能不能看懂业务流程，能不能进入一个陌生行业，能不能扛住混乱，能不能组织资源、推动事情、把模糊需求真正落地。",
    "这些东西，AI 很难替代。而这也可能是下一代 builder 最重要的能力。",
    "ha7ch 想做的事情其实很简单：用真实世界，筛出下一代 AI native builder。",
    "商业化的事，以后再说。",
  ],
  en: [
    "Lately we've been chewing on one question: what exactly is ha7ch?",
    "Not a business-model question. Not a fundraising-story question. Just very plainly: what are we actually building?",
    "---",
    "China has a massive number of mid-sized companies. Dozens of people, hundreds, sometimes several hundred. The operations are already too complex for Excel, but they can't afford a traditional software vendor.",
    "Before, they had two options: drop several million on a custom platform, or keep grinding it out by hand. So entire industries got stuck in a “semi-digitalized” limbo.",
    "Then AI native coding showed up. Claude Code, Cursor, vibe coding... they crushed the cost of writing software to a level no one would have dared to imagine. Suddenly a lot of needs that “weren't worth doing” were worth doing.",
    "That was the opportunity we saw first. But later we realized it might only be the surface.",
    "---",
    "We suddenly clicked on something: the core of ha7ch might not be software at all. It's filtering people.",
    "Today's college students aren't short on tutorials, courses, or Hackathons. What they're short on is the first real entry into the real world. The first time they realize:",
    "“Wait, what I built is actually being used.”",
    "“Wait, a system I made actually saved a company money.”",
    "“Wait, I can make my first real money off my own skill.”",
    "After a Hackathon ends, the project never gets opened again. A real company is different. A real company yells at you every day, chases you every day, says there's a bug here every day, says the flow is wrong every day. And precisely because of that, you actually enter the real world.",
    "So ha7ch isn't a bootcamp. It's a funnel for AI native builders. We keep filtering: who can actually communicate, who can actually walk into a company, who can actually understand the business, who can actually deliver, who can actually finish.",
    "A real builder isn't just someone who can write code. A real builder is someone who can turn the mess of the world into a system.",
    "---",
    "A lot of people ask: “Are you guys handing money to top college students?”",
    "No. Handing out money has no meaning. What matters is letting them earn money for the first time. That feeling is completely different.",
    "The moment someone realizes “holy shit, I actually made money doing this,” their worldview shifts. And the shift is irreversible.",
    "A lot of people never get into that state in their whole life. They only live inside the GPA, grad-school, internship, offer, ranking game. The real world has another game. Some people are wired for research, some for enterprise, some for starting things, some for 0-to-1, some for 1-to-100.",
    "Jack Ma wasn't Tsinghua's top student. Not everyone has to become the top of the academic ladder. What matters is: have you found your own battlefield?",
    "---",
    "Then we figured out one more thing: why do some organizations end up so strong?",
    "Not the courses. Not the office. Not the logo. It's the people inside.",
    "Why is PayPal Mafia strong? Because that group later scattered across the Valley and built Tesla, LinkedIn, YouTube, Palantir. Why is YC strong? Because it keeps filtering founders, and the alumni network keeps compounding. Why is Harvard, Harvard? Because inside Harvard is that group of people.",
    "Without those people, Harvard isn't Harvard.",
    "So we increasingly think: the truly valuable thing isn't code. It's who you pulled all-nighters with, who you shipped projects with, who you failed with, who you raced a deadline with in a rented Shenzhen apartment. These relationships stay with you for years and years.",
    "---",
    "Honestly, we haven't figured out what ha7ch finally turns into. But one thing is getting clearer: it doesn't necessarily need to be commercial, at least not at the start.",
    "The moment you stare at monetization from day one, you start unconsciously doing “things that make money” instead of “the right things.” What we want is to gather people first, let things happen first, let young people enter the real world and get results first.",
    "It's more like a hybrid: a community of AI native builders, a filter, a real-world training ground, a resource network for young people.",
    "If we have to analogize, it's closer to early YC. Not a commercial product but a mechanism. Its value isn't in a revenue report. It's in the people who walk out of it.",
    "“I came out of ha7ch.” We hope one day that sentence carries weight.",
    "---",
    "A lot of people like to argue these days about whether AI will replace programmers.",
    "But we increasingly think the truly hard-to-replace ability is a different one: can you talk to the boss, can you read a business workflow, can you walk into an unfamiliar industry, can you take the chaos, can you marshal resources, push things forward, land a vague requirement into something real.",
    "AI has a hard time replacing these. And this might be the most important ability for the next generation of builders.",
    "What ha7ch wants to do is actually simple: use the real world to filter out the next generation of AI native builders.",
    "Monetization, later.",
  ],
};

export default article;
