import type { Article } from "./types";

const article: Article = {
  slug: "mckinsey-ai-is-not-hr-remake",
  titleZh: "劳泰德锐评麦肯锡：AI 不是重做 HR",
  titleEn: "Lawted on McKinsey: AI Is Not an HR Remake",
  date: "2026-08-27",
  dateDisplay: "Aug 27",
  descriptionZh: "麦肯锡看见了 AI 会重构组织，却仍在用传统 HR 的方式规划未来。ANC 的基本单元不是任务，而是可执行、可复用、可审计的 Skill；真正需要重做的不是 HR，而是公司本身。",
  description: "McKinsey sees AI restructuring organizations but still plans the future through traditional HR. An ANC is built from executable, reusable, auditable Skills. The real object of redesign is not HR—it is the company itself.",
  keywords: [
  "AI Native Company",
  "ANC",
  "McKinsey",
  "HR",
  "Skills",
  "FDE",
  "Agent Operations",
  "organization design",
  "麦肯锡",
  "人力资源"
],
  zh: [
  "麦肯锡刚刚发了一篇文章，叫《智能体驱动型组织：AI 如何重写人力资源的底层逻辑？》",
  "我看完以后，评价是：65 分。",
  "它终于意识到，AI 不是给旧流程安装一个聊天机器人，也不是教所有员工写 Prompt，而是要重新拆解任务、能力和责任边界。但麦肯锡最大的问题是：它看见了 AI 会重构组织，却仍然假设这场重构要由 CEO、CHRO、CIO 先开会规划，再由 HR 画一张「任务—能力—智能体」地图来完成。这还是传统大企业转型的逻辑，不是 AI Native Company 的逻辑。",
  "一、组织的基本单元，不是任务，而是 Skill",
  "麦肯锡说，传统组织以岗位为基本单元，未来应该以任务为基本单元。这个方向是对的，但只走了一半。",
  "任务是一次性的，比如帮我筛选这批简历。Skill 是可以被反复调用、组合、审计和迭代的组织能力，比如完成从岗位分析、候选人搜索、简历筛选、邀约到面试复盘的完整招聘流程。",
  "所以 Skill 绝不是一篇 SOP，也不是几个 Prompt。它应该包含上下文、流程、工具、权限、判断标准、交付物和评估机制。",
  "SOP 是告诉员工应该怎么做，Skill 是直接让智能体开始做。过去麦肯锡通过顾问和 Slides 复制组织能力，未来 ANC 通过 Skills 复制组织能力。",
  "二、AI 不是 HR 的工具，而是新的生产资料",
  "这篇文章一直在问：哪些任务交给员工，哪些任务交给 AI，哪些任务需要人机协同？",
  "但真正的 ANC 还要回答：这个智能体拥有什么身份？可以访问哪些数据？能调用哪些工具？对什么结果负责？出错以后谁来接管？它积累的经验如何被其他智能体复用？",
  "如果没有身份、权限、记忆、工具、交付接口和评估体系，所谓的「AI 员工」依然只是一个聊天框。",
  "ANC 不是给公司增加几个 AI 工具，而是为公司建立一套能够调度人类、智能体和数字系统的新操作系统。",
  "三、智能体驱动型组织，不是一次 HR 升级",
  "文章把未来的 HR 描述成「人机协同系统的架构师」。我觉得这个判断过于照顾 HR 了。",
  "智能体驱动型组织首先是业务交付系统的重构，HR 只是被重构的对象之一。",
  "真实的转型路径，通常不是 HR 先制定战略人力规划，再让 IT 部署智能体。而是一线业务出现真实问题，FDE 进入现场拆解流程，在 48 小时内做出第一个可以工作的智能体，让它进入真实业务，再根据交付结果重新定义岗位、流程、绩效和组织结构。",
  "不是 HR 先设计未来组织，再让技术去实现。而是智能体先在业务里跑起来，组织制度再追认已经发生的现实。",
  "未来甚至未必会出现一个更强的 CHRO。HR、IT 和运营的一部分，很可能会被合并成新的 Organization Engineering 或者 Agent Operations 职能。",
  "麦肯锡把 CHRO 重新包装成「首席人类智能体资源架构师」，多少有点像在给旧部门续命。",
  "四、不要一上来就建设「统一底座」",
  "麦肯锡建议企业盘点 10 到 15 条端到端流程，建设统一人力数据底座、技能体系和跨职能治理机制。这些事情当然都对，但按照传统咨询公司的方式执行，很容易重新变成一个三年数字化转型项目：半年画蓝图，一年建平台，最后交付一套 PPT 和一个没人使用的系统。",
  "劳泰德 ANC 的逻辑恰恰相反：先做一单，再做一单，再做一单。",
  "当你连续做成几个真实项目，那些反复出现的上下文、工具、权限、流程和交付方式，才会自然沉淀成 Skill、Harness 和企业架构。",
  "架构不是在项目开始以前想象出来的，架构是从连续交付中长出来的。",
  "五、治理必须存在，但不能成为不行动的借口",
  "麦肯锡非常强调数据治理、权限、审计、人工复核和模型风险。这没有错，尤其是招聘、绩效、薪酬和解雇，本身就是高风险场景。",
  "但治理必须分阶段生长。",
  "48 小时，先证明场景是否存在真实价值，可以由人来兜底。48 天，把流程跑稳定，补齐权限、日志、异常处理和人工复核。48 个月，再考虑跨组织治理、系统维护和长期风险。",
  "如果一个 Demo 第一天就按照跨国集团 2035 年的治理标准设计，它大概率永远不会上线。",
  "不是不要治理，而是治理必须跟着业务风险和系统规模一起生长。",
  "六、真正的问题不是「少招 20 个人」",
  "麦肯锡举了一个例子：企业原本准备招聘 20 名计划员，经过任务拆解以后，可以由少量新增员工、内部转岗、外部专家和 AI 智能体共同完成。",
  "但这仍然只是在优化现有组织。",
  "ANC 真正要问的是：当知识、协调、执行和管理能力都可以被编码成 Skill，公司为什么还需要这么多固定岗位？为什么还需要这么多管理层？为什么所有能力都必须通过全职雇佣获得？一家公司能不能只保留一个很小的核心团队，再动态调用智能体、外部专家和项目型人才？",
  "麦肯锡讨论的是，如何用 AI 重新配置一家大公司的劳动力。",
  "ANC 讨论的是，当组织能力可以被直接调用以后，这家公司还有没有必要长成今天这个样子。",
  "所以，我对这篇文章最终的评价是：它非常适合帮助传统 CEO 理解，AI 不是购买几个工具，而是要改流程、改指标、改责任。",
  "但它距离真正的 AI Native Company，还差三步：从任务走向可执行、可复用的 Skill；从 HR 配置 AI 走向 FDE 在业务现场构建人机交付系统；从优化现有组织走向重新质疑岗位、部门、管理层级，甚至企业本身的边界。",
  "麦肯锡想用 AI 重新设计人力资源。",
  "ANC 想重新设计公司本身。",
  "再说得狠一点：麦肯锡已经看见 AI 会消灭旧组织，却还在认真讨论，旧组织里的 HR 应该升职成什么。"
],
  en: [
  "McKinsey has just published an essay titled “Agent-Driven Organizations: How AI Rewrites the Foundations of Human Resources.”",
  "My score after reading it: 65 out of 100.",
  "It finally recognizes that AI is not about bolting a chatbot onto an old process or teaching every employee to write prompts. It is about redefining tasks, capabilities, and accountability. But McKinsey still assumes that the transformation will be planned in meetings by the CEO, CHRO, and CIO, then completed when HR draws a “task–capability–agent” map. That is the logic of traditional enterprise transformation, not the logic of an AI Native Company.",
  "1. The basic unit of an organization is not the task. It is the Skill",
  "McKinsey argues that traditional organizations are built around jobs, while future organizations should be built around tasks. The direction is right, but it stops halfway.",
  "A task is disposable: screen this batch of résumés. A Skill is an organizational capability that can be called, combined, audited, and improved repeatedly: analyze the role, find candidates, screen applications, send invitations, and review the interviews as one complete recruiting capability.",
  "A Skill is therefore not an SOP document or a handful of prompts. It contains context, process, tools, permissions, judgment criteria, deliverables, and an evaluation mechanism.",
  "An SOP tells an employee how to work. A Skill lets an Agent begin working. McKinsey used to replicate organizational capability through consultants and slides. An ANC replicates it through Skills.",
  "2. AI is not an HR tool. It is a new means of production",
  "The essay keeps asking which tasks should go to employees, which should go to AI, and which require human–AI collaboration.",
  "A real ANC has to go further. What identity does the Agent have? Which data may it access? Which tools may it call? Which result does it own? Who takes over when it fails? How can the experience it accumulates be reused by other Agents?",
  "Without identity, permissions, memory, tools, delivery interfaces, and evaluation, an “AI employee” is still only a chat box.",
  "ANC is not about adding a few AI tools to a company. It is about giving the company a new operating system that can coordinate people, Agents, and digital systems.",
  "3. An agent-driven organization is not an HR upgrade",
  "The essay casts the future HR function as the architect of human–Agent collaboration. I think that is too generous to HR.",
  "An agent-driven organization is first a reconstruction of the business delivery system. HR is only one of the functions being reconstructed.",
  "The real path usually does not begin with HR writing a strategic workforce plan and IT deploying Agents afterward. It begins with a real problem on the front line. An FDE enters the field, breaks down the workflow, ships the first working Agent in 48 hours, puts it into real operations, and then uses delivery results to redefine roles, processes, performance, and structure.",
  "HR does not design the future organization first and ask technology to implement it. Agents run inside the business first; organizational policy then catches up with the reality that has already formed.",
  "The future may not produce a stronger CHRO at all. Parts of HR, IT, and operations may merge into a new Organization Engineering or Agent Operations function.",
  "Rebranding the CHRO as a “Chief Human-Agent Resources Architect” feels, at least partly, like extending the life of an old department.",
  "4. Do not begin with a “unified foundation”",
  "McKinsey recommends mapping 10 to 15 end-to-end processes, building a unified people-data foundation and skills system, and establishing cross-functional governance. All of that can be correct. Executed through the traditional consulting playbook, however, it easily becomes another three-year digital-transformation program: six months drawing the blueprint, a year building the platform, and finally a deck plus a system nobody uses.",
  "Lawted’s ANC logic runs in the opposite direction: deliver one real project, then another, then another.",
  "Only after several real projects succeed do the recurring contexts, tools, permissions, workflows, and delivery patterns naturally harden into Skills, a Harness, and enterprise architecture.",
  "Architecture is not imagined before delivery begins. Architecture grows out of repeated delivery.",
  "5. Governance must exist, but it cannot become an excuse for inaction",
  "McKinsey is right to emphasize data governance, permissions, auditability, human review, and model risk. Recruiting, performance, compensation, and termination are high-risk domains.",
  "But governance has to grow in stages.",
  "In 48 hours, prove that the use case creates real value, with humans covering the gaps. In 48 days, stabilize the workflow and add permissions, logs, exception handling, and human review. In 48 months, address cross-organizational governance, long-term maintenance, and systemic risk.",
  "If a demo must satisfy the governance standard of a multinational corporation in 2035 on day one, it will probably never go live.",
  "The point is not to remove governance. Governance must grow with business risk and system scale.",
  "6. The real question is not whether to hire 20 fewer people",
  "McKinsey describes a company that planned to hire 20 planners, then decomposed the work so a smaller number of new hires, internal transfers, outside experts, and AI Agents could do it together.",
  "That still only optimizes the existing organization.",
  "ANC asks a more fundamental question. If knowledge, coordination, execution, and management can all be encoded as Skills, why does the company still need so many permanent roles and management layers? Why must every capability be acquired through full-time employment? Could a small core team dynamically call Agents, external experts, and project-based talent instead?",
  "McKinsey is discussing how AI can reallocate the workforce of a large company.",
  "ANC is asking whether a company whose capabilities can be called on demand still needs to grow into the shape it has today.",
  "My final judgment is that the essay can help a traditional CEO understand that AI is not a shopping list of tools. It requires changing processes, metrics, and accountability.",
  "But it remains three steps away from a true AI Native Company: from tasks to executable and reusable Skills; from HR allocating AI to FDEs building human–Agent delivery systems in the field; and from optimizing the existing organization to questioning jobs, departments, management layers, and even the boundary of the firm.",
  "McKinsey wants to use AI to redesign human resources.",
  "ANC wants to redesign the company itself.",
  "Put more sharply: McKinsey can already see AI dismantling the old organization, yet it is still carefully debating what promotion HR should receive inside it."
],
};

export default article;
