import type { Article } from "./types";

const article: Article = {
  slug: "poetry-and-the-plaza",
  titleZh: "两双眼睛",
  titleEn: "Two Pairs of Eyes",
  date: "2026-05-10",
  dateDisplay: "May 10",
  zh: [
    "我最近一直在想旧金山和硅谷的事。",
    "更准确地说，我在想为什么这两个地方开车只要四十分钟，但它们给人的感觉差得像两个国家。",
    "硅谷其实根本不是一座城市。它是一片郊区。一个又一个 plaza，一个又一个住宅区，一个又一个公司园区。每个城市都有一个所谓的 downtown，但是放到旧金山来看，那个 downtown 也就只能算一个街区。",
    "但地理只是表面。真正不一样的是凝视。",
    "你住在硅谷的时候，你总是能感到有人在看你。",
    "但说实话，那些人其实并没有真的在看你。美国生活的真相是，你独处的时间比你以为的多。你能感觉到的那种凝视，绝大多数时候是你自己在凝视你自己。",
    "只是这双眼睛是你住的这个地方装上去的。它装好以后，就再也卸不下来了。哪怕在没有人的房间里、没有人的高速上、没有人的凌晨两点，那双眼睛也还是开着的。",
    "硅谷给你装的，是一双有非常清晰刻度的眼睛。它会一直问你：你 title 升了吗？你公司估值多少？你小孩进了哪个学区？这些问题都有清楚的答案。你随时可以回答，也随时知道自己在哪一档。",
    "这种刻度是双刃的。一方面，它会慢慢把一个人磨成它所测量的形状。你最后变成了一个主要由这些指标定义的人。",
    "但另一方面，一个永远没有刻度的人，也很难把一件事做到极致。我知道这个观点不讨喜，但我越来越觉得它是对的。",
    "在意自己有没有被这双眼睛打分，和在意自己有没有把事情做好，其实是同一种内在结构。一个完全不在意外界目光的人，往往也写不出有 test 的代码、做不出能给一千个陌生人用的产品、坚持不了一个三十年的事业曲线。耐心、严谨、收尾——这些都是有「观众」的人才容易具备的品质。哪怕那个观众只是想象中的。",
    "硅谷之所以是硅谷，正是因为这双眼睛在过去几十年里逼出了世界上最厉害的一批工程师、最严格的产品标准、最长期的耐心。它杀创造力，但它也喂养卓越。这是同一个东西在你不同阶段会变成不同的东西。发明需要这双眼睛闭上，建造需要这双眼睛睁开。",
    "我觉得这其实和亚洲很像。亚洲装上的也是这样一双眼睛，无形的、内化的、永远在那里。它消耗自由，但它也建造了让一代一代人能稳定生活的秩序。这不是一个好坏的问题，是一个你现在需不需要它的问题。",
    "旧金山也有自己的凝视。我不想把旧金山写成一座没有凝视的城市，因为它不是。",
    "但旧金山给你装的眼睛不一样。",
    "硅谷的眼睛问的是：他们看见你了吗？",
    "旧金山的眼睛问的是：你看见你自己了吗？",
    "第一个问题有答案。第二个问题没有。",
    "第一个问题的答案在你的工资条上、你的 LinkedIn 上、你小孩的录取通知书上。第二个问题的答案，只有你一个人在凌晨三点的时候能隐约感觉到，而且经常感觉不到。",
    "所以旧金山其实并不是一座更轻松的城市，它只是把工作的方向换了。它把「被世界看见」的工作，换成了「看见自己」的工作。前者有 KPI，后者没有。前者可以表演，后者表演不了。前者你做对了别人会鼓掌，后者你做对了没人知道。",
    "很多人以为搬来旧金山就能从凝视里逃出来。其实不能。他们只是从一种凝视搬到了另一种凝视。而且很多人最后会偷偷把硅谷那把尺子带过来——他们用旧金山的方式过日子，但用硅谷的标准给自己打分，结果是两边的代价都付了。",
    "但即便如此，旧金山的凝视确实更稀薄一些，因为这座城市从一开始就是各种奇怪的人的避难所。淘金的、传教的、流浪的、写诗的、写代码的、不想结婚的、不想要小孩的、不想穿正常衣服的、不想做正常工作的人，都在这里找到了他们的角落。",
    "旧金山的建筑也是这样。它不是在告诉你这座城市多漂亮，它是在告诉你：你不需要正常才能过得好。",
    "而硅谷的建筑说的是另一种语言。低矮的、平的、整洁的、白的、米色的、永远在修剪的草坪，永远停着的 Tesla。这些建筑不会告诉你任何事情，它们只是在等你去配合它们。这种配合不浪漫，但它有一种被低估的好。一栋不要求你的房子，对一个白天一直被要求的人来说，本身就是一种喘息。它不要求你 interesting，不要求你 edgy，不要求你证明什么。你可以疲惫，可以无聊，可以发呆，可以一连好几个小时什么都不是。米色和草坪不会问你今天有没有更有意义地活着。",
    "AI 又把年轻人带回了 SoMa，带回了 Hayes Valley，带回了 Mission。他们二十几岁，没结婚，没小孩，不开 Tesla，租一个 studio，或者睡在朋友的 air mattress 上，每天在 cafe 里写代码到凌晨。他们在做一些可能会改变世界，也可能两个礼拜就 pivot 掉的产品。",
    "硅谷大部分是 house，旧金山大部分是 apartment、condo、townhouse。我觉得这背后藏着一件挺有意思的事。",
    "住在 house 里，你的连接是向内的。你有一个家庭，一个院子，一个晚饭时间。你最重要的关系都已经在这堵墙里面了，你不太需要往外找。你的想法也就不那么容易被改变。",
    "住在 studio 里，你的连接是向外的。你的房子小到你不愿意一直待在里面，所以你会出门，去 cafe，去 coworking，去随便一个 meetup，去认识完全不认识的人。你不知道你下一个想法会从谁那里来，但你知道它一定不会从你这一百二十平方英尺的墙里冒出来。",
    "两种都是连接，但方向不一样。一种是在养护已经有的关系，一种是在不断地往外伸触手。这大概也是为什么旧金山的人想法更容易变。",
    "我后来想明白了，这两个地方其实代表了一个人在不同阶段的两种状态。",
    "硅谷是已经知道自己要去哪儿的人住的。他们的人生是要被持续优化的。",
    "旧金山是还没想好自己要去哪儿的人住的。他们的人生不是要被优化的，是要被发明的。",
    "诗和苟且其实就这一点区别。但苟且不是不好。苟且是你拿着别人写好的尺子，然后在那把尺子上把日子过到最好。诗是你扔掉那把尺子，自己去找一把还没人造出来的。",
    "一个人这一辈子，大概率两种都需要。先用别人的尺子把基础打牢，再扔掉它去找自己的。或者反过来，先用自己的尺子瞎走一段，最后接受那把更主流的尺子，把它打磨成自己的。问题不是哪个更高级，问题是你现在在哪个阶段，以及你有没有诚实地知道自己在哪个阶段。",
    "说到底，每次开车从硅谷北上，过了 Daly City，旧金山的天际线在雾里浮出来的那一瞬间，我都会松一口气。",
  ],
  en: [
    "I've been thinking a lot about San Francisco and Silicon Valley lately.",
    "More specifically, I've been thinking about why these two places, only forty minutes apart by car, feel like two different countries.",
    "Silicon Valley is not a city. It's a suburb. Plaza after plaza, neighborhood after neighborhood, corporate park after corporate park. Every town has a so-called downtown, but compared to SF, those downtowns are basically just one block.",
    "But geography is just the surface. The real difference is the gaze.",
    "When you live in Silicon Valley, you can always feel someone watching you.",
    "But honestly, those people aren't actually watching you. The truth of American life is that you spend more time alone than you think. The gaze you can feel — almost all the time — is yourself watching yourself.",
    "It's just that the eyes you're watching yourself with were installed by the place you live. Once they're installed, you can't take them off. Even in an empty room, on an empty highway, at 2am with nobody around, those eyes are still open.",
    "Silicon Valley installs a pair of eyes with very clear markings on them. They keep asking you: did you get the promotion? What's your company's valuation? Which school district did your kid get into? These questions all have clear answers. You can answer them at any moment, and at any moment you know exactly where you stand.",
    "These markings are double-edged. On one hand, they slowly grind you into the shape they measure. You end up becoming a person mostly defined by these numbers.",
    "On the other hand, a person without any markings also has a hard time pushing anything to its limit. I know this take isn't popular, but I think it's correct.",
    "Caring about whether those eyes are scoring you and caring about whether you've actually done a good job are the same internal structure. A person who genuinely doesn't care what anyone thinks usually doesn't write code with tests, doesn't ship a product polished enough for a thousand strangers to use, doesn't sustain a thirty-year career arc. Patience, rigor, finishing — these are qualities that come more naturally to people who have an audience. Even if the audience is only imagined.",
    "Silicon Valley is Silicon Valley because those eyes have, over decades, produced the world's best engineers, the most ruthless product standards, the longest patience. They kill creativity. But they also feed excellence. It's the same thing turning into different things at different stages of your life. Invention needs those eyes closed. Building needs them open.",
    "I think this is similar to what happens in Asia. Asia installs the same kind of eyes — invisible, internalized, always there. They eat freedom, but they also build the kind of order that lets generations live stable lives. It's not a question of good or bad. It's a question of whether you need them right now.",
    "San Francisco has its own gaze too. I don't want to write SF as a city without a gaze, because it isn't.",
    "But the eyes SF installs are different.",
    "The Silicon Valley eyes ask you: do they see you?",
    "The SF eyes ask you: do you see yourself?",
    "The first question has an answer. The second one doesn't.",
    "The answer to the first is on your paycheck, your LinkedIn, your kid's acceptance letter. The answer to the second is something only you can faintly feel at 3am, alone, and very often you can't feel it at all.",
    "So SF isn't actually a lighter city. It just changes the direction of the work. It swaps the work of being seen for the work of seeing yourself. The first has KPIs. The second doesn't. The first you can perform. The second you can't. When you do the first one right, people clap. When you do the second one right, nobody knows.",
    "A lot of people think moving to SF lets them escape the gaze. It doesn't. They just move from one gaze to another. And many of them quietly bring the SV ruler with them — they live an SF life but score themselves with an SV scorecard, and end up paying both costs.",
    "That said, the SF gaze is genuinely thinner, because from the very beginning this city was a refuge for weird people. Gold rushers, missionaries, drifters, poets, coders, people who didn't want to get married, people who didn't want kids, people who didn't want to wear normal clothes, people who didn't want to do normal jobs. They all found their corner here.",
    "The architecture says the same thing. It's not telling you the city is beautiful. It's telling you: you don't need to be normal to live well.",
    "Silicon Valley's architecture speaks a different language. Low, flat, clean, white, beige, lawns always trimmed, Teslas always parked. These buildings don't tell you anything. They just wait for you to fit them. That kind of fitting isn't romantic, but it has an underrated kind of good. A house that doesn't demand anything of you is, for someone who has been demanded of all day, its own kind of rest. It doesn't ask you to be interesting. It doesn't ask you to be edgy. It doesn't ask you to prove anything. You can be tired. You can be bored. You can stare into space. You can spend three hours being nobody at all. The beige and the lawn don't ask you whether you spent the day living meaningfully enough.",
    "AI brought the young people back to SoMa, to Hayes Valley, to the Mission. Twenty-somethings, not married, no kids, no Tesla, renting a studio, or sleeping on a friend's air mattress, writing code in a cafe until 2am. They're building things that might change the world, or might pivot in two weeks.",
    "Silicon Valley is mostly houses. SF is mostly apartments, condos, townhouses. I think there's something interesting hiding behind that.",
    "When you live in a house, your connections point inward. You have a family, a backyard, a dinner time. The relationships that matter most to you are already inside these walls. You don't need to go looking. And your thoughts stop changing that easily.",
    "When you live in a studio, your connections point outward. The apartment is too small to want to stay inside, so you go out — to cafes, to coworking, to random meetups, to meet people you've never met. You don't know where your next idea will come from, but you know it won't come from inside your 120 square feet.",
    "Both are connection, just in different directions. One tends to what's already there. The other keeps reaching outward. That's probably also why people in SF change their minds more easily.",
    "And eventually I figured it out: these two places really represent two states a person can be in at different stages of life.",
    "Silicon Valley is for people who already know where they're going. Their lives are meant to be optimized.",
    "SF is for people who haven't figured out where they're going. Their lives are not meant to be optimized. They're meant to be invented.",
    "That's the difference between poetry and the grind. But the grind isn't bad. The grind is taking the ruler somebody else wrote and being as good as possible on that ruler. Poetry is throwing that ruler away and trying to find one nobody has made yet.",
    "Most people will probably need both at some point. First use someone else's ruler to lay a foundation, then throw it away and look for your own. Or the other way around — wander around with your own ruler for a while, then accept the more mainstream one and grind it into your own. The question isn't which one is higher. The question is which stage you're in right now, and whether you're being honest with yourself about it.",
    "Honestly, every time I drive north out of Silicon Valley, past Daly City, and the SF skyline emerges from the fog, I feel myself exhale.",
  ],
};

export default article;
