import type { Article } from "./types";

const article: Article = {
  slug: "question-every-instinct",
  titleZh: "质疑你的每一个直觉",
  titleEn: "Question Every Instinct",
  date: "2026-05-13",
  dateDisplay: "May 13",
  zh: [
    "做了 Raily 以后，每天会有非常多的人给我们提建议。",
    "听起来都很有道理，听起来都像是顺理成章的下一步。但是我发现，大部分的建议如果你顺着直觉去做，全是错的。",
    "我说真的，全是错的。",
    "---",
    "举个例子。我们小红书群里大概 1000 个人，每天嘎嘎地提需求。听了好多人跟我说：你可以做一个小红书的 agent，让 agent 去读群里面的消息，整理成需求文档，然后你就可以更方便地去做，不需要在群里面提供情绪价值了。",
    "我说大错特错，大错特错，错到离谱。",
    "第一，我们建这个群是因为我们要学习的是如何去运营。我们写代码他妈的已经写了五年了，我们还学什么代码？我们要学的就是如何去给别人提供情绪价值，这是我们当下的瓶颈，不是写代码。",
    "第二，你做小红书的 agent，反爬非常严重。你掉进去就是个无底洞，烧时间、烧脑子、收益接近于零。",
    "那正确的做法是什么？你他妈应该自己在群里一边提供情绪价值，一边把需求整理出来。把需求整完了以后，丢给 Claude Code 或者 Codex 自己去写。这才是正道。",
    "而且这后面的技术难度是零，就是现在的工作流，对不对？",
    "也就是说，你顺着直觉是想用 agent 去做你最值得人工做的部分，然后自己花时间去做 agent 最容易做的部分。完全反了。",
    "---",
    "再举个例子。我们这边开始做了 writing，然后有人说：你们应该给 writing 加上邮件订阅。",
    "我说不对呀。",
    "邮件是正在退场的东西。如果我的判断是对的，后面大家会进入零 token 时代，所有人都会有自己的 AI agent。",
    "那这种情况下我们应该做什么？应该做一个 CLI，或者一个 MCP，让大家可以把他们的 agent 接进来。",
    "他们的 agent 在任何时候，如果他想起来要读一下我们的文章，可以直接问 AI。AI 也可以帮他总结、帮他提炼、帮他翻译成各种各样的语言。",
    "或者，如果他想自动化，应该是他的 agent 每天定时来爬一下我们的网站，把新的内容拉走。",
    "所以我们要做的不是在网页里嵌一个聊天机器人，也不是加一个邮件订阅按钮。我们要做的是让我们的网站对 agent 更友好，更容易被读、更容易被理解、更容易被消费。",
    "你顺着直觉想做的是把人留在你的网页上。但未来的事情是，人根本就不会来你的网页。",
    "---",
    "所以我现在每次听到一个建议、产生一个直觉，先停下来。",
    "问自己：这个直觉到底来自哪个时代？是来自上一个时代的范式吗？是来自我以前的舒适区吗？",
    "大部分的时候，答案是是的。",
  ],
  en: [
    "Since shipping Raily, we get a ton of suggestions every day.",
    "They all sound reasonable. They all sound like the obvious next step. But I've noticed that most of them, if you just follow your gut and do them, are wrong.",
    "I mean it. All wrong.",
    "---",
    "Example one. We have a RedNote group of about 1000 people dropping feedback all day. A bunch of people told me: you should build a RedNote agent. Have the agent read the group messages, turn them into a requirements doc, then you can build the requested features faster and you don't have to keep providing emotional value in the group.",
    "I told them: you're dead wrong. Completely wrong. Absurdly wrong.",
    "First, the reason we built this group is to learn how to do ops. We've been writing fucking code for five years. Why would we want to learn more code? What we need to learn right now is how to give people emotional value. That's our current bottleneck. Not code.",
    "Second, building a RedNote scraper agent walks straight into anti-bot hell. It's a bottomless pit. Burns time, burns brain, returns close to zero.",
    "What's the right move? You provide the emotional value yourself, in the group, and while you're at it you distill the requirements yourself. Once the requirements are clean, you hand them to Claude Code or Codex and let it write the code. That's the right way.",
    "And the technical difficulty of that second half is zero. That's literally today's workflow. Right?",
    "Following the gut, you were going to use the agent for the part that's most worth doing by hand, and spend your own time on the part the agent is best at. Completely flipped.",
    "---",
    "Example two. We started doing writing, and people said: you should add email subscriptions.",
    "Nope.",
    "Email is a thing on the way out. If my read is right, we're heading into a zero-token era. Everyone will have their own AI agent.",
    "So what should we build? A CLI, or an MCP, so people can plug their agents in.",
    "Whenever their agent wants to read our writing, it can just ask the AI. The AI summarizes, extracts, translates into whatever language. That's how the consumption is going to happen.",
    "Or, if they want it automated, their agent crawls our site on a schedule and pulls in the new content.",
    "So the move is not to embed a chatbot widget on the page, and not to slap on an email subscription button. The move is to make our site more agent-friendly. Easier to read, easier to parse, easier to consume.",
    "Following the gut, you were trying to keep people on your webpage. But the future is that people aren't going to come to your webpage at all.",
    "---",
    "So now, every time I hear a suggestion or feel an instinct, I stop.",
    "I ask: which era does this instinct come from? Is it a paradigm from the previous era? Is it my old comfort zone?",
    "Most of the time, the answer is yes.",
  ],
};

export default article;
