import type { Article } from "./types";

const article: Article = {
  slug: "resume-material-from-700-conversations",
  titleZh: "700 条对话记录里藏着我最好的简历素材，但我懒得翻",
  titleEn: "My Best Resume Material Was Hidden in 700 Conversations, But I Was Too Lazy to Dig",
  date: "2026-05-22",
  dateDisplay: "May 22",
  description: "A personal workflow for using AI agents to mine real project history, conversations, and commits into stronger resume material.",
  descriptionZh: "一次用 AI 子代理从真实项目记录、对话和 git commit 里挖简历素材的实践。",
  keywords: [
    "HA7CH",
    "AI native",
    "resume",
    "Codex",
    "Claude Code",
    "subagents",
  ],
  zh: [
    "事情是这样的。",
    "我在准备一份实习简历，方向是 AI Coding 产品经理。我日常开发全靠 AI，Claude Code 和 Codex 两个工具换着用，三个月烧了 39.5 亿 tokens。这些经历如果写进简历，是非常硬的素材。",
    "问题来了，这些素材散落在几百个对话框里。",
    "700 个 sessions，96 个项目，每个项目里我跟 AI 说了什么、怎么协作的、踩了什么坑，全部埋在 jsonl 文件和 git commit 里面。一个个翻？我光想想就觉得要死。",
    "然后我做了一件很自然的事，让 AI 自己去翻。",
    "我同时派了 7 个子代理出去。一个去扫我的 token 用量数据，一个去翻 Codex 的对话记录找我怎么开发电子日记的，一个去 git log 里还原我修 bug 的真实时间线，一个去读我的全局配置文件看我为什么选这个模型不选那个。每个代理都有明确的搜索范围和任务目标。",
    "几分钟后，19 份调研报告回来了。",
    "我举几个例子你们感受一下这个「准确」是什么意思。",
    "R10 报告告诉我，我的 Codex 用量占 token 总消耗的 60%，Claude Opus 4.6 占总对话的 78%。前者跑代码，后者跑文字。我自己是知道这个习惯的，但我从来没量化过。代理直接去 data.json 里按模型拆分算出来的。",
    "R4 报告还原了一个 bug 故事。我的跨设备文件传输工具 Folip 出了个「上传成功但 Android 下载不到」的问题，AI 在客户端代码里反复打转找不到原因。我当时做了一件事，让 AI 自己去读阿里云 OSS 的访问日志。秒定位，预签名 URL 漏算了 Content-Type。代理从 git commit 里把这整条时间线还原得清清楚楚。",
    "R8 报告挖出了我做电子日记项目时的一个细节，Codex 帮我校对手写日记的时候会「自作主张」润色，把「但她很 normal」扩写成「但是她也很 normal」。我因此写了 7 条「不要」规则，沉淀进 prompt 里。代理找到了对应的 jsonl 文件路径和时间戳。",
    "这些东西我自己去翻可能要一整天，而且大概率会记错细节。AI 去翻自己的记忆，又快又准。",
    "但这不是最有意思的部分。",
    "最有意思的是我跟 AI 之间的纠错过程。代理跑回来的初稿里有好几个地方写反了或者写过了。比如有个代理把我用 Codex 和 Claude 的逻辑写反了，我立刻纠正。有个代理写了一个「15% context 优化」的技术细节，我说「我自己都不太懂这个」，直接删掉。还有一个把我发现 bug 的过程写成了「手动查看日志」，我说不对，是我让 AI 去读的。",
    "每一轮纠正都让简历离真实更近一步。最后定稿的简历里，每一个数字、每一个故事、每一个判断都是我真的做过、真的想过、真的能在面试里讲清楚的。",
    "说真的，我觉得这才是 AI native 写简历应该有的样子。不是让 AI 帮你编一份华丽的简历，是让 AI 帮你从自己的真实数据里把最好的素材挖出来，然后你来把关哪些是真的你、哪些不是。",
    "AI 的记忆比你好，但只有你知道哪些记忆是你的。",
  ],
  en: [
    "Here is what happened.",
    "I was preparing an internship resume for an AI Coding product manager role. My daily development depends almost entirely on AI. I switch between Claude Code and Codex, and in three months I burned through 3.95 billion tokens. If these experiences went into my resume, they would be very solid material.",
    "The problem was that all this material was scattered across hundreds of chat windows.",
    "700 sessions, 96 projects. What I said to AI in each project, how I collaborated with it, what traps I stepped into, all buried inside jsonl files and git commits. Go through them one by one? Just thinking about it made me want to die.",
    "So I did the most natural thing: I let AI go dig through it itself.",
    "I sent out 7 subagents at the same time. One scanned my token usage data. One went through Codex conversations to find how I built my electronic diary. One reconstructed the real bug-fixing timeline from git log. One read my global config files to understand why I chose one model over another. Every agent had a clear search scope and a clear task target.",
    "A few minutes later, 19 research reports came back.",
    "Let me give you a few examples so you can feel what I mean by \"accurate.\"",
    "Report R10 told me that Codex accounted for 60% of my total token consumption, while Claude Opus 4.6 accounted for 78% of my total conversations. The former handled code, the latter handled writing. I knew I had this habit, but I had never quantified it. The agent went straight into data.json, broke it down by model, and calculated it.",
    "Report R4 reconstructed a bug story. My cross-device file transfer tool Folip had a problem where uploads succeeded but Android could not download the file. AI kept circling around the client code and could not find the cause. At the time, I did one thing: I asked AI to read the Alibaba Cloud OSS access logs itself. It found the issue instantly. The pre-signed URL had missed Content-Type in the calculation. The agent reconstructed that entire timeline clearly from git commits.",
    "Report R8 dug up a detail from my electronic diary project. When Codex helped me proofread handwritten diary entries, it would \"take initiative\" and polish them, expanding \"但她很 normal\" into \"但是她也很 normal.\" Because of that, I wrote 7 \"do not\" rules and folded them into the prompt. The agent found the exact jsonl file path and timestamp.",
    "If I had gone through all this myself, it might have taken a whole day, and I probably would have remembered the details wrong. Letting AI dig through its own memory was both fast and accurate.",
    "But that was not the most interesting part.",
    "The most interesting part was the correction process between me and AI. In the drafts the agents brought back, several places were reversed or overstated. For example, one agent got my logic for using Codex and Claude backwards, and I immediately corrected it. Another wrote about a technical detail called \"15% context optimization,\" and I said, \"I don't really understand this myself,\" then deleted it directly. Another described my bug discovery process as \"manually checking logs,\" and I said no, that was wrong. I had asked AI to read the logs.",
    "Every round of correction moved the resume closer to reality. In the final version, every number, every story, and every judgment was something I had actually done, actually thought through, and could actually explain clearly in an interview.",
    "Honestly, I think this is what an AI-native resume-writing process should look like. It is not asking AI to invent a polished resume for you. It is asking AI to dig the best material out of your own real data, then having you judge what is truly you and what is not.",
    "AI has a better memory than you do, but only you know which memories are yours.",
  ],
};

export default article;
