import type { Article } from "./types";

const article: Article = {
  slug: "scissors-in-the-gap",
  titleZh: "缝隙里有一把剪刀",
  titleEn: "A Pair of Scissors in the Gap",
  date: "2026-06-04",
  dateDisplay: "Jun 4",
  descriptionZh:
    "我钻进了《被忽略的大陆》说的那个缝隙,在里面撞到一把剪刀:ACV 低的客户做得动却不赚钱,ACV 高的客户赚钱却不是一个 builder 扛得动的。FDE 是 land,不是生意。",
  description:
    "I crawled into the gap from The Ignored Continent and hit a pair of scissors: the customers you can serve don't pay enough, and the ones who pay are beyond a single builder. FDE is the land, not the business.",
  keywords: [
    "FDE",
    "OPC",
    "ACV",
    "vertical AI",
    "freight forwarding",
    "货代",
    "HA7CH",
    "Palantir",
    "moat",
    "data flywheel",
  ],
  zh: [
    "前段时间我写了《被忽略的大陆》。我说,最大的市场不在大厂里,在每一条你看不见的产业带上。光深圳做船单物流的就有 8000 多家,工作流大同小异——微信接单,Excel 做单,PDF 传文件,人工核对,人工录入,人工催款。我说,大厂进不来,VC 不投,外包做不好,老板自己搞不定。这就是那个缝隙,HA7CH 要钻进去。",
    "然后我真的钻进去了。一头扎进货代,扎进一家真实的公司、真实的单子、真实的跟单员。",
    "现在我要诚实地告诉你,我在那个缝隙里撞到了什么。",
    "我撞到了一把剪刀。",
    "---",
    "先说清楚这把剪刀长什么样。",
    "一家三四十个人的货代公司,一年在系统上花两万块。我能帮他。我能把他那套靠人肉堆出来的活,用 AI 重写一遍,真的能省人。这一点我验证了——老板握着我的手,说你一定要过来帮我降本增效。",
    "但是我收不到钱。因为他的价格天花板,就焊死在两万块那条线下面。我投进去的人力,比这两万块贵。低客单的客户,我做得动,但不赚钱。",
    "那我往上走,找大一点的、ACV 高一点的客户。",
    "问题就来了。ACV 一旦高到值得我做,这个客户就大到、复杂到一个背着 MacBook 的人根本扛不住。他要安全,要合规,要 SLA,要出了事凌晨三点有人接电话,要一整套交付体系和问责。",
    "而这套东西,恰恰是大厂 FDE 有、我没有的。我有的是个体能力,他要的是组织能力。",
    "---",
    "所以你发现没有:ACV 和一个 builder 的能力,是反着走的。",
    "ACV 越高,客户越大越复杂,越需要组织;ACV 越低,我越做得动,但越不赚钱。这把剪刀的两片是连在一起的。我想用涨价去救毛利,可涨上去的那一刻,客户就开始要我恰好给不了的东西。",
    "中间那条「ACV 高到能赚钱、又简单到一个人能交付」的窄带,薄得几乎不存在。",
    "---",
    "这一刀下去,让我后背发凉的不是「货代不行」。是另一件事。",
    "我在《被忽略的大陆》里说,大厂进不来,因为不可能为了一个三四十人的物流公司专门派一个团队。当时我把这当成机会。",
    "但现在我明白了:让大厂派团队不划算的原因,和让我派人也不划算的原因,是同一个——这家公司付不起 FDE 的人力。",
    "那个缝隙之所以空着,不是因为别人都蠢。是因为「靠人交付」这件事,在两头都不闭合。我看到了金子,却从来没给那把锁住金子的剪刀定过价。",
    "---",
    "我想了很久,差点就放弃了。但有一个东西救了这件事——而且只有这一个。",
    "这把剪刀,只在「交付靠人」的时候才剪得动。",
    "如果我从一家公司蒸馏出来的东西,变成了一个不靠我、自己会跑起来的软件——那两片刀刃,同时松开了。",
    "低客单变得能赚钱:边际成本趋近于零,我可以铺一整条长尾。",
    "高客单变得能接:扛复杂度的是产品,不是我那副坐在椅子上的身体。",
    "软件,是唯一能同时碰到剪刀两片的东西。",
    "---",
    "我以前一直把 Palantir 当 FDE 的样板。可 Palantir 从来不靠 FDE 赚钱,它靠 Foundry。",
    "FDE 是 land,是走进去的那一下;产品,才是生意。FDE 那点人力是被产品的毛利补贴的,而且最终会被产品替代。",
    "我犯的错,是把「走进去」这个动作,当成了生意本身。剪刀差,就是对这个混淆的惩罚。",
    "---",
    "其实这几个星期,我一个人跟自己吵了好几轮。",
    "我说,AI 解析托书是护城河吧?不是,谁接个模型一周都能抄。",
    "那整封对账邮件的双侧解析呢?也会被抄,而且现在还老出错。",
    "那我干脆把活全接过来、替客户跑(OPC)呢?信任扛不住,出了事谁赔。",
    "那靠走量呢?客单两万,封顶。",
    "那同行第二家、第三家复制呢?每家都得重新摸一遍业务流,根本不省力。",
    "现在,又来一把剪刀。",
    "五个不同的角度,全撞在同一面墙上。这面墙,是同一句话:我从一家公司蒸馏出来的知识,到底能不能变成一个「自己会交付、而且越用越准」的软件。",
    "---",
    "然后我得承认一件最难堪的事。",
    "我在《HA7CH 是一个 FDE 加速器》里写过最性感的一句话:每个传统公司有且只能被蒸馏一次,蒸馏完,所有知识都进入这个 AI 系统,别人再想蒸馏就非常难,老板也不会想切换。",
    "这句话,我从来没验证过。一次都没有。",
    "我做的产品,确实在偷偷地把人工的每一次修正都记下来:AI 当时填了什么,人最后改成了什么,一对一对地存进库里。这是蒸馏里最难的一半,我把它建好了。",
    "但另一半——把这些修正喂回去,让它下一次更准、让它真的越用越厚——我一行都没写。那张表,只进不出。",
    "我理论里最承重的那块砖,我盖了一半,从来没压过它到底承不承重。",
    "---",
    "所以我决定停下来。",
    "停止写理论。停止给「它为什么不行」找新的理由——我已经找到五个了,而每一个的终点,都是同一面没被压过的墙。",
    "再聪明的论证也撑不开那把剪刀。只有一个东西能:把那面墙的另一半盖上,然后压一次。",
    "这件事,一个星期就能见分晓。我把那些「AI 填错、人改对」的配对喂回去,看同一个客户、同一个海外代理的账单,人工修正率是平的,还是往下走的。",
    "如果是平的——那我认。这就是一门被剪刀封了顶的服务生意,能让几个人赚到第一桶金,但不是我想要的那个东西。早点认,比晚点认值钱。",
    "如果它往下走——那把剪刀,就被撑开了。被忽略的大陆,重新成立。",
    "---",
    "我写《MVP as Research》的时候说过:先把食物丢在地上,看有没有人吃;有人吃,再给他安排一个盘子。",
    "货代,就是我丢在地上的那块食物。有人啃了一口。研究结论现在回来了——不是没人饿,是这块地上,有一把剪刀。",
    "我不会再用嘴把自己 argue 上那片大陆。我要走过去,把那面墙压一次,看它到底承不承重。",
    "That's it。",
  ],
  en: [
    "A while back I wrote The Ignored Continent. I said the biggest market isn't inside the big tech companies. It's on every industrial belt you can't see. In Shenzhen alone there are 8,000-plus companies doing ocean freight forwarding, and their workflows are roughly the same — orders come in over WeChat, the paperwork gets done in Excel, files get passed around as PDFs, everything reconciled by hand, keyed in by hand, chased for payment by hand. I said big tech can't get in, VCs won't touch it, outsourcing does it badly, and the bosses can't do it themselves. That's the gap. And HA7CH was going to crawl into it.",
    "So I actually crawled in. Headfirst into freight forwarding — a real company, real shipments, real operators.",
    "Now I'm going to be honest with you about what I hit in that gap.",
    "I hit a pair of scissors.",
    "---",
    "Let me spell out what these scissors look like.",
    "A freight forwarder with thirty or forty people spends maybe twenty thousand RMB a year on software. I can help him. I can take the work he's been doing by piling up human labor and rewrite it with AI, and genuinely cut headcount. That part I've verified — the boss grabbed my hand and said you have to come help us cut costs and boost efficiency.",
    "But I can't collect the money. Because his price ceiling is welded to a line below twenty thousand. The labor I pour in costs more than that twenty thousand. Low-ACV customers: I can do the work, but I can't make money.",
    "So I go upmarket. Bigger customers, higher ACV.",
    "And here's the problem. The moment the ACV is high enough to be worth my time, the customer is big enough and complex enough that one guy with a MacBook simply can't carry it. He wants security, compliance, SLAs, someone who picks up the phone at 3 a.m. when something breaks, a whole delivery org and a chain of accountability.",
    "And that is exactly what big-tech FDE has and I don't. What I have is individual capability. What he wants is organizational capability.",
    "---",
    "So you see it, right? ACV and a builder's capability point in opposite directions.",
    "The higher the ACV, the bigger and more complex the customer, the more org they need. The lower the ACV, the more I can actually do it, but the less money there is. The two blades of these scissors are joined together. I try to save my margin by raising the price, and the instant I raise it, the customer starts demanding the one thing I can't give.",
    "That narrow band in the middle — ACV high enough to make money, simple enough for one person to deliver — is so thin it barely exists.",
    "---",
    "What sent a chill down my back wasn't \"freight forwarding doesn't work.\" It was something else.",
    "In The Ignored Continent I said big tech can't get in, because they'd never send a team for a thirty-person logistics company. I treated that as the opportunity.",
    "But now I get it: the reason it isn't worth a team for big tech is the same reason it isn't worth my people either — this company can't afford FDE labor.",
    "That gap is empty not because everyone else is stupid. It's empty because \"delivery by humans\" doesn't close the math at either end. I saw the gold. I just never put a price on the scissors that were locking it up.",
    "---",
    "I sat with it for a long time and almost gave up. But one thing saves this — and only one.",
    "These scissors only cut when delivery runs on people.",
    "The moment what I distill out of a company turns into software that runs on its own, without me — both blades open at once.",
    "Low ACV becomes profitable: marginal cost approaches zero, and I can carry an entire long tail.",
    "High ACV becomes serviceable: what carries the complexity is the product, not my body sitting in a chair.",
    "Software is the only thing that can touch both blades of the scissors at the same time.",
    "---",
    "I used to hold up Palantir as the model FDE. But Palantir never made its money from FDE. It made it from Foundry.",
    "FDE is the land — the act of walking in. The product is the business. The FDE labor is subsidized by the product's margin, and in the end it gets replaced by the product.",
    "My mistake was treating \"walking in\" as the business itself. The scissors are the punishment for that confusion.",
    "---",
    "Honestly, these past few weeks I argued with myself round after round.",
    "I said, AI parsing of shipping instructions — that's a moat, right? No. Anyone who wires up a model can copy it in a week.",
    "Okay, the two-sided parsing of a whole reconciliation email? Also copyable. And right now it still gets things wrong all the time.",
    "Fine, then I just take over the work entirely and run it for the customer (OPC)? The trust won't hold. When something breaks, who pays for it.",
    "Then volume? The ACV is twenty thousand. Capped.",
    "Then replicate to competitor number two, number three? Every single one makes you re-learn the whole workflow from scratch. It doesn't save you anything.",
    "And now, another pair of scissors.",
    "Five different angles, all slamming into the same wall. And the wall is one sentence: can the knowledge I distill out of a company become software that delivers itself — and gets more accurate the more it's used.",
    "---",
    "And then I have to admit the most embarrassing thing.",
    "In HA7CH Is a FDE Accelerator I wrote the sexiest line of all: every traditional company can be distilled exactly once, and after that all the knowledge lives inside this AI system, so it's very hard for anyone to re-distill, and the boss won't want to switch.",
    "That line — I've never verified it. Not once.",
    "The product I built does quietly record every human correction: what the AI filled in, what the human changed it to in the end, stored in the database pair by pair. That's the hardest half of distillation, and I built it.",
    "But the other half — feeding those corrections back so it gets better next time, so it actually gets thicker the more it's used — I haven't written a single line of. That table only takes in. Nothing comes out.",
    "The load-bearing brick of my whole theory — I laid half of it, and I've never once put weight on it to see if it holds.",
    "---",
    "So I've decided to stop.",
    "Stop writing theory. Stop finding new reasons it won't work — I've already found five, and every one of them ends at the same wall I've never pressed on.",
    "No argument, however clever, will pry those scissors open. Only one thing will: build the other half of that wall, and put weight on it once.",
    "This takes a week to settle. I feed back those \"AI got it wrong, human got it right\" pairs, and I watch whether — for the same customer, the same overseas agent's invoices — the human correction rate stays flat, or bends down.",
    "If it stays flat — then I'll accept it. This is a service business capped by the scissors. It can earn a few people their first bucket of gold, but it isn't the thing I wanted. Accepting it early is worth more than accepting it late.",
    "If it bends down — then the scissors are pried open. And the ignored continent is real again.",
    "---",
    "When I wrote MVP as Research, I said: drop the food on the ground first and see if anyone eats it. If someone eats it, then you give them a plate.",
    "Freight forwarding is the food I dropped on the ground. Someone took a bite. The research has come back now — it's not that no one's hungry. It's that there's a pair of scissors on this patch of ground.",
    "I'm not going to argue my way onto that continent with my mouth anymore. I'm going to walk over, put weight on that wall, and find out whether it holds.",
    "That's it.",
  ],
};

export default article;
