import type { Article } from "./types";

const article: Article = {
  slug: "stop-saying-jiushi",
  titleZh: "不要再说“就是”",
  titleEn: 'Stop Saying "Jiushi"',
  date: "2026-05-17",
  dateDisplay: "May 17",
  zh: [
    "这不是一篇特别“干货”的文章。更像是一篇语言上的小警报，也是一点 AI 时代的生活感想。最近越来越强烈地觉得，有一个词，真的应该少说，最好能有意识地戒掉。这个词就是“就是”。",
    "中文里的“就是”当然不是原罪。它有很多正常用法，有时候只是一个普通的系词，有时候只是口语里的连接词，有时候甚至只是人在思考时顺手垫一下的语气。问题不在这个词本身，而在于它常常被我们用来偷跑。很多时候，一个“就是”出来，后面的思考其实就已经被它提前封口了。",
    "最常见的场景，不是解释，而是反问。比如，“你不就是这个意思吗？”“这不就是在逃避吗？”“那不就是说明你根本不想吗？”这种说法表面上像在讨论，实际上已经把结论塞进了问题里。它不是在打开理解，而是在设定默认值。它不是在邀请对方一起想，而是在替对方把话说死。很多人说话之所以让人觉得有压迫感，不是因为语气有多凶，而是因为这种“我已经替你总结完了”的姿态来得太快。",
    "这一点，和 AI 相处久了之后，反而会看得更明显。一个正常被调教过的模型，通常不会那么急着反问，也不会上来就把一句“你不就是……”扣在人头上。它更常做的事情，是先试图理解上下文，先辨认歧义，先给出几种可能的解释，然后再慢慢收束。很多时候，它甚至笨拙得有点过头，会反复确认：我理解得对不对？是不是这个意思？虽然这种谨慎有时让人觉得啰嗦，但它至少说明了一件事：真正的理解，不该建立在默认值上，而该建立在空间上。",
    "“就是”最危险的地方，不在于粗鲁，也不在于口语化，而在于它特别容易制造一种“我已经想清楚了”的幻觉。尤其是在中文里，这个词太顺手了。顺手到很多时候，脑子还没真正转过去，嘴已经先替自己下了定义。看上去像表达流畅，实际上是在跳步。原本还值得再想一层的问题，原本还可以再问一句的地方，原本还没有真正厘清的关系，一旦被一个“就是”盖过去，后面往往就不会再继续展开了。",
    "这也是为什么我最近开始对这个词特别敏感。因为模型思考是需要时间的。今天的 AI 虽然已经越来越快，越来越会模拟那种“我懂了”的感觉，但真正像样一点的推理依然需要上下文，需要辨义，需要把几种可能性放在一起比一比。人其实也一样。可现实里，很多人一开口就是“就是”，好像一秒钟之内就已经完成了理解、判断、归纳和定性。可哪里有那么快。很多所谓的“就是”，不是思考完成后的表达，而是思考还没开始时的捷径。",
    "所以我最近有一点想认真戒掉这个词。不是因为它低级，也不是因为它不够优雅，而是因为一旦少说一点，才会发现，很多时候自己其实并没有想到那个地步。那个“就是”原本想跳过去的地方，恰恰是最值得停一停的地方。为什么会这样理解？有没有别的可能？是不是把一个模糊的问题讲得太满了？是不是把一个本来还可以继续追问的东西，提前封口了？",
    "某种意义上，戒掉“就是”，不是在训练措辞，而是在训练一种更诚实的思考方式。它逼着人承认：这里我可能还没懂，这里我还需要再想一下，这里不能那么快地下结论。这种停顿感，在现在这个时代反而显得越来越重要。因为 AI 的上下文逻辑已经很清楚了，它很擅长整理信息、梳理结构、摊开几种可能性。我们如果还保留一点比机器更像样的优势，未必是在速度上，也未必是在“更聪明”上，而更可能是在理解上。",
    "这里说的理解，不只是“知道”一个东西，而是真实地进入它，承认它可能比自己第一反应更复杂，承认自己可能没有一下子抓到重点，也愿意给人与人之间的讨论留一点空间。理解也不是一种高高在上的共情姿态，而是一种相当朴素的能力：知道自己有局限，愿意追问，愿意让一个问题在自己这里多停留一会儿，而不是急着抢答。",
    "我原本想把这件事和 Andrej Karpathy 联系起来，但更准确的说法应该是，Karpathy 在近年的公开讨论里，反复会把人的 taste、judgment、understanding 往前推，而不是简单给出一句“人类唯一的护城河就是理解”的口号。更稳妥地说，AI 越强，人的判断、品味和理解力就越重要。我很认同这个方向。因为 AI 当然已经能“思考一分钟再回答”，也已经能模拟谨慎、模拟推理、模拟反思，但它不总能真的意识到自己哪里没懂。人至少还有一个能力，是可以在某个瞬间认真承认：这里我可能理解错了，这里我还没想透，我得再问一句，我得再学一点。这个动作本身，就已经很厉害了。",
    "所以到最后，我想说的其实不是语言洁癖，也不是要把“就是”从中文里彻底删掉。我只是越来越觉得，一个人怎么用“就是”，其实会暴露很多东西。暴露他是不是太急着下判断，太急着替别人总结，太急着把复杂的东西简化成一个现成的默认值。也暴露他有没有给理解留空间，有没有给思考留时间，有没有意识到自己可能还没到那个地步。",
    "如果说 AI 时代还给人留了什么像样的功课，我猜其中一个就是这个：不要把自己活成一台只会抢答的机器。少一点“这不就是”，多一点“我再想想”；少一点默认值，多一点真的理解；少一点急着定性，多一点愿意追问。",
    "先从少说一句“就是”开始，也许是个不坏的练习。不是因为这个词有罪，而是因为很多时候，它来得太快了。而理解这件事，本来就不该那么快。",
  ],
  en: [
    'This is not exactly a "practical tips" essay. It is more like a small language alarm, and also a bit of life thinking from the AI era. Lately I have felt more and more strongly that there is one word we should probably say less. Ideally, we should consciously try to quit it. That word is "jiushi."',
    'Of course, "jiushi" in Chinese is not some original sin. It has many normal uses. Sometimes it is just an ordinary copula. Sometimes it is just a spoken connector. Sometimes it is even just a filler sound people reach for while thinking. The problem is not the word itself. The problem is that we often use it to skip ahead. A lot of the time, once a "jiushi" comes out, the thinking that should follow has already been sealed off in advance.',
    'The most common scene is not explanation, but rhetorical questioning. For example: "Isn\'t that what you mean?" "Isn\'t this just avoidance?" "Doesn\'t that just show you do not really want it?" On the surface, this sounds like discussion. In reality, the conclusion has already been stuffed into the question. It is not opening understanding. It is setting the default. It is not inviting the other person to think together. It is speaking the other person\'s meaning to death. A lot of people feel oppressive in conversation not because their tone is especially fierce, but because this posture of "I have already summarized you" arrives too quickly.',
    "After spending a long time with AI, this actually becomes easier to see. A reasonably tuned model usually will not rush into a rhetorical question like that, and it usually will not slap a sentence like \"aren't you just...\" onto someone's head right away. What it does more often is first try to understand the context, first identify ambiguity, first offer several possible interpretations, and then slowly narrow them down. A lot of the time, it is even clumsy in how much it confirms: am I understanding this correctly? Is this what you mean? That kind of caution can feel verbose, but at least it shows one thing: real understanding should not be built on defaults. It should be built on space.",
    'The most dangerous thing about "jiushi" is not that it is rude, and not that it is too colloquial. It is that it can so easily create the illusion of "I have already figured this out." Especially in Chinese, the word is too convenient. So convenient that a lot of the time, before the mind has really turned the corner, the mouth has already defined things on its behalf. It looks fluent. In reality, it is skipping steps. A question that was still worth thinking through one more layer, a place where one more question could still be asked, a relationship that had not yet been truly clarified: once a "jiushi" covers it over, what follows often stops unfolding.',
    'That is also why I have recently become especially sensitive to this word. Model thinking takes time. AI today is already faster and faster, and better and better at simulating the feeling of "I get it." But any reasoning that is halfway decent still needs context, still needs disambiguation, still needs to put several possibilities next to each other and compare them. People are actually the same. But in real life, many people open their mouths with "jiushi," as if within one second they have already completed understanding, judgment, summarization, and classification. But how could it be that fast? Many so-called "jiushi" moments are not expressions after thinking has finished. They are shortcuts before thinking has begun.',
    'So lately I have been somewhat serious about quitting this word. Not because it is low-class, and not because it lacks elegance, but because once you say it a little less, you realize that many times you actually had not thought that far. The place that "jiushi" wanted to jump over is exactly the place most worth pausing. Why do I understand it this way? Is there another possibility? Am I stating a vague problem too fully? Am I sealing off something that could still be questioned further?',
    'In a sense, quitting "jiushi" is not training diction. It is training a more honest way of thinking. It forces a person to admit: I may not understand this yet. I may still need to think about this. I cannot reach a conclusion that quickly. This sense of pause feels more and more important in this era. AI is already very clear in its contextual logic. It is good at organizing information, sorting out structure, and laying out several possibilities. If we still keep some advantage that is more decent than the machine\'s, it may not be speed, and it may not be being "smarter." It may be understanding.',
    'The understanding I mean here is not just "knowing" something. It is really entering into it, admitting that it may be more complicated than your first reaction, admitting that you may not have grasped the point immediately, and being willing to leave some room in discussion between people. Understanding is not some lofty posture of empathy, either. It is a very plain ability: knowing that you have limits, being willing to ask further, being willing to let a question stay with you for a little longer instead of rushing to answer first.',
    'I originally wanted to connect this to Andrej Karpathy, but the more accurate version is that in his public discussions in recent years, Karpathy has repeatedly pushed human taste, judgment, and understanding to the front, rather than simply offering the slogan "the only moat humans have is understanding." A steadier way to put it is: the stronger AI becomes, the more important human judgment, taste, and understanding become. I agree with that direction. Because AI can already "think for a minute before answering." It can already simulate caution, simulate reasoning, and simulate reflection. But it cannot always truly notice where it does not understand. Humans at least still have one ability: in a certain moment, to honestly admit that I may have misunderstood this, I have not thought this through, I need to ask one more question, I need to learn a little more. That action itself is already powerful.',
    'So in the end, what I want to say is not language purism, and it is not that "jiushi" should be deleted from Chinese entirely. I just increasingly feel that the way a person uses "jiushi" reveals many things. It reveals whether they are too eager to judge, too eager to summarize other people, too eager to simplify something complex into a ready-made default. It also reveals whether they leave room for understanding, whether they leave time for thinking, and whether they realize that they may not have arrived there yet.',
    'If the AI era still leaves humans with any decent homework, I suspect one piece of it is this: do not live yourself into a machine that only knows how to buzz in first. A little less "isn\'t this just," a little more "let me think again"; fewer defaults, more real understanding; less rushing to define, more willingness to ask.',
    'Start by saying one less "jiushi." Maybe that is not a bad exercise. Not because the word is guilty, but because a lot of the time, it arrives too fast. And understanding was never supposed to be that fast.',
  ],
};

export default article;
