import type { Article } from "./types";

const article: Article = {
  slug: "the-ignored-continent",
  titleZh: "被忽略的大陆",
  titleEn: "The Ignored Continent",
  date: "2026-05-20",
  dateDisplay: "May 20",
  zh: [
    "事情是这样的。",
    "我的朋友 Lawted 前段时间见了一个做传统制造运输的老板。聊完业务以后，他随手帮老板在手机上装了一个豆包。",
    "老板打开，试了试。看脸，算命，聊天。",
    "然后老板说了一句，「卧槽，这他妈太屌了。」",
    "这个老板，公司年营收过千万，手底下几十号人。但他从来没用过任何 AI 产品。他不知道什么是 ChatGPT，不知道什么是 Claude，不知道什么是 prompt。他的全部业务靠微信群协调、Excel 流转、人力堆砌。",
    "他用豆包干什么呢？",
    "看脸算命。",
    "而且不是试一次就放下了。是每天都在用。完全上瘾了，跟着了魔似的，真的很夸张。",
    "我当时听完这个事儿，愣了好一会儿。",
    "不是觉得好笑。是突然意识到一件事，我们这些天天泡在 AI 圈子里的人，和这些真正在用人力堆业务的老板，真的活在两个完全不同的世界里。",
    "我们在讨论 Harness Engineering，在讨论多 Agent 编排，在讨论 Codex 和 Claude Code 到底谁更能打。Codex 上了移动端有人觉得方便有人嫌它慢。我们每天的信息流里全是这些东西。",
    "但在我们视线之外，有一整片我们根本看不见的大陆。",
    "那片大陆上，一个年入千万的老板，第一次见到 AI，是被一个看脸算命的 APP 震撼到说不出话。",
    "你想想这个画面。",
    "这不是一个段子。这是一个信号。一个巨大的、几乎所有人都忽视了的信号。",
    "---",
    "说真的，我之前一直以为 AI 的市场在互联网公司里，在大厂里，在那些已经很懂技术的团队里。我觉得 AI 落地嘛，就是给已经会用 AI 的人做更好的工具，做更强的 agent，做更丝滑的工作流。",
    "但自从我们开始做 HA7CH，真的去接触传统行业以后，我的想法被彻底改变了。",
    "最大的市场根本不在那里。",
    "最大的市场，在中国每一条你看不见的产业带上。",
    "就拿那个老板做的船单物流来说。光深圳一个城市，做这行的公司就有 8000 多家。",
    "8000 多家。",
    "而且这些公司之间，工作流几乎大同小异。都是微信接单，Excel 做单，PDF 传文件，人工核对，人工录入，人工催款，人工跟踪。一个公司里面可能有二三十个人，每天在做的事情就是从一个系统搬到另一个系统，从一个表格搬到另一个表格，从微信群里的一句话搬到 Excel 里的一个格子。",
    "老板说的是一套，员工做的是另一套。系统里写的是一套，真实操作又是一套。很多关键的规则不在任何文档里，而是在某个干了十几年的老员工脑子里。很多信息不是结构化数据，而是微信群里的一句语音、PDF 里的一行小字、Excel 备注栏里的一个缩写。",
    "这还只是一个行业，一个城市。",
    "你把这个数字乘以全国，乘以所有传统行业。物流、教育、制造、贸易、货代、建材、餐饮供应链。你会得到一个让人头皮发麻的数字。",
    "而这些公司的老板，绝大多数都不刷即刻，不关注 AI 新闻，不知道 ChatGPT 和豆包有什么区别。他们唯一知道的事情是，我每个月在人力上花一大笔钱，我很头疼，我想降本增效，但我不知道该找谁。",
    "这才是 AI 真正的 PMF。",
    "不是让已经会用 AI 的人用得更好。而是让从没见过 AI 的人，第一次见到就炸裂。",
    "---",
    "可能有小伙伴纳闷，这么大的市场，为什么大厂不做？为什么没有人去吃？",
    "坦率的讲，不是不想做，是做不了。",
    "大厂做 FDE，比如 Palantir、OpenAI、Anthropic，背后是成熟的平台产品，是 Foundry、是 Claude 企业版、是整套交付体系。他们面对的是世界 500 强，是动不动几百万几千万预算的大客户。他们不可能为了一个三四十人的物流公司、一个本地教育机构、一个传统小工厂，专门派一个团队去做深度定制。",
    "国内的 MiniMax、智谱也是类似的逻辑。企业客户要的不是「我跟 AI 聊两句」，企业要的是模型能进内网、能接现有系统、能处理具体业务场景。这些事情的交付成本很高，大模型公司的 FDE 只能优先服务大客户。",
    "VC 也不投这种生意。太散了，太脏了，太不标准化了，讲不出什么指数增长的故事。",
    "但问题是，机会恰恰就藏在这种地方。",
    "越土、越乱、越靠人堆，才越有 AI 改造的空间。",
    "传统外包公司也不好做这个事儿。外包沟通成本高、交付周期长、报价也不低，最后做出来还经常不好用。而且外包是按功能收费的，你要什么我做什么。但这些传统企业的问题不是「我要一个功能」，而是「我整个流程都是乱的，我自己都说不清我需要什么」。",
    "这就是那个缝隙。大厂进不来，外包做不好，老板自己搞不定。",
    "而 HA7CH 要做的，就是钻进这个缝隙里。",
    "---",
    "回到那个装豆包的故事。那个老板被一个看脸算命的 APP 震撼到不行，但他真正需要的不是算命。他需要的是有人帮他把那些每天重复的、靠人堆出来的流程，用 AI 重新写一遍。",
    "他需要的是，一个带着 MacBook 和 Claude Code 200 刀套餐的年轻人，走进他的公司，坐在他员工旁边，看他们每天到底怎么干活。然后用两三个月时间，把那些最痛的流程做成一个能跑的系统。",
    "这个人，就是 FDE。Forward Deployed Engineer，前沿部署工程师。",
    "但我们这种 FDE，跟大厂的不一样。",
    "大厂 FDE 背后是一个巨大的模型平台。我们这种 FDE 背后可能就是一个 MacBook、一个 Claude Code 200 刀套餐、几个 API、一个微信群，和一个敢走进企业现场的人。",
    "听起来很土。",
    "但也正因为土，所以它能进入那些大厂进不去的地方。",
    "而且现在为什么这事能成立？因为 AI coding 工具真的把个体的交付能力放大了太多。以前一个企业小系统，需要一个小团队做两三个月。现在一个足够强的 builder，用 Claude Code、Cursor、Codex 这些工具，可能两周就能跑出一个 MVP。以前你要同时 handle 五六个项目基本不可能，现在如果方法对，真的可以做到。",
    "这件事把「企业解决方案」从一个组织能力，变成了一个强个体能力。",
    "---",
    "这也是为什么我们说 HA7CH 不是外包公司，不是培训班，也不是创业社群。",
    "HA7CH 是一个 FDE 加速器。",
    "我们把 AI-native 的 builder 送到传统企业现场。白天去访谈业务员，看他们怎么工作，怎么填表，怎么对单，怎么复制粘贴，怎么在微信和 Excel 之间来回切。晚上回去 coding，把今天看到的东西写成系统。第二天再拿回现场，让业务员试。",
    "不对就改。对了就继续往下推。",
    "老板按「省了多少人」付钱，不按「用了什么技术」付钱。",
    "这个逻辑非常简单，也非常真实。一个公司如果有 10 个运营，每人月薪 8000，一年就是接近 100 万的人力成本。如果你的系统能帮他把 10 个人的活变成 3 到 5 个人就能做，收他节省成本的 10% 到 20%，收个 10 万、20 万，一点都不夸张。",
    "而且更关键的一点是，这个系统不是只能卖给一家。同一个行业里，工作流大同小异。做完第一家，你拿着案例去找同行，不用再重新讲什么 AI 未来。你直接说，某某公司已经用了，原来多少人做这个流程，现在省了多少人，原来一天处理多少单，现在一天能处理多少单。",
    "第一家是样板间。后面的，是可以复制的行业产品。",
    "如果第一个老板够聪明，他甚至可能直接变成你的天使投资人。因为他很清楚，你这个系统只要好用，不可能只卖给他一家。你一定会卖给他的同行。那他就会想，我能不能先占一个坑。",
    "这才是 FDE 真正性感的地方。",
    "你一开始看起来像是在免费干活，像是在做外包。但如果你选对行业，选对第一个客户，选对那个可以复制的工作流，它后面就完全不是外包。它会变成一个 SaaS。甚至变成一个行业级的 AI 系统。",
    "---",
    "说到这个，可能有人会问，你们到底想找什么样的人。",
    "我直说了。两个特征，缺一不可。",
    "有能力，有时间。",
    "先说能力。你要会 build。你不一定是最强的工程师，但你一定要能把东西从 0 做出来。你知道怎么用 Claude Code、Cursor、Codex 这些工具，怎么快速搭系统，怎么接 API，怎么做页面，怎么部署。如果你平时就在用 vibe coding 做各种小项目，那你大概率已经具备基础能力了。",
    "再说时间。这一点非常关键。FDE 不是远程写代码的活儿。你要真的去现场，去公司，去办公室，甚至去仓库，站在一线员工旁边看他们怎么干活。你要能跟老板聊，也要能跟业务员聊。你要能听懂他们讲的那些很土的行话。这需要至少连续几周到两三个月的投入。",
    "所以我是真的觉得，大学生是一个非常适合的群体。",
    "不是说只要大学生。如果你是自由职业者、离职程序员、gap year 的人，只要满足上面两个条件，都可以。但大学生有几个天然的优势，是其他群体很难具备的。",
    "有时间。寒暑假两三个月，刚好可以驻场做一单。",
    "有冲劲。还没有被大厂流程驯化，愿意试、愿意跑、愿意把自己扔到一个陌生的行业里。",
    "而且最关键的是，这一代学生已经天然会用 AI 工具了。他们知道怎么用 Claude Code，怎么用 Cursor，怎么提 issue，怎么发 PR，怎么快速 fork 一个东西再改出来。",
    "你想想看，一个大二的学生，暑假两个月，帮一家物流公司做了一套系统。这套系统后来卖给了同行的第二家、第三家公司。他每个月还能从里面拿到一些分成。这些钱可能帮他 cover 生活费，帮他买设备，帮他做下一个项目。",
    "这个感觉和打工是完全不一样的。它会让你第一次感受到，我做出来的东西，真的可以在真实世界里赚钱。",
    "不是工资。是你自己创造出来的现金流。",
    "这种体验，学校教不了，大厂实习也不一定教你。你在学校里学十门课，都不如你真的去一个公司现场，看一个老板怎么赚钱，看一个业务员怎么干活，看一个系统怎么从 0 到 1 跑起来。你会同时学到产品、工程、销售、交付、商业、行业、人性。",
    "这才是最好的学习。",
    "---",
    "当然，我也不想把这件事说得太美好。坦率的讲，做 FDE 很苦。",
    "你没有工位，没有正经的工作环境，办公室里可能所有人都在抽烟。老板可能给你端茶倒水，也可能要你陪酒。你做的第一单大概率是交付以后才给钱，甚至一分钱定金都没有。你可能贴时间进去，可能天天去现场，可能晚上写代码写到 12 点。",
    "而且你面对的不是标准化的需求。真实业务不是 PRD 里写好的。老板不会给你写 user story。员工也不会告诉你完整流程。你要自己看，自己问，自己拆，自己判断。你会遇到一堆乱七八糟的字段，一堆历史包袱，一堆「这个客户比较特殊」的情况。",
    "这不是每个人都能干的事。",
    "但如果你能干，而且你敢干，回报也是很真实的。",
    "因为在传统行业里，你会突然变成一个很稀缺的人。你跟他们说 AI 可以帮他们对单、整理表格、自动生成文件、分析客户数据、把每天复制粘贴的活儿接走，他们真的会觉得，我操，这个人有点东西。",
    "在大厂里你可能只是一个普通工程师。在 Stanford 你可能只是一个普通研究助理。但你到了一个真正缺 AI、缺自动化、缺技术理解的传统行业里，你突然就会变成一个很关键的人。",
    "技术这东西，放在不同的地方，价值完全不一样。",
    "---",
    "我自己也不确定 HA7CH 这件事最后能走到哪里。也许几个月后发现某些假设是错的，也许 Hatch House 是个伪命题，也许商业模式需要大调整。这些都有可能。",
    "但有一件事我们是确定的。",
    "那片被忽略的大陆，是真实存在的。",
    "那些从没见过 AI 的老板，是真的需要有人走进去的。",
    "那些靠人力堆出来的工作流，是真的在等着被重写一遍的。",
    "而每一个公司，有且只能被 AI 化一次。先进去的人，就拥有了那个工作流。后面再想蒸馏，就非常困难了。",
    "这个窗口期不会永远存在。大厂 12 个月内会进场，但他们会从大客户做起。中小「土老板」市场，可能还有 12 个月的窗口。",
    "所以回到开头那个故事。",
    "一个年入千万的老板，用豆包看脸算命，觉得太牛逼了。",
    "他不知道 AI 还能帮他做什么。他不知道他每天花在人力上的成本，有一半可以被系统接走。他不知道他的公司正等着被蒸馏。",
    "但我们知道。",
    "而我们要做的，就是找到那些有能力、有时间、敢走进现场的年轻 builder，把他们送到这些老板身边去。",
    "让他们成为走进这些公司的第一个人。",
    "HA7CH，BUILD IN THE FIELD. HATCH INTO IMPACT.",
    "如果你觉得自己就是这种人，或者你想了解更多，来 ha7ch.com 看看。我们第一批 batch 已经在跑了。",
    "我们，下次再见。",
  ],
  en: [
    "Here is what happened.",
    "A while ago, my friend Lawted met a boss who runs a traditional manufacturing and transportation business. After they talked through the business, Lawted casually helped him install DouBao on his phone.",
    "The boss opened it and tried a few things. Face reading, fortune telling, chatting.",
    "Then he said one sentence: “Holy shit, this is fucking insane.”",
    "This boss runs a company with annual revenue in the tens of millions and dozens of people under him. But he had never used any AI product before. He did not know what ChatGPT was, did not know what Claude was, did not know what a prompt was. His entire business runs on WeChat groups, Excel handoffs, and people brute-forcing the workflow.",
    "What did he use DouBao for?",
    "Face reading and fortune telling.",
    "And it was not the kind of thing where he tried it once and put it down. He was using it every day. Completely hooked. Almost possessed. It was honestly wild.",
    "When I heard this story, I sat there stunned for a while.",
    "Not because I thought it was funny. Because I suddenly realized something: those of us soaking in the AI world every day and the bosses actually running businesses on human labor live in two completely different worlds.",
    "We are discussing Harness Engineering, multi-agent orchestration, whether Codex or Claude Code is stronger. Codex ships on mobile and some people think it is convenient while others complain it is slow. Our feeds are full of this stuff every day.",
    "But outside our field of vision, there is an entire continent we cannot see.",
    "On that continent, a boss making tens of millions a year sees AI for the first time through a face-reading app and is stunned speechless.",
    "Just picture that scene.",
    "This is not a joke. It is a signal. A huge signal that almost everyone has ignored.",
    "---",
    "Honestly, I used to think the market for AI was inside internet companies, inside big tech, inside teams that already understand technology. I thought AI deployment meant making better tools, stronger agents, and smoother workflows for people who already knew how to use AI.",
    "But ever since we started doing HA7CH and actually began touching traditional industries, my view has been completely changed.",
    "The largest market is not there at all.",
    "The largest market is on every industrial belt in China that you cannot see.",
    "Take the shipping-doc logistics business that boss is in. In Shenzhen alone, there are more than 8,000 companies doing this line of work.",
    "More than 8,000.",
    "And across these companies, the workflows are almost the same. Orders come in through WeChat, documents are made in Excel, PDFs get passed around, people manually check, manually enter, manually chase payments, manually track progress. A company may have twenty or thirty people whose daily work is basically moving something from one system to another, from one spreadsheet to another, from a sentence in a WeChat group into a cell in Excel.",
    "What the boss says is one thing. What the employees do is another. What is written in the system is one thing. How it actually works is another. Many of the key rules are not in any document. They live inside the head of one old employee who has been there for more than a decade. A lot of the information is not structured data. It is a voice message in a WeChat group, a tiny line in a PDF, an abbreviation in the notes column of an Excel sheet.",
    "And this is just one industry in one city.",
    "Multiply that number across the whole country and across every traditional industry: logistics, education, manufacturing, trade, freight forwarding, building materials, restaurant supply chains. You get a number that makes your scalp go numb.",
    "Most of these bosses do not use Jike, do not follow AI news, do not know the difference between ChatGPT and DouBao. The only thing they know is: I spend a huge amount on labor every month, it gives me a headache, I want to cut costs and boost efficiency, but I do not know who to call.",
    "This is the real PMF for AI.",
    "Not helping people who already know how to use AI use it better. Helping people who have never seen AI see it for the first time and feel their heads explode.",
    "---",
    "Some people may wonder: if the market is this large, why are the big companies not doing it? Why has nobody eaten it?",
    "To be blunt, it is not that they do not want to. It is that they cannot.",
    "When big companies do FDE, companies like Palantir, OpenAI, and Anthropic have mature platforms behind them: Foundry, Claude Enterprise, entire delivery systems. They face Fortune 500 companies and clients with budgets in the millions or tens of millions. They cannot send a dedicated team to deeply customize software for a logistics company with thirty or forty people, a local education business, or a small traditional factory.",
    "Domestic companies like MiniMax and Zhipu follow a similar logic. Enterprise customers do not want “I chat with AI for a bit.” Enterprises want models that can enter the intranet, connect to existing systems, and handle concrete business scenarios. Delivery costs are high, so the FDE teams at model companies can only prioritize large clients.",
    "VCs do not fund this kind of business either. It is too scattered, too dirty, too non-standardized. It does not tell a clean exponential-growth story.",
    "But the problem is, the opportunity is exactly hidden in these places.",
    "The more local, messy, and labor-heavy something is, the more room there is for AI to transform it.",
    "Traditional outsourcing companies do not do this well either. Communication costs are high, delivery cycles are long, pricing is not cheap, and the final product often does not work well. Outsourcing also charges by feature: you tell me what you want, I build it. But these traditional companies do not have the problem “I need a feature.” Their problem is “my entire workflow is chaotic, and I cannot even explain what I need.”",
    "This is the gap. Big companies cannot enter, outsourcing cannot do it well, and the boss cannot figure it out alone.",
    "And what HA7CH wants to do is get inside this gap.",
    "---",
    "Back to the DouBao story. That boss was blown away by a face-reading app, but what he actually needs is not fortune telling. What he needs is someone to help him rewrite all those repetitive, labor-stacked workflows with AI.",
    "What he needs is a young person with a MacBook and a $200 Claude Code plan to walk into his company, sit beside his employees, and watch how they actually work every day. Then, over two or three months, turn the most painful workflows into a system that actually runs.",
    "That person is the FDE: Forward Deployed Engineer.",
    "But our kind of FDE is different from big-company FDE.",
    "Behind a big-company FDE is a massive model platform. Behind our kind of FDE there may just be a MacBook, a $200 Claude Code plan, a few APIs, a WeChat group, and one person brave enough to walk into the company on-site.",
    "It sounds very local.",
    "But precisely because it is local, it can enter places the big companies cannot enter.",
    "And why does this work now? Because AI coding tools have amplified the delivery ability of an individual by too much. In the past, a small enterprise system needed a small team working for two or three months. Now, a sufficiently strong builder using Claude Code, Cursor, Codex, and tools like these may be able to ship an MVP in two weeks. In the past, juggling five or six projects at once was basically impossible. Now, if the method is right, it really can be done.",
    "This turns “enterprise solutions” from an organizational capability into a strong-individual capability.",
    "---",
    "This is also why we say HA7CH is not an outsourcing company, not a bootcamp, and not a startup community.",
    "HA7CH is an FDE accelerator.",
    "We send AI-native builders into traditional companies on-site. During the day, they interview operations people and watch how they work, how they fill forms, how they reconcile orders, how they copy and paste, how they move back and forth between WeChat and Excel. At night, they go back and code what they saw into a system. The next day, they bring it back on-site and let the employees try it.",
    "If it is wrong, they change it. If it is right, they keep pushing forward.",
    "The boss pays based on “how many people did this save,” not based on “what technology did you use.”",
    "This logic is very simple and very real. If a company has 10 operators, each making 8,000 RMB a month, that is nearly 1 million RMB in labor cost a year. If your system can turn the work of 10 people into something 3 to 5 people can handle, charging 10% to 20% of the saved cost, 100,000 or 200,000 RMB is not exaggerated at all.",
    "And the more important point is: this system is not something you can only sell to one company. In the same industry, workflows are largely similar. After you finish the first company, you take the case study to its peers. You do not need to preach the future of AI again. You just say, this company is already using it. This workflow used to take this many people, now it saves this many people. They used to process this many orders per day, now they can process this many.",
    "The first company is the show apartment. The ones after that can become a repeatable industry product.",
    "If the first boss is smart enough, he may even become your angel investor. Because he understands very clearly that if this system works, there is no way you will only sell it to him. You will definitely sell it to his competitors. So he will think: can I get a seat first?",
    "That is the part of FDE that is genuinely sexy.",
    "At the beginning, it may look like you are working for free, like you are doing outsourcing. But if you pick the right industry, the right first customer, and the right repeatable workflow, what comes after is not outsourcing at all. It becomes SaaS. It may even become an industry-level AI system.",
    "---",
    "At this point, some people may ask: what kind of people are you actually looking for?",
    "I will say it directly. Two traits. You need both.",
    "Ability and time.",
    "First, ability. You need to be able to build. You do not have to be the strongest engineer, but you must be able to make something from zero. You know how to use Claude Code, Cursor, Codex, and tools like these; how to quickly set up a system; how to connect APIs; how to build a page; how to deploy. If you are already using vibe coding to make small projects in daily life, you probably already have the basic ability.",
    "Then, time. This is extremely important. FDE is not remote coding work. You have to actually go on-site, to the company, the office, maybe even the warehouse, and stand beside front-line employees watching how they work. You need to be able to talk to the boss and also to the operations people. You need to understand the very local industry language they use. This takes at least several continuous weeks, and sometimes two or three months.",
    "So I genuinely think college students are a very suitable group.",
    "Not only college students. If you are a freelancer, a developer who has left a job, or someone on a gap year, as long as you meet the two conditions above, you can do it. But college students have several natural advantages that are hard for other groups to match.",
    "They have time. A winter or summer break of two or three months is just enough to go on-site and complete one project.",
    "They have momentum. They have not yet been trained by big-company process. They are willing to try, willing to run, willing to throw themselves into an unfamiliar industry.",
    "And most importantly, this generation of students already naturally knows how to use AI tools. They know how to use Claude Code, how to use Cursor, how to open issues, how to send PRs, how to quickly fork something and modify it.",
    "Think about it: a sophomore spends two months in the summer helping a logistics company build a system. That system later sells to the second and third companies in the same industry. Every month, he can still receive some revenue share from it. That money might cover living expenses, buy equipment, fund the next project.",
    "That feeling is completely different from having a job. It lets you feel, for the first time, that something you built can actually make money in the real world.",
    "Not salary. Cash flow you created yourself.",
    "This experience cannot be taught by school, and big-company internships may not teach it either. Taking ten classes in school is not as good as actually going on-site to a company, watching how a boss makes money, how an operations person works, how a system goes from zero to one and starts running. You learn product, engineering, sales, delivery, business, industry, and human nature all at once.",
    "This is the best kind of learning.",
    "---",
    "Of course, I do not want to make this sound too beautiful. To be blunt, doing FDE is hard.",
    "You do not have a proper desk. You do not have a proper work environment. Everyone in the office may be smoking. The boss may pour tea for you, or he may ask you to drink with him. Your first project will probably only be paid after delivery, maybe with not even one yuan of deposit. You may put your own time into it, go on-site every day, and write code until midnight.",
    "And what you face is not standardized requirements. Real business is not written in a PRD. The boss will not write user stories for you. Employees will not tell you the full workflow either. You have to watch, ask, break it down, and judge by yourself. You will run into a mess of fields, historical baggage, and endless cases of “this customer is special.”",
    "This is not something everyone can do.",
    "But if you can do it, and you dare to do it, the return is also very real.",
    "Because in traditional industries, you suddenly become a very scarce person. When you tell them AI can help reconcile orders, organize spreadsheets, automatically generate files, analyze customer data, and take over the daily copy-paste work, they will really think: holy shit, this person has something.",
    "Inside a big company, you may just be an ordinary engineer. At Stanford, you may just be an ordinary research assistant. But when you arrive in a traditional industry that truly lacks AI, automation, and technical understanding, you suddenly become a key person.",
    "Technology has completely different value depending on where you put it.",
    "---",
    "I am not sure where HA7CH will ultimately go. Maybe a few months from now we find out some assumptions were wrong. Maybe Hatch House is a false premise. Maybe the business model needs a major adjustment. All of that is possible.",
    "But there is one thing we are certain about.",
    "That ignored continent is real.",
    "Those bosses who have never seen AI truly need someone to walk in.",
    "Those workflows stacked on human labor are truly waiting to be rewritten.",
    "And every company can only be AI-ified once. Whoever gets in first owns that workflow. Distilling it later becomes extremely difficult.",
    "This window will not stay open forever. Big companies will enter within 12 months, but they will start with large clients. The market of small and mid-sized “local bosses” may still have a 12-month window.",
    "So, back to the opening story.",
    "A boss making tens of millions a year uses DouBao for face reading and fortune telling, and thinks it is incredible.",
    "He does not know what else AI can help him do. He does not know that half of the labor cost he spends every day can be taken over by a system. He does not know that his company is waiting to be distilled.",
    "But we know.",
    "And what we need to do is find those young builders who have ability, have time, and dare to walk into the field, then send them to the side of these bosses.",
    "Let them become the first person to walk into these companies.",
    "HA7CH, BUILD IN THE FIELD. HATCH INTO IMPACT.",
    "If you feel like you are this kind of person, or you want to learn more, come to ha7ch.com. Our first batch is already running.",
    "See you next time.",
  ],
};

export default article;
