import type { Article } from "./types";

const article: Article = {
  slug: "the-frog-in-the-well",
  titleZh: "井底之蛙",
  titleEn: "The Frog in the Well",
  date: "2026-05-13",
  dateDisplay: "May 13",
  zh: [
    "我高中计算机课挂了科。我大学读的是会计。怎么看,我都不该是写这篇东西的人。",
    "但三段实习,三个完全不同的行业,让我看到了大多数软件工程师一辈子都不会看到的东西。",
    "---",
    "我不是从哪篇博客上学会什么叫 FDE 的。我是从三段实习里学会的——在那些地方,我亲眼看着一群聪明人做着蠢事,而他们身边没有一个人意识到那有多蠢。",
    "私募股权公司(2023年):几百个实习生。强大的 CRM、真正优质的线索、桌面上摆着真金白银的钱。工作内容是什么?把同一段模板化的开发信复制粘贴给每一个线索。几百个实习生,每天手动重复着完全一样的动作。",
    "我搭了一条流水线,一键替代了 200 个实习生的工作,而且每封信都做了个性化处理。他们不愿意为这个工具付我钱,搬出我的劳动合同来压我。去他妈的,我走人。",
    "燃油公司,年营收 50 亿美元(2024年)。我是税务会计实习生。我看着两个 CPA(全美最难考的资格证之一的持证人)一个一个手动复制粘贴客户地址,去查税率。这占了他们工作量的 50%。这就是公司花钱请他们干的事。完全是脑死亡的活。他们的专业能力本该用在别的地方,时间却全耗在了这里。一个星期。我自己找到了 shapefile 数据,搭了一条 Python 流水线(几百行代码),搞定。整个公司的燃油税计算,全自动化了。",
    "土木工程公司(2025年)。工程师们盯着 50 年的时间序列数据,试图用眼睛去识别时间模式。用他们的肉眼。每周要花 10 小时。我写了一个解析引擎,用动态时间规整(DTW)算法,几秒钟就把数学意义上的高匹配项给捞出来了。",
    "---",
    "三段实习。三个毫不相干的行业。每次都是同一个故事。我进这些公司都不是以软件工程师的身份。每一次我都是以商科实习生的身份进去的。SWE 实习生根本进不了那些房间。我能看到这些工作流,是因为我就坐在干这些活的人旁边。",
    "这些都不是傻公司。私募股权公司不傻。CPA 不傻。那些土木工程师聪明得很。但所有这些工作流在结构上都是疯狂的。公司里没有一个人看得出来。不是因为他们蠢,而是因为他们是井底之蛙。",
    "井底之蛙。你不知道自己不知道什么。从井底,你看不到天空。你游的那点水,就是你认识的全部的水。",
    "---",
    "这就是现在全世界每一家传统企业里都摆着的东西。不是少数几家。是每一家。某个吞噬着三个、三十个、甚至三百个人脑力的工作流,而一个带着笔记本电脑和正确直觉的人,几个星期就能把它压成一行命令。瓶颈在于:能看见工作流的人看不见 AI,能看见 AI 的人从来不会走进那个房间。",
    "YC 和旧金山现在又亮又花。创始人们推销着下一个 Claude 版本一发布就会被秒杀的套壳产品,在 Twitter 上炫耀自己怎么把 VC 的种子轮骗到手,第七次做同一个傻逼约会软件。泡沫是真的。这些公司里很多撑不了多久。",
    "与此同时,西雅图郊外有家物流公司,年营收 8000 万美元,整个调度系统跑在一个叫 Dave 的人 2011 年搭的 Excel 表上。Dave 2019 年退休了。没人知道那些公式里有一半是怎么算出来的。去年他们专门请了两个人来伺候这张表。老板听说过 ChatGPT,因为他女儿给他看过。他有真实的营收、真实的利润,以及一个 AI 今天下午就能解决的真实问题。",
    "价值在那儿。不光鲜。不在 Twitter 上。在某个购物广场后面的办公室里,荧光灯,会卡纸的打印机,白板上还写着上个季度的数字。一个跑了三十年、全靠人脑撑着的工作流,等着一个人走进来看见它。",
    "---",
    "能干这活的人,不是普通的软件工程师。传统 SWE 想要的是工单、需求文档、code review、staging 环境。这里什么都没有。你两手空空地走进去。工作流住在某个人的脑子里。一半时间老板自己都说不清他的员工到底在干什么。你必须坐在他们旁边,看着。",
    "刚进去的时候你什么都看不懂。你必须学得很快,不然就完蛋。你必须能跟那些跟你完全不是一类人的人说上话——那些觉得 AI 是魔法、是骗局、或者两者皆是的人。老板说错的时候你得有分寸,但该顶回去的时候你还得顶回去。你必须在星期二交付一个你星期一根本不知道它存在的东西。",
    "你写出来的东西不会有任何文档。没法直接丢给 Claude Code 让它自己写出来。数据库结构在某人的笔记本里。业务逻辑在某个员工的脑子里。边角情况躺在 2020 年的某个 Teams 聊天记录里。你必须把它们挖出来,理清楚,然后交付。",
    "---",
    "这不是每个人都能干的活。",
    "但如果你能干(也许那个人就是你),现在有一扇我们从来没见过的窗口。每一家传统公司只会被蒸馏一次。谁先把它做了,谁就拿下那个工作流。这样的公司有几百万家。",
    "我是误打误撞学会这件事的。一个会计学位、三段实习,加上一种看见太蠢的人工活就忍不住想搞清楚、把东西造出来的习惯。能在 HA7CH 干得好的人,大概也都是这么学会的——从一个他们本不该出现的地方学会的。",
    "---",
    "井底之蛙不知道那口井是一口井。",
    "我们去造他妈的梯子吧",
  ],
  en: [
   "I failed Computer Science in high school. I'm studying accounting in college. I am, by every reasonable measure, not the person who should be writing this.",
    "But three internships in three industries taught me something most software engineers will never see.",
    "---",
    "I didn't learn what FDE meant from a blog post. I learned it from three internships where I watched smart people do stupid things, and nobody around them knew it was stupid.",
    "Private equity firm (2023): Hundreds of interns. Powerful CRM, genuinely good leads, real money on the table. The job: copy-paste the same boilerplate outreach message to every lead. Hundreds of interns, all doing the exact same thing, by hand, every day.",
    "I built a pipeline that replaced the work of 200 interns and personalized every message at the click of a button. They didn't want to pay me for the tool. Cited my work contract. Hell nah, I left.",
    "Fuel company, $5B in revenue (2024). I was a tax accounting intern. I watched two CPAs (people who passed one of the most rigorous certifications in the country) manually copy-paste customer addresses, one by one, to look up tax rates. This was 50 percent of their job. This is what the company pays them to do. Mindless. Their specialization is needed elsewhere but their time is soaked up here. One week. I find my own shapefiles, build a Python pipeline (a few hundred lines of code), done. Whole company's fuel tax calculations, automated.",
    "Civil engineering firm (2025). Engineers eyeballing 50 years of time series data, trying to pattern-match temporal sequences visually. With their eyes. Took them 10 hours per week. I built a parsing engine with dynamic time warping that surfaced mathematically high-tier matches in seconds.",
    "---",
    "Three internships. Three industries that have nothing to do with each other. Same story every time. I wasn't in any of these companies as a software engineer. I entered each of these companies as a business intern. A SWE intern would never have been in those rooms. The reason I saw these workflows is that I was sitting next to the people doing them.",
    "These weren't dumb companies. PE firms aren't dumb. CPAs aren't dumb. These civil engineers were incredibly smart. And yet all of these workflows were structurally insane. Nobody on the inside saw it. Not because they were stupid. Because they were the frog at the bottom of the well.",
    "井底之蛙. You don't know what you don't know. You can't see the sky from down there. The water you swim in is the only water there is.",
    "---",
    "This is what's sitting in every traditional company in the world right now. Not a few. Every single one. Some workflow that absorbs the brainpower of three people, or thirty, or three hundred, that one person with a laptop and the right instinct could collapse in a few weeks. The bottleneck is that the people who can see the workflow can't see the AI, and the people who can see the AI never walk into the room.",
    "YC and SF are bright and flashy right now. Founders pitching wrappers that will be murdered in the next Claude release, bragging on Twitter how they're going to scam VCs out of a seed round, building the same stupid dating app for the seventh time. The bubble is real. Many of those companies will not exist for long.",
    "Meanwhile, there's a logistics company outside Seattle doing $80M a year, running dispatch out of a spreadsheet a guy named Dave built in 2011. Dave retired in 2019. Nobody knows how half the formulas work. They hired two people last year just to babysit the file. The owner has heard of ChatGPT because his daughter showed him. He has real revenue, real margin, and a real problem that AI can solve this afternoon.",
    "That's where the value is. Not glamorous. Not on Twitter. A back office in a strip mall, fluorescent lights, a printer that jams, a whiteboard with last quarter's numbers still on it. Just a workflow that's been running on human brainpower for thirty years, waiting for one person to walk in and see it.",
    "---",
    "The people who can do this are not normal software engineers. A traditional SWE wants a ticket, a spec, a code review, a staging environment. None of that exists here. You walk in with nothing. The workflow lives in someone's head. Half the time the boss can't even tell you what his employees do. You have to sit next to them and watch.",
    "You will not understand anything going in. You have to learn fast or you're cooked. You have to be able to talk to people who are nothing like you, who think AI is magic or a scam or both. You have to have tact when the boss is wrong, and you have to know when to push anyway. You have to ship something on Tuesday that you didn't understand existed on Monday.",
    "The things you build will have no documentation. There is no way to paste it into Claude Code and have it write itself. The schema is in someone's notebook. The business logic is in an employee's head. The edge cases live in a Teams chat from 2020. You have to dig it out, structure it, and ship.",
    "---",
    "This is not for everyone.",
    "But if you can do it (and maybe that person is you) there is a window right now that we've never seen before. Every traditional company gets distilled exactly once. Whoever does it first owns that workflow. And there are millions of these companies.",
    "I learned this by accident. Starting from an accounting degree, three internships, and a habit of figuring shit out and building the thing when I see something too stupid to be done manually. Most of the people who'll thrive at HA7CH probably learned it the same way- from somewhere they weren't supposed to be.",
    "---",
    "The frog at the bottom of the well doesn't know the well is a well.",
    "Let's go build some fucking ladders",
  ],
};

export default article;
