import type { Article } from "./types";

const article: Article = {
  slug: "three-hundred-strangers",
  titleZh: "三百个陌生人",
  titleEn: "Three Hundred Strangers",
  date: "2026-05-20",
  dateDisplay: "May 20",
  zh: [
    "我在超市的时候，Lawted 给我发消息：'哥你看看这个小红书的群聊。'",
    "他几个小时前刚放出了 Raily 的原型。等我点开链接的时候，群里已经三百人了。功能建议。Bug 反馈。截图。有人在问安卓版什么时候出。",
    "这群里没有一个人是被谁的爸爸介绍进来的。没有谁欠谁人情。十年前他们根本不可能聚在同一个房间。入场费就是——这个东西存在，而且值得围观。",
    "这个房间能存在本身，就意味着一个时代的终结。大多数人还没意识到它正在终结。",
    "---",
    "一百年来，人脉一直是这套系统的底层操作系统。你爸认识谁的爸。饭局就是面试。红包就是合同。你没办法从网络外部去验证一个陌生人，所以网络本身就是验证。信息稀缺。资本稀缺。信任稀缺。这三样东西都通过同一套管道流动，而那些管道上都写着名字。",
    "这套系统造就了财富。造就了行业。造就了你父母引以为傲的大部分家底。",
    "它结束了。",
    "信息不再稀缺。验证一个陌生人只要三十秒。作品就是信号，而且这个信号是公开的。一个在宿舍里发版本的二十二岁年轻人，在真正重要的人眼里，比某某副总裁推荐信里那个简历光鲜的侄子要清晰得多。",
    "资本不再稀缺。Raily 的全部成本就是 Lawted 几个失眠的晚上。仅此而已。建造昂贵的时代，你需要钱；钱在网络里流动，所以网络才那么重要。亿万富翁的儿子曾经有十英里宽的护城河。今天，一个饥渴的、有台笔记本电脑的工薪阶层小孩，周五之前就能追平。",
    "而真正重要的房间，有了新的门卫。门卫不再是人了。门卫是一个过滤器：你能不能交付，你能不能看见，你值不值得别人花三个小时的晚上。你贿赂不了这个过滤器。你爸打电话也没用。作品是唯一的密码，而且没有后门。",
    "旧系统卖给你的所有优势——人脉、引荐、家族名号、对的学校、对的公司——都在实时崩塌。大多数还握着这些优势的人，还没意识到他们手里握的只是一张废纸。",
    "---",
    "那句老话说，你是你身边五个人的平均值。所以大家都在优化'进入'——怎么进那个房间。怎么认识对的人。怎么搞到那个引荐。",
    "这是输家的游戏了。",
    "---",
    "旧系统没有完全死。有些行业、有些城市，关系还在主导一切，而且还会再主导一代人的时间。行。让那些继承了那套游戏的人继续玩吧。棋盘在缩小。",
    "每一年，更多的验证搬到线上。每一年，建造的成本继续下降。每一年，更多的房间是围绕作品形成的，而不是围绕血统。方向是单向的，坡度还在变陡。",
    "如果你押注在这个转向上，你是在早期下注。早期是唯一押对的时机。",
    "别再想着挤进哪个房间了。",
    "做点声音够大的东西，让房间自己来找你。",
  ],
  en: [
    "I was at a supermarket when Lawted texted me: 'bro check out this groupchat on 小红书.'",
    "He'd released a prototype of Raily a few hours earlier. By the time I opened the link, three hundred people were already in the chat. Feature requests. Bug reports. Screenshots. Someone asking when the Android version was coming.",
    "Nobody in that chat was introduced by anyone's dad. Nobody owed anyone a favor. None of them would have been in the same room a decade ago. The entry fee was that the thing existed and was worth being around.",
    "The fact that the room exists means the end of an era most people haven't noticed is ending.",
    "---",
    "For a hundred years, 人脉 was the operating system. Your dad knew someone's dad. The dinner was the interview. The red envelope was the contract. You couldn't verify a stranger from outside their network, so the network was the verification. Information was scarce. Capital was scarce. Trust was scarce. All three flowed through the same pipes, and those pipes had names on them.",
    "This system built fortunes. It built industries. It built most of the wealth your parents are proud of.",
    "It's over.",
    "Information isn't scarce anymore. You can verify a stranger in thirty seconds. The work is the signal now, and the signal is public. A twenty-two-year-old shipping from a dorm room is more legible to the people who matter than someone's nephew with a polished résumé and a recommendation letter from a vice president.",
    "Capital isn't scarce anymore. Raily cost Lawted a few sleepless nights. That's the whole budget. When building was expensive you needed money, and money moved through networks, which is why the networks mattered. The son of a billionaire used to have a moat ten miles wide. Today he has nothing a hungry working-class kid with a laptop can't match by Friday.",
    "And the rooms that matter have new bouncers. The bouncer isn't a person anymore. The bouncer is a filter: can you ship, can you see, are you worth three hours of someone's evening. You can't bribe that filter. You can't get your dad to call it. The work is the only password, and there are no backdoors.",
    "Every advantage the old system sold you — access, introductions, the family name, the right school, the right firm — is collapsing in real time. Most of the people holding those advantages haven't realized they're holding nothing but a piece of paper.",
    "---",
    "The cliché says you're the average of the five people you surround yourself with. So everyone optimizes for access. How do I get into the room. How do I meet the right people. How do I get the introduction.",
    "That's the loser's game now.",
    "---",
    "The old system isn't fully dead. There are industries and cities where 关系 still runs everything and will for another generation. Fine. Let the people who inherited that game keep playing it. It's a shrinking board.",
    "Every year more verification moves online. Every year more building gets cheaper. Every year more rooms form around the work instead of around the bloodline. The direction is one-way and the slope is steepening.",
    "If you're betting on this, you're betting early. Early is the only time the bet pays.",
    "Stop trying to climb into rooms.",
    "Build something loud enough that the room comes to you.",
  ],
};

export default article;
