import type { Article } from "./types";

const article: Article = {
  slug: "we-dont-know-what-ha7ch-is-yet",
  titleZh: "我们也他妈不清楚 HA7CH 是什么",
  titleEn: "We Don't Fucking Know What HA7CH Is",
  date: "2026-05-11",
  dateDisplay: "May 11",
  zh: [
    "这两天好多人来问我们 HA7CH 到底是干什么的。其实我们也不知道 HA7CH 是什么，但是我们有一些思考，在这里和大家分享一下。",
    "---",
    "所以我们现在在做什么？",
    "我们一边在运营小红书的群，群里有大概 1000 个人，非常喜欢我们 Raily 这个产品，确实做得也不错，他们每天在那里嘎嘎地提反馈。",
    "另一方面，我们在运营一个微信的 builder 群，群里有一些喜欢 vibe coding、认知比较高的人。大家想一起做一些事情，也认同 HA7CH 的某些观点。",
    "---",
    "先说 Raily。很多人说希望我们收费，但我们其实并不希望收费。我们决定很快就会上线上架，然后在它最火爆的时候直接开源。",
    "因为 Raily 其实没有多少成本，成本就是熬一些夜、一些开发。但是我们得到了什么？得到了一个用户群，得到了反馈，得到了大家的喜爱。这些东西都很重要，比那几十块钱的订阅费重要太多。",
    "我们希望的是造势，拉更多的用户、更多的注意力到我们的产品上。这件事还有另外一个好处：如果我们想出圈、想推下一个产品，builder 群里有人有 idea，他就不用冷启动，我们可以直接把它丢到用户群里去，让真实的用户做反馈。如果喜欢，我们继续做；如果不喜欢，就丢掉，做下一个。",
    "所以 Raily 其实就是我们的第一次 branding，Lawted 的 branding，HA7CH 的 branding。Which is fucking important.",
    "就这样，我们希望吸引到一些志同道合的 builder。这些 builder 会有非常高超的 AI、coding 能力，他们有信念、有想法、有执行力。",
    "这样的人适合做什么呢？适合来做 FDE。",
    "---",
    "FDE 其实就是 Forward Deployed Engineer，直接驻进一家传统行业公司，用 AI 把他们的工作流重写一遍。",
    "为什么是深圳？因为深圳一抓一大把传统行业的土老板，每个老板手里都有一套跑了几十年、用人肉堆出来的工作流。员工在这里干了几十年，脑子里全是隐性的知识：客户怎么谈、价格怎么算、流程怎么走、出问题找谁、每个字段该怎么填、这是什么东西、那是什么黑话。这些东西没文档、没系统，全部都在人的脑子里，或者在 Excel 里。他们的系统大部分都是 Excel、PDF、Word 组成的。",
    "AI 当然可以代替这些东西。我们现在所有人都相信，两年后这些公司将会裁掉很多人。",
    "那为什么这些人会被裁掉？是因为这些土老板突然学会了 vibe coding，自己做了一个系统吗？我并不这么觉得。",
    "我觉得是他妈的有一个人走进这家公司，每天带着一个 Mac，两三个月，帮他们蒸馏、帮他们梳理，最后提高效率，裁掉一波人。",
    "而且我敢赌这里只有一个人。两个人之间会有沟通磨损，反而做不快。还有一个关键的，两三个月绝对可以做完，做不完说明水平不够，赶紧滚蛋。",
    "就这样，我们可以让这批人赚到他们自己的第一笔 real fucking money。这是第一桶金，不是工资，是他自己的创造。",
    "---",
    "那我们的人怎么来到深圳做 FDE 呢？",
    "我们希望在深圳搞一个 Hatch House。你知道深圳的办公室多得一批，赞助、借场地都行，我们也可以直接租一个开 party。把这些 builder 全部聚集在这里，然后帮他们去链接公司。他们每天从 house 出发，去那些公司驻场做事。",
    "我觉得一个暑假可能就够了。",
    "这群 builder 可能之前是学生，可能是大厂里的程序员。我相信，如果他们能进入并通过我们 2C 这一关的验证和考验，他们应该能做到。",
    "如果你没有经过这个考验，我觉得你很难成为一个真正的 FDE。因为 FDE 的工作环境可能非常恶劣：老板可能给你倒茶，也可能要你陪酒，没有工位，没有正经的工作环境，甚至办公室里大家都在抽烟。但你就要在这里找到你的第一桶金。",
    "---",
    "这些 builder 真正做的事，就是把第一个工作流蒸馏出来。",
    "我们有一个大胆的断言：这件事会是一个巨大的风口。因为每一个传统公司有且只能被蒸馏一次。再往后，所有的知识都会进入这个 AI 系统。即使这个传统行业还在迭代，所有的思考、所有的业务知识也都会进入这个 AI 系统。这样即使别人想蒸馏，也会变得非常困难。",
    "而且土老板们也不会想切换方案。关于人力成本，还有什么比一个光脚走进来的 builder 更便宜的东西呢？",
    "做完第一家以后，你肯定还能继续做这个行业。因为工作流在一个行业里其实大同小异。",
    "所以 HA7CH 会帮他们把这些 AI 系统卖给同行业的第二家、第三家。有了这些工作流，土老板可以把自己的公司变成 AI 公司，成本大大降低，让竞品无法生存。",
    "就像我们做 Raily 一样：我们能免费，是因为我们用 AI 去写代码，比之前其他的 APP 强大太多，所以我们就可以直接做到免费。",
    "---",
    "我们希望在 5-6 月跑出第一笔 FDE 交付，然后开始往 Hatch House 输送人，接着是后面的横向复制、运营等等。",
    "这件事我们可能跑得出来，也可能跑不出来。也许 6 月我就发现走不通，也许 Hatch House 是个伪命题。可能都是错的。",
    "但是不知道，因为我们他妈的也不知道 HA7CH 到底是什么。",
    "---",
    "P.S. 本文中「土老板」并不针对任何具体的人，也并非贬义。感谢改革开放创造的巨大机会。",
  ],
  en: [
    "Over the last couple of days a lot of people have been asking us what HA7CH actually does. Honestly, we don't know what HA7CH is either. But we have some thoughts, and we're going to share them here.",
    "---",
    "So what are we actually doing right now?",
    "On one side, we're running a RedNote group of around 1000 people who really love Raily, which, to be fair, has turned out pretty well. They drop feedback in there all day long.",
    "On the other side, we're running a WeChat builder group, made up of people who like vibe coding, with their heads on right. People who want to build things together, and who align with some of what HA7CH thinks.",
    "---",
    "Let's start with Raily. A lot of people want us to charge. We don't want to. We'll ship it, list it on the store, and at peak popularity we'll just open source the whole thing.",
    "Raily didn't cost us much. A few sleepless nights and some dev. But what did we get? A user base. Feedback. Affection. These matter way more than the few bucks of subscription money we could have collected.",
    "What we're after is momentum, pulling more users and more attention onto our products. There's a second use too: when we want to break out and push the next product, if someone in the builder group has an idea, they don't have to cold start. We drop what they build straight into the user group and let real users react. If they like it, we keep going. If they don't, we drop it and start the next one.",
    "So Raily is really our first branding move. Lawted's branding, HA7CH's branding. Which is fucking important.",
    "This is how we attract a certain kind of builder: people with serious AI and coding skill, with belief, with ideas, with execution.",
    "What are these people good for? They're good for FDE.",
    "---",
    "FDE is Forward Deployed Engineer. You walk straight into a traditional-industry company and rewrite their workflow with AI.",
    "Why Shenzhen? Because Shenzhen is crawling with bosses of old-school industries, and every one of them sits on a workflow built up over decades of human labor. Employees who've been there for decades have all the implicit knowledge in their heads: how to talk to clients, how to price, how the flow goes, who to call when shit breaks, what each field means, what each piece of jargon decodes to. None of it is documented. None of it lives in a system. It's all in heads, or in Excel. Their systems are mostly Excel, PDF, and Word.",
    "AI can obviously replace this. We all believe a lot of people in these companies will be laid off in two years.",
    "So why do those people get laid off? Because the boss suddenly learned to vibe code and built a system himself? I don't think so.",
    "It's because one fucking person walked into the company, came in every day with a Mac, and over two or three months distilled them, sorted them out, raised efficiency, and replaced a chunk of headcount.",
    "And I'd bet there's only one person on the inside. Two people generate communication friction, you end up slower. And the key thing: two or three months is absolutely enough. Can't ship in that time? Skill issue. Get out.",
    "This is how we let this group of people earn their first real fucking money. A first bucket of gold. Not a salary. Something they made themselves.",
    "---",
    "So how do our people get to Shenzhen to do FDE?",
    "We want to set up a Hatch House in Shenzhen. You'd be surprised how much office space is sitting around. Sponsors, borrowed rooms, or just renting somewhere for parties, any of it works. Pull these builders into one place, then connect them to companies. Every day they head out from the house to wherever they're embedded.",
    "A summer might be enough.",
    "These builders were probably students, or programmers at big tech. I believe that if they can come through and survive our 2C filter, they can do this.",
    "If you haven't been through that filter, I don't think you can be a real FDE. The FDE working environment can be brutal: the boss might pour you tea, might want you out drinking with him, no workstation, no proper workspace, the office might be full of smoke. But that's where you have to find your first bucket of gold.",
    "---",
    "What these builders are actually doing is distilling the first workflow out of a company.",
    "And we have a bold claim: this is going to be a massive wave. Because every traditional company can be distilled exactly once. After that, all the knowledge lives inside that AI system. Even if the industry keeps evolving, all the thinking, all the business knowledge ends up inside the same system. Trying to re-distill later becomes very hard.",
    "And the bosses won't want to switch vendors. On the labor cost question, what's cheaper than a builder walking in barefoot?",
    "Once you've done the first company, you can almost always keep going in that industry. Workflows in a given industry are roughly the same.",
    "So HA7CH helps these bosses sell the same AI system to competitor #2 and #3. With those workflows in hand, the boss can turn his company into an AI company. Costs drop hard, competitors can't survive.",
    "It's the same play as Raily: we can be free because we used AI to write the code, far more powerful than the older apps, so we can just give it away.",
    "---",
    "We're aiming for the first FDE delivery in May–June, then start pushing people through Hatch House, then horizontal replication and operations and so on.",
    "We might pull it off. We might not. Maybe in June I realize the path doesn't work. Maybe Hatch House is a false premise. All of it might be wrong.",
    "But who knows. We don't fucking know what HA7CH is either.",
    "---",
    "P.S. The term 'old-school bosses' in this piece doesn't refer to any specific person and isn't pejorative. Huge thanks for the opportunities Reform and Opening Up created.",
  ],
};

export default article;
