import type { Article } from "./types";

const article: Article = {
  slug: "why-you-should-come-to-hatch",
  titleZh: "你为什么该来 HA7CH",
  titleEn: "Why You Should Come to Hatch",
  date: "2026-05-21",
  dateDisplay: "May 21",
  zh: [
    "我们就假设你是一个 AI native 的人。我问你一个问题。",
    "你做过的最酷的东西，是什么？",
    "可能是某门傻逼课的期末大作业。可能是某次 hackathon 上的一个项目。或者就是某个周末，你用 Claude Code 拼了一个小 demo 出来，截图发了朋友圈，一堆人点赞。",
    "然后呢？",
    "很多事情就停在那儿了。",
    "寒暑假到了，你还是去找一份实习。一个小时 40 块钱，干一些 dog shit 的活儿。你心里清楚这不是你想要的。但你不知道还能去哪儿。",
    "---",
    "我跟你说件事。",
    "外面真的有人，愿意为你已经会的能力付钱，付一笔你想象不到的钱。",
    "但他们不在你熟悉的那个世界里。",
    "他们是一群你只要待在学校，就基本不可能接触到的老板。开着一家三十来人的传统公司。一年营收几千万。",
    "他们每天的工作是：员工在 Excel、PDF、微信、几个内部系统之间复制粘贴。他们知道这件事不对劲。他们也想用 AI。但他们不会 prompt，他们不知道去哪儿找你们这种 AI native 的人，他们也不相信外包公司、软件公司能给他们做出他们真正想要的东西。",
    "但你不一样。你会 Claude Code，你能写前端，后端也懂个大概，你一个人一周能跑出一个能用的小系统。",
    "我得说，这两个世界基本没有交集。",
    "HA7CH 要做的，就是把你送过去。",
    "你自己去找这种老板很难。让他们信你，更难。这段路你不用自己走，我们带你过去。你只管交付，只管 ship。这本来就是你最熟悉的事，对吧？",
    "---",
    "OK，再具体说说。",
    "一个暑假。你进到一家这样的公司。不是远程，是真的进现场。你跟着他们的员工看几天，或者一两个礼拜，看他们到底怎么干活。怎么对一张单。怎么跟一个客户。怎么把同一个数字在四个地方填四遍。",
    "你就直接蹲在他们公司里，两天就给他们一个能跑的东西，再过几个小时就迭代一版。",
    "最后，老板按「我省了几个人」付你钱。不是按「你用了什么 tech stack」付你钱。",
    "这一单，比你去大厂找一份实习，钱多得多。",
    "---",
    "你拿到的还不止是钱。",
    "你会知道真实客户脑子里到底在想什么。你会知道你自以为很酷的那个功能，他根本不用。你会知道他真正愿意为什么东西掏钱。你会知道东西交付以后，到底有没有人在用。",
    "这些没有一件，是你能在课上学到的。",
    "而且如果你做的这个流程，恰好是行业里很多公司都有的，那它就不只是一单生意。你拿着第一家的案例去敲第二家、第三家的门。这可能就是一个 SaaS 的起点。可能就是你创业的起点。",
    "---",
    "还有一件事。",
    "我们自己做过 FDE，知道前期手头紧是什么感觉。所以我们办了一个 Hatch House。一个让大家住到一起、一起吃饭、一起写代码、一起扯淡、一起喝酒的地方。",
    "就算这两个月你最后什么都没做成，你也认识了一群跟你一样的人。这件事本身就够爽了。说真的，挺有意思。",
    "---",
    "HA7CH 不是学校。我们不教你怎么 prompt，也不用教你怎么 fine-tune。这些对你来说太简单了，对吧？",
    "HA7CH 也不是外包公司。我们不会让你照着 PRD 一条一条按功能报价。",
    "HA7CH 就是一条路。",
    "一个暑假。从课程作业的世界里走出来，走进一个真实的行业，完成一次真实的交付，拿到一笔 real fucking money。",
    "简历上多一行，跟你自己第一次做成一单生意，是完全两件事。你自己选。",
    "---",
    "如果你觉得你就是这种人，来 ha7ch.com。",
    "我们第一批已经在跑了。",
    "下次再见。",
  ],
  en: [
    "Let's just assume you are an AI-native person. Let me ask you a question.",
    "What's the coolest thing you have ever built?",
    "Maybe it's a final project for some stupid course. Maybe it's a project at a hackathon. Or maybe one weekend you used Claude Code to throw together a small demo, took a screenshot, sent it to LinkedIn, and a lot of people liked it.",
    "And then what?",
    "A lot of things just stop there.",
    "So in the summer or winter, you still go look for an internship. Maybe 40 RMB an hour, doing some dog shit job. You know it's not what you want. You just don't know where else you can go.",
    "---",
    "So let me tell you something.",
    "There are people out there willing to pay for your ability, and pay you a lot of money. But they are not in the world you are familiar with.",
    "They are the bosses you would never get a chance to touch if you stay in school. They run a traditional company, maybe 30 people. ARR maybe a million.",
    "Their daily job is this: people are using Excel, PDF, WeChat, some internal system, just copy and paste. They know something is wrong. They want to use AI. But they don't know how to prompt, they don't know how to find these AI-native people, and they don't trust that the consulting or the IT company will give them what they actually want.",
    "But you. You can use Claude Code, you know how to build a frontend, you know some shit about backend, and you can build a small system in a week.",
    "I gotta say, these two worlds have no intersection.",
    "So what HA7CH wants to do is send you there.",
    "It's quite hard for you to find this boss. Getting them to trust you is much harder. But this path, you don't need to walk through by yourself. We're going to lead you there. You just need to deliver and ship. That's the most familiar thing for you, right?",
    "---",
    "Okay, now let's talk more specifically.",
    "A summer. You go to a company like this. Not remote. Literally on site. You follow their employees for a couple of days, maybe a couple of weeks, and see how they do their job. How they match a ticket. How they follow a customer. How they put the same number in four different places.",
    "Then you go back. Or you just sit on the ground, on the floor, and give them something they can try in maybe two days. Iterate within a couple of hours.",
    "And in the end, the boss pays you by how many people I cut. Not by what tech stack you are using.",
    "This ticket, this shit, is much higher than finding an internship at Amazon.",
    "---",
    "What's more, you get another thing.",
    "You get to know what the real customer is thinking. You get to know the cool feature they're not going to use. You get to know what they are willing to pay for. You get to know after you build it, whether people use it or not.",
    "There is not a single thing about this you can learn from class.",
    "And if this process is shared across the industry, then it's not just a single business. You use this case to knock the second door, to knock the third door. Maybe it's the start point of a SaaS. Maybe it's the entry point for your startup journey.",
    "---",
    "One more thing.",
    "We did FDE before, and we know what it looks like. So we have a Hatch House. A place where people live, eat, code, talk shit, and drink together.",
    "Even if you did nothing in those two months, you got to know a bunch of people just like you. Which is pretty insane. Pretty interesting, to be frank.",
    "---",
    "HA7CH is not a school. We don't teach you how to prompt. We don't need to teach you how to fine-tune. That's easy for you, right?",
    "And we are not an outsourcing company. We are not going to pay you by function, by feature, by PRD.",
    "HA7CH is just a path.",
    "A summer. You go from your course homework into a real industry, finish a real delivery, get a real fucking check.",
    "Adding one more line on your resume is so different from running a real business of your own. Those are two different things. You choose it yourself.",
    "---",
    "If you think you are this kind of person, just come to ha7ch.com.",
    "Our first batch is running right now.",
    "See you soon.",
  ],
  descriptionZh: "学生不缺能力，缺的是一单真正值钱的活。一个暑假，从课程作业的世界走进一个真实的行业，做完一次真实的交付。",
  description: "Students don't lack ability. They lack one piece of work that's actually worth real money. One summer, step out of class projects and into a real industry.",
  keywords: ["HA7CH", "FDE", "students", "AI builder", "summer", "internship", "ha7ch.com"],
};

export default article;
