import type { Article } from "./types";

const article: Article = {
  slug: "zero-token-after-chatgpt-work",
  titleZh: "ChatGPT Work 之后，再谈零 Token 设计",
  titleEn: "Zero Token Design, After ChatGPT Work",
  date: "2026-07-11",
  dateDisplay: "Jul 11",
  description:
    "Two months after Zero Token Design, ChatGPT Work turns the agent workspace into something everyone carries in their pocket, and it may become the entry point for every small product.",
  descriptionZh:
    "写完《零 Token 设计》两个月后，ChatGPT Work 把 agent workspace 装进了每个人的手机。为什么它可能成为以后所有小产品的入口。",
  keywords: [
    "Zero Token Design",
    "ChatGPT Work",
    "AI product",
    "agent workspace",
    "Skill",
    "Plugin",
    "npx",
    "Raily",
    "Claude Code",
    "Codex",
    "entry point",
  ],
  zh: [
    "两个月前，我写了一篇《零 Token 设计》。",
    "那篇文章的核心判断是：一个 AI 产品，不一定要在自己的 runtime 里烧 token。用户点一下就调一次模型、烧一次 token 的老逻辑，在用户已经有了自己的 agent workspace 之后，其实可以换一种做法。",
    "更好的方式是，让用户在自己的 agent workspace 里完成推理，把结构化的结果写回产品。产品负责 schema、数据库、版本、展示和分发。说白了就是，让 agent 去干活，让产品把结果接住。",
    "但那篇文章其实藏着一个我当时没说破的前提。",
    "---",
    "这套设计原来只属于少数人",
    "不是每个人都有 agent workspace。",
    "一个开发者可能已经装了 Codex、Claude Code 或者 OpenCode。他知道怎么开终端，知道 npx 是什么，也知道该把一段 quick start prompt 粘到哪里。",
    "但对绝大多数普通用户来说，这件事太远了。他不会为了用一个小产品，先去装一个 coding agent，也不会在自己电脑上配一套新的工作环境。",
    "所以零 Token 设计当时在架构上是成立的，但它其实只属于开发者。它是一个开发者的设计。",
    "---",
    "ChatGPT Work 本身就是那个 agent workspace",
    "ChatGPT Work 出来之后，我意识到这个前提被填上了。",
    "ChatGPT Work 已经不是原来那个聊天框。它可以读文件、连外部服务、跑多步骤的工作流，并且能持续工作更长时间。它本身就是一个 agent workspace。",
    "更关键的是，它跑在云端，而且进了手机。过去只有开发者的电脑里才有 agent workspace，现在它出现在每一个人的手机里。",
    "所以你不需要让手机自己去执行一条 npx 命令。真正的执行环境已经在 ChatGPT 背后的云端工作台里。",
    "而 npx 的角色，其实彻底反了过来。以前，npx 是用户启动某项产品能力的入口；以后，npx 只是开发者把能力打包进去的一种方式，用户甚至不需要知道它存在。他只需要说一句话。",
    "于是零 Token 设计，从一个面向开发者的架构，第一次变成了一个面向所有人的架构。",
    "---",
    "Raily 那个截图导入功能，不用做了",
    "我之前做过一个高铁行程 App，叫 Raily。",
    "当时有人给过我一个很合理的建议：为什么不加一个截图导入功能？用户在 12306 买完票，把订单截图传进 Raily，Raily 自动识别日期、车次、出发到达站、时间和座位，生成一条行程。",
    "按以前的产品逻辑，这功能当然该做。我得在 Raily 里做图片上传、申请相册权限、接 OCR、解析字段、处理识别错误、加一个二次确认页，最后再把数据写进服务器。",
    "但现在再看，这个功能根本不需要存在于 Raily 里。",
    "用户买完票，直接把截图发给 ChatGPT：把这趟高铁加进我的 Raily。",
    "ChatGPT 看懂截图。Raily Skill 把车次、时间、车站和座位转成 Raily 需要的数据结构，再调用 Raily 的接口写进服务器。Raily Skill 和 Raily App 共用同一套账户、同一个数据库、同一台服务器。",
    "用户下一次打开 Raily，这趟行程已经在时间线上了。他没有打开 Raily，没有找导入按钮，没有重新上传一次截图，也没有去学 Raily 支持什么格式。",
    "---",
    "但 Raily 不会消失",
    "这不代表 Raily 会被 ChatGPT 取代。",
    "因为对话框不一定是查看铁路行程的最佳界面。用户还是需要一条清晰的时间线、不同城市之间的换乘、出发和到达提醒、车站信息、历史行程，甚至一张铁路旅行地图。这些体验，一个专门的垂直 App 可能比对话框做得更好。",
    "真正变化的是，Raily 不再需要同时承担所有事情。ChatGPT 负责理解用户想干什么、负责把真实世界的输入接进来；Raily 负责把铁路行程展示到最好。",
    "它们不是两个互相竞争的产品，而是同一个系统的两个界面。一个负责输入，一个负责展示，背后共用同一份数据。",
    "这个逻辑不只适用于高铁 App。一个消费分析产品也一样：用户不用再下载 App、注册、拍小票、等 OCR、改错误、选类别，才能进到报表页。他可以直接在 ChatGPT 里拍一张小票说帮我记一笔，再打开网站看完整的月度图表，两边读的是同一份数据。",
    "---",
    "ChatGPT Work 会成为所有小产品的入口",
    "所以这次真正的变化，不是截图导入变得更方便了。",
    "而是 ChatGPT Work 可能成为以后所有小产品的入口。",
    "过去，每一个产品都要自己建一套入口：注册、登录、上传、搜索、表单、帮助中心，再加一个新的 AI 聊天框，和一套自己的推理服务。每一个创业者，都在重复造这些几乎一样的东西。",
    "但用户真正需要的，往往不是这些入口，而是产品背后的那点能力：一段行业规则、一套数据结构、一个稳定的执行流程，以及长期沉淀下来的状态。",
    "ChatGPT Work 的意义，就是把这层通用的壳，从每一个产品里抽走。",
    "于是未来的小产品，可能只需要四样东西：一套清晰的数据结构，一台可靠的服务器，一个能被 agent 调用的 Skill 或 Plugin，以及一个真正值得独立存在的展示界面。第一批用户，甚至可以完全通过 ChatGPT 来用你的产品。",
    "---",
    "先设计接口，再设计页面",
    "到这一步，产品的结构会变。",
    "以前是：用户打开 App，App 理解用户，App 调用 AI，App 写数据，App 展示结果。以后可能是：用户打开 ChatGPT Work，ChatGPT 理解用户，Skill 调用产品能力，产品服务器保存状态，App 展示结果。",
    "所以创业者第一件要问的事，可能不再是我要做几个页面，而是：我的产品能不能被 agent 调用？能不能稳定地接收结构化结果？身份和权限能不能在 ChatGPT 和产品之间打通？Skill 和 App 能不能读写同一份数据？用户不打开我的产品时，它还能不能产生价值？",
    "这也会改变产品分发的逻辑。过去我们问的是，怎么让用户多打开一次我的产品；以后我们要问的，可能是怎么让 ChatGPT 在正确的时候调用我的产品。",
    "SEO 是让搜索引擎找到你的页面。未来可能会有另一种优化：让 agent 理解你的能力、信任你的接口，并在正确的场景里调用你。",
    "---",
    "再说回零 Token",
    "这也是我想再写一次零 Token 设计的原因。",
    "第一次写它的时候，我关心的是 token 成本，别让每个产品都重复承担一遍推理。但今天再看，零 Token 设计真正重要的，可能不是省了多少钱，而是它重新定义了一个产品应该在哪里发生。",
    "过去，一个产品必须发生在自己的网站和 App 里。现在，一个产品可以发生在用户的 agent workspace 里。而 ChatGPT Work，把这个 agent workspace 从开发者的终端，搬到了所有人的手机。这一次，用户不需要装 Codex，不需要懂 npx，只需要打开 ChatGPT。",
    "而当一个产品开始发生在 agent workspace 里，用户进入它的地方，也跟着搬了过去。产品在哪里发生，用户就在哪里进入，这两件事第一次重合了。",
    "所以以后，别急着给每个产品再塞一个 chatbot，也别急着为每一种输入重做一个页面。该交给 agent 的就交出去，只把真正需要专业呈现的地方，留给一个好的 App。",
    "以前，我们为每一个产品设计一个入口。以后，所有产品可能共用同一个入口。这个入口，就是 ChatGPT Work。",
  ],
  en: [
    "Two months ago I wrote a piece called Zero Token Design.",
    "The core claim was this: an AI product doesn't always need to burn its own tokens at runtime. The old logic, where every click fires another model call and burns another token, works differently once the user already has their own agent workspace.",
    "The better way is to let the user finish the reasoning inside their own agent workspace, and then push the structured result back into the product. The product owns the schema, the database, the versions, the rendering, and the distribution. Basically: let the agent do the work, and let the product catch the result.",
    "But that piece quietly rested on one assumption I never said out loud.",
    "---",
    "It Only Worked for a Few People",
    "Not everyone has an agent workspace.",
    "A developer might already have Codex, Claude Code, or OpenCode installed. They know how to open a terminal, they know what npx is, and they know where to paste a quick-start prompt.",
    "But for most ordinary users, that's still too much of a leap. They're not going to install a coding agent just to use some small product, and they're not going to set up a new working environment on their laptop.",
    "So Zero Token Design held up as an architecture, but it really only belonged to developers. It was a developer's design.",
    "---",
    "ChatGPT Work Is That Agent Workspace",
    "After ChatGPT Work shipped, I realized that missing piece was now in place.",
    "ChatGPT Work is no longer the old chat box. It can read files, connect to external services, run multi-step workflows, and keep working for much longer stretches. It's an agent workspace in its own right.",
    "What matters more is that it runs in the cloud, and it is on the phone. The agent workspace that used to live only on a developer's laptop now sits in everyone's pocket.",
    "You don't need the phone itself to run an npx command. The real execution environment already lives in the cloud workspace behind ChatGPT.",
    "But the role of npx has flipped completely. Before, npx was how a user launched a product's capability. Now, npx is just how a developer packages that capability into the product. The user doesn't even need to know it exists. They just have to ask.",
    "So for the first time, Zero Token Design goes from an architecture for developers to an architecture for everyone.",
    "---",
    "That Screenshot Importer? Don't Build It",
    "I once built a high-speed rail app called Raily.",
    "Someone gave me a very reasonable suggestion at the time: why not add a screenshot import feature? A user buys a ticket on 12306, drops the order screenshot into Raily, and Raily automatically reads the date, train number, departure and arrival stations, time, and seat, then creates a trip.",
    "By the old product logic, of course you should build this. I would have to build image upload inside Raily, request photo library permissions, wire up OCR, parse the fields, handle recognition errors, add a confirmation step, and finally write the data to the server.",
    "But looking at it now, that feature does not need to live inside Raily at all.",
    "The user buys the ticket and sends the screenshot straight to ChatGPT: add this train to my Raily.",
    "ChatGPT reads the screenshot. The Raily Skill turns the train number, time, stations, and seat into the data structure Raily needs, then calls Raily's API to write it to the server. The Raily Skill and the Raily app share the same account, the same database, and the same server.",
    "The next time the user opens Raily, the trip is already on the timeline. They never had to open Raily to make it happen, never hunted for an import button, never re-uploaded the screenshot, and never learned what formats Raily supports.",
    "---",
    "But Raily Doesn't Disappear",
    "This doesn't mean ChatGPT replaces Raily.",
    "Because a chat box isn't necessarily the best interface for looking at rail trips. Users still want a clean timeline, transfers between cities, departure and arrival reminders, station details, trip history, maybe even a map of where they have traveled by rail. A dedicated vertical app can probably do these better than a chat box.",
    "What actually changes is that Raily no longer has to carry everything at once. ChatGPT handles understanding what the user wants and pulling in real-world input. Raily handles showing the rail trip beautifully.",
    "They're not two competing products. They're two interfaces of the same system. One handles input, one handles display, and they share the same data underneath.",
    "This logic is not limited to a rail app. A spending tracker is the same: the user no longer has to download an app, sign up, photograph a receipt, wait for OCR, fix errors, and pick a category just to reach a report page. They can snap a receipt inside ChatGPT and say log this expense, then open a website to see the full monthly chart. Both sides read the same data.",
    "---",
    "ChatGPT Work Becomes the Entry Point for Every Small Product",
    "So the real change this time is not that screenshot import got more convenient.",
    "It's that ChatGPT Work might become the entry point for every small product from now on.",
    "In the past, every product had to build its own entry: sign up, login, upload, search, forms, a help center, plus a new AI chat box and its own inference service. Every founder was rebuilding the same things.",
    "But what users actually need is usually not these entries. It's the small bit of capability behind the product: a set of domain rules, a data structure, a stable execution flow, and the state that accumulates over time.",
    "The point of ChatGPT Work is that it strips this generic shell out of every product.",
    "So the small product of the future may only need four things: a clear data structure, a reliable server, a Skill or Plugin that agents can call, and a display surface that genuinely deserves to exist on its own. The first batch of users might use your product entirely through ChatGPT.",
    "---",
    "Design the API Before the Pages",
    "At that point, the structure of a product shifts.",
    "It used to be: the user opens the app, the app understands the user, the app calls the AI, the app writes the data, the app displays the result. Now it might be: the user opens ChatGPT Work, ChatGPT understands the user, the Skill calls the product's capability, the product server holds the state, and the app displays the result.",
    "So the first question a founder asks may no longer be how many pages do I need to build. It becomes: can my product be called by an agent? Can it reliably accept a structured result? Can identity and permissions carry over between ChatGPT and my product? Can the Skill and the app read and write the same data? When the user never opens my product, does it still create value?",
    "This also changes the logic of distribution. We used to ask how to get the user to open our product one more time. Now we may have to ask how to get ChatGPT to call our product at the right moment.",
    "SEO is about getting a search engine to find your page. There may be a new kind of optimization ahead: getting an agent to understand your capability, trust your interface, and call you in the right situation.",
    "---",
    "Back to Zero Token",
    "This is also why I wanted to write about Zero Token Design one more time.",
    "The first time, I cared about the token cost, about not making every product carry the same inference over and over. But looking at it now, what really matters about Zero Token Design may not be how much money it saves. It is that it redefines where a product is allowed to happen.",
    "In the past, a product had to happen inside its own website and app. Now, a product can happen inside the user's agent workspace. And ChatGPT Work moved that agent workspace from a developer's terminal into everyone's phone. This time, the user doesn't need to install Codex, doesn't need to understand npx, and only needs to open ChatGPT.",
    "And once a product starts happening inside the agent workspace, the place where users enter it moves there too. Where a product happens and where the user enters it become the same place, for the first time.",
    "So from now on, don't rush to stuff another chatbot into every product, or rebuild a page for every kind of input. Hand the agent what belongs to the agent, and keep a good app only for the places that genuinely need a dedicated display.",
    "In the past, we designed an entry point for each product. In the future, all products may share the same entry point. And that entry point is ChatGPT Work.",
  ],
};

export default article;
