import type { Article } from "./types";

const article: Article = {
  slug: "zero-middle-management",
  titleZh: "0 中层公司：AI Native Company 的下一种组织形态",
  titleEn: "The Zero-Middle-Management Company",
  date: "2026-08-03",
  dateDisplay: "Aug 3",
  descriptionZh:
    "0 中层不是没有管理，而是不再保留一层以汇总信息、传达指令、协调资源为主要工作的永久中层。传统公司让信息沿着人流动，ANC 让信息沿着系统流动。从 Block 的公开实验到 48 理论：48 小时绕过中层，48 天蒸馏中层，48 周重构中层。",
  description:
    "Zero middle management doesn't mean zero management. It means no permanent layer of people whose main job is relaying information, passing down instructions, and coordinating resources. Traditional companies route information through people; an AI Native Company routes it through systems. From Block's public experiment to the 48 theory: bypass the middle layer in 48 hours, distill it in 48 days, rebuild it in 48 weeks.",
  keywords: [
    "AI Native Company",
    "ANC",
    "0 中层",
    "zero middle management",
    "组织形态",
    "org design",
    "DRI",
    "player-coach",
    "company world model",
    "Block",
    "Goose",
    "48 理论",
    "FDE",
    "HA7CH",
  ],
  zh: [
    "AI Native Company 可以被进一步定义为一家「0 中层公司」。这里的「0 中层」，不是没有管理者，也不是所有员工都直接向老板汇报，而是不再保留一层以汇总信息、传达指令、协调资源和监督流程为主要工作的永久中层。过去由中层承担的组织协调功能，被拆解给企业 Context、Skills、Agent、Evals、权限系统和动态 DRI；人与人的管理仍然存在，但管理不再天然对应一个永久职位。",
    "压到最短就是：传统公司让信息沿着人流动，ANC 让信息沿着系统流动；传统公司把权力绑定在职位上，ANC 把权力绑定在结果上。",
    "有两点先说清楚。",
    "第一，0 中层不等于 0 管理。公司依然需要战略、授权、裁决、人才培养、冲突处理和风险治理。消失的是以信息搬运为主要价值的管理层，保留下来的是对结果负责的人。",
    "第二，0 中层不是裁员方案，而是组织能力成熟后的结果。如果企业没有 Context、Skills、Agent、Evals、权限和审计，直接把中层裁掉，不会得到一家 AI Native Company，只会得到一家失去协调能力的公司。",
    "一、组织架构本来就是一种信息技术",
    "为什么公司发展到一定规模以后，一定会出现中层？",
    "根本原因不是老板喜欢官僚主义，而是人的带宽有限。",
    "一个创始人可以直接理解五个人在做什么，却不可能持续理解五百个人每天在做什么。随着组织扩大，公司只能把人分成小组，每个组设置负责人，再把几个负责人交给更高一层管理者。",
    "员工向组长汇报，组长向部门经理汇报，部门经理向总监汇报，总监最后把信息整理成一份 PPT 交给老板。老板作出决定以后，指令再沿着同样的链条逐级向下传递。",
    "所以传统组织架构表面上是在划分权力，本质上却是一套由人组成的信息系统。每一层中层都承担三种作用：压缩信息、传递指令、协调资源。",
    "中层不是偶然出现的冗余，而是工业时代解决组织规模问题的基础设施。但这套系统有一个无法避免的问题：信息每经过一层，就会损失一次。",
    "客户在现场说了十句话，一线员工记住八句，汇报给经理时剩下五句，经理写进周报时剩下三句，最后出现在老板 PPT 上的可能只剩一句：「客户对系统体验存在一定意见。」",
    "反过来也一样。老板提出的是「提高客户续约率」，经过几层拆解以后，可能变成要求员工每天打多少个电话、填写多少张表、完成多少个与客户价值无关的过程指标。",
    "于是传统公司形成了一个矛盾：公司越大，越依赖中层；中层越多，公司距离真实工作和真实客户越远。",
    "过去没有更好的办法，因为组织中的信息只能由人理解、归纳和传递。但现在，这个前提第一次发生了变化。",
    "二、AI 首先替代的可能不是员工，而是信息路由层",
    "今天，大部分企业所谓的 AI 转型，是给每个员工购买一个大模型账号。",
    "员工用 AI 写材料，经理用 AI 总结材料，总监用 AI 把几份总结变成汇报，老板再用 AI 阅读这份汇报。看起来每个人都提高了效率，但公司的信息结构没有发生任何变化。",
    "以前员工花两个小时写周报，现在只需要十分钟；以前经理花半天汇总周报，现在只需要半小时。结果不是公司更接近客户了，而是旧金字塔能够生产更多周报了。",
    "这不是 AI Native Company。",
    "AI Native Company 不是给传统组织的每一个节点安装一个 Copilot，而是重新追问：这些节点还有没有存在的必要？",
    "如果企业里的客户反馈、项目记录、会议纪要、合同、代码、订单、报价和财务数据都已经数字化，Agent 就可以直接读取这些原始 Context，持续判断公司现在发生了什么、哪个项目正在延期、客户真正提出了什么问题、哪个环节正在重复返工、哪些决策已经作出，以及下一步应该由谁行动。",
    "老板不再需要等待三层汇报才能知道一线发生了什么，员工也不必通过三层审批才能获得完成任务需要的背景、方法和资源。",
    "所以 AI 对组织最大的影响，可能不是让一个员工完成两个人的工作，而是让公司不再需要依靠一层又一层的人来搬运信息。",
    "当组织的 Context 可以被 AI 直接理解，中层最重要的信息路由功能就开始失去存在的基础。",
    "三、0 中层，不是没有负责人",
    "「0 中层公司」最容易引起的误解，是大家会以为公司以后没有管理，也没有老板，几百个人完全自我组织。",
    "这不现实。",
    "AI Native Company 依然需要明确的最终责任人。它改变的不是责任是否存在，而是责任如何产生。",
    "传统公司的权力来自职位。因为你是部门经理，所以这个部门的预算、招聘、项目和信息都要经过你。无论公司此刻最重要的问题是什么，你都永久占据组织中的这一层。",
    "ANC 的权力来自结果。因为你在未来 48 天里对「把报价 Agent 部署到一线并达到 80% 使用率」负责，所以你暂时拥有调动相关人员、数据和系统的权力。任务完成以后，这份授权可以结束，也可以转移到另一个问题上。",
    "这就是 DRI，Directly Responsible Individual。",
    "DRI 不一定拥有永久下属，也不需要先拥有一个部门，才能解决一个问题。他只是在一段明确时间里，对一个明确结果承担最终责任。",
    "因此，0 中层公司不是所有人直接向 CEO 汇报，而是大部分工作不再通过汇报关系被组织，而是通过任务、结果和动态授权被组织。",
    "传统公司是职位先存在，再把任务放进职位里；ANC 是问题先出现，再围绕问题组织人和 Agent。",
    "四、中层不会被一个 Agent 替代，而是被一套系统拆解",
    "「用一个 AI 经理替代所有中层」同样是一种过度简化。",
    "中层承担的工作至少可以被拆成五类：",
    "| 中层的传统职能 | ANC 中的承接机制 |",
    "| --- | --- |",
    "| 收集情况、汇总进度 | 企业 Context 与持续更新的组织状态 |",
    "| 传达制度和工作方法 | Skills 与标准化工作流 |",
    "| 分配任务、协调资源 | Agent 编排与动态 DRI |",
    "| 检查质量、发现异常 | Evals、监控与审计记录 |",
    "| 培养员工、处理冲突 | 人类 player-coach |",
    "前四类工作主要涉及信息处理、流程执行和结果验证，可以逐步交给系统。最后一类涉及信任、情绪、价值判断和人的长期成长，依然需要人。",
    "因此，ANC 不是拿一个 Agent 替换一个经理，而是建立一套新的组织基础设施。",
    "企业 Context 替代层层汇报；Skills 替代依靠老员工口头传授的方法；Agent 替代重复的任务分发、信息查询和流程执行；Evals 替代「做好以后给领导看一下」；权限与审计替代隐藏在个人职位里的模糊控制。",
    "真正需要处理人的成长、专业判断和冲突的人，会变成 player-coach：一边参与真实工作，一边帮助其他人成长。",
    "在 ANC 里，脱离一线工作的纯管理者会越来越少；既能够创造结果，又能够帮助他人创造结果的人会越来越重要。",
    "五、0 中层公司的四类人",
    "一家成熟的 0 中层公司，大致会保留四种核心角色。",
    "第一类是 Owner。Owner 决定公司为什么存在、什么结果最重要、哪些边界不能突破，以及出现重大冲突时由谁作出最终裁决。AI 可以帮助 Owner 看见更多事实，但不能替代责任归属。",
    "第二类是 DRI。DRI 围绕一个具体问题获得阶段性授权。他可能负责一次 48 小时 Sprint，也可能负责一个持续半年的客户结果。只要任务还存在，他就拥有调动相关资源的权力；任务结束，授权就重新分配。",
    "第三类是 Builder。ANC 中的大多数人都应该是 Builder。工程师、销售、顾问、运营、设计师、律师和财务都可以是 Builder。关键不在岗位名称，而在于他是否直接创造结果。在 Agent 的帮助下，一个人可以带着一组 Agent，对一段更完整的结果负责。",
    "第四类是 player-coach。他自己仍然在场上比赛，同时负责专业标准、人才培养和复杂判断。他不是靠拥有下属证明价值，而是靠专业能力和他人信任产生影响。",
    "因此，0 中层公司不是把管理者全部变成普通员工，而是要求管理者重新成为创造者。",
    "六、Block 正在公开尝试取消永久中层",
    "目前公开资料中，最接近这种组织形态的，不是 Anthropic，也不是 OpenAI，而是 Square 的母公司 Block。",
    "2026 年，Jack Dorsey 和红杉合伙人 Roelof Botha 发表了《From Hierarchy to Intelligence》。他们提出，传统公司的层级结构本质上是为了解决信息流动问题。管理者需要掌握团队正在发生什么，再将这些信息沿着组织结构向上汇总、向下传达。",
    "但 Block 是一家 remote-first 公司。公司的讨论、决策、计划、代码、问题和项目进展，本来就大量存在于数字系统中。这些记录可以成为 company world model 的原材料。",
    "这个 world model 可以持续理解什么正在被开发、哪个项目被卡住、资源被分配到了哪里、什么方法正在奏效，以及哪些结果正在偏离预期。",
    "如果 AI 能够持续维护这张公司地图，组织就不再需要依靠管理者反复开会、询问和制作汇报，才能知道自己正在发生什么。",
    "Block 为此提出了三种核心角色：直接创造结果的 Individual Contributor、对具体问题和客户结果负责的 DRI，以及一边工作、一边培养他人的 player-coach。",
    "它的公开文章里有一句非常直接的话：There is no need for a permanent middle management layer.",
    "不过，这句话不能被误读成「Block 已经是完全成熟的 0 中层公司」。Block 自己也明确承认，这项转型仍处于早期阶段，部分机制可能会先出问题，再逐步成熟。",
    "准确的表述应该是：Block 不是已经完成了 0 中层，而是第一批公开、系统地向 0 永久中层转型的大型科技公司。",
    "来源：Block《From Hierarchy to Intelligence》（block.xyz/inside/from-hierarchy-to-intelligence）",
    "七、Claude 正在把这件事从理论变成基础设施",
    "Block 并不是只写了一篇组织理论文章。",
    "它内部已经部署了基于 Claude 的开源 Agent Goose，把模型与公司的数据、工具和工作流连接起来。",
    "根据 Anthropic 公布的案例，75% 的 Block 工程师每周因此节省 8—10 小时以上；数千名不同岗位的员工已经开始使用 Goose；非技术员工可以直接生成 SQL、查询数据和自动化流程，不再必须把问题提交给数据团队，再等待排期。",
    "这些数字最重要的意义不是「工程师效率提高了」。",
    "真正的组织变化是：员工开始直接调用公司的数据和工具，不再需要通过管理者协调另一个部门的人，才能完成任务。",
    "过去，一个产品经理想知道某项功能的客户使用情况，需要先联系数据团队、解释需求、等待排期、确认口径，再拿到报表。现在，他可以直接让 Agent 查询数据、生成 SQL、解释结果，并把分析转化为下一步行动。",
    "这减少的不只是一名数据分析师的工作，也减少了围绕这项工作产生的沟通、排期、审批和管理。",
    "来源：Claude × Block 案例（claude.com/customers/block）",
    "另一个更直接的案例是 LaunchNotes。它将 GitHub、Jira、Linear 等系统里的项目数据交给 Claude 分析，自动生成个性化进展更新、识别异常并理解工程上下文。使用以后，团队识别事故的速度提升到原来的 5 倍，会议时间减少了 50%。",
    "收集进度、发现阻塞、组织同步、提醒负责人，本来就是工程中层最常见的工作。Claude 并没有「扮演一名经理」，但它接走了经理大量用于收集信息和维持同步的工作。",
    "来源：LaunchNotes × Claude 案例（claude.com/customers/graph）",
    "Anthropic 对内部 132 名工程师和研究人员的调查也显示，受访者平均已经在约 59% 的工作中使用 Claude，并自报获得约 50% 的生产力提升。Claude Code 平均连续执行的动作数量，也从半年前大约 10 个增长到了约 20 个。",
    "这说明 Agent 正在从「帮助人完成一个步骤」，逐渐进入「独立承担一段工作」的阶段。",
    "来源：Anthropic《How AI Is Transforming Work at Anthropic》（anthropic.com/research/how-ai-is-transforming-work-at-anthropic）",
    "八、Anthropic 和 OpenAI 都不是 0 中层公司",
    "这里需要做一个事实澄清。",
    "Anthropic 虽然深度使用 Claude，也强调高信任、小团队和个人主动性，但它并不是 0 中层公司。Anthropic 仍在公开招聘 Research Manager 和 Engineering Manager，职责包括管理团队执行、员工绩效、职业发展、招聘和跨团队沟通。",
    "OpenAI 同样不是。OpenAI 的公开招聘信息中，仍然存在经理、区域负责人和全球负责人的多层结构。例如，APAC 销售发展负责人需要管理各个市场的前线 SDR 经理和销售团队；HRBP 岗位也明确需要辅导经理、参与组织设计和人才规划。",
    "Square 也不能被单独称为 0 中层公司。Square 现在是 Block 旗下的业务品牌，提出这套组织变革的是母公司 Block。",
    "因此，目前更准确的判断是：Anthropic 是一家高度 AI 化的公司，但不是 0 中层公司；OpenAI 是一家生产 AI 的公司，但也不是 0 中层公司；Block 是目前公开向 0 永久中层转型最激进的大公司之一，但这场实验尚未完成。",
    "这也说明，「做出最先进的 AI」和「用 AI 重构自己的组织」是两件不同的事。",
    "九、0 中层不是从组织架构开始，而是从企业 Context 开始",
    "很多老板看到这里，第一反应可能是：那我是不是应该开始削减管理层？",
    "不是。",
    "如果企业的真实信息还散落在个人微信、纸质文件、Excel、员工大脑和互不连通的软件中，中层依然是公司最重要的信息连接器。",
    "在这种情况下裁掉中层，组织的信息不会自动进入 AI，只会跟着人一起离开。",
    "所以 ANC 改造不能从修改组织架构开始，而应该从打穿真实业务开始。",
    "先选择一个足够具体、能够验证价值的业务点，让 FDE 进入现场，理解真实流程，连接必要的数据和工具，做出第一个可用系统。",
    "员工开始使用以后，系统才能收集真实反馈。哪些规则需要增加，哪些权限不能开放，哪些异常必须人工处理，哪些判断依赖老员工经验，只有进入业务以后才能知道。",
    "这些反馈再被沉淀成 Context、Skills 和 Evals，Agent 才能逐渐承担更完整的任务。",
    "当越来越多的信息不再依赖中层汇报，越来越多的方法不再依赖中层口头传授，越来越多的任务不再依赖中层协调，组织结构才有条件自然变平。",
    "不是先裁掉中层，再建设 ANC；而是先建设组织智能，让一部分中层职能自然失去存在的必要。",
    "十、48 小时、48 天、48 周，也是从有中层走向 0 中层",
    "「0 中层公司」可以被放进劳泰德 48 理论中理解。",
    "48 小时，FDE 提出一个面、打穿一个点，绕过传统立项、汇报和部门协调，让老板直接看见业务价值。这一阶段不是改变组织，而是证明：有些事情不需要经过原来的七八个工种和多层协作，也可以快速完成。",
    "48 天，系统部署给员工使用。通过真实使用收集企业 Context，把散落在人脑、聊天记录和文件中的经验，逐渐沉淀为知识库、Skills、工作流和 Evals。这一阶段开始蒸馏中层。原来中层掌握的规则、经验和判断，开始变成组织可以重复调用的能力。",
    "48 周，经过验证的 Agent 开始承担端到端任务。企业重新划分人和 AI 的工作、责任、权限与风险，一部分永久部门被动态 DRI 和任务型团队取代。这一阶段才真正开始重构中层。",
    "所以可以把三个阶段进一步压缩成：48 小时绕过中层，48 天蒸馏中层，48 周重构中层。",
    "0 中层不是 48 小时的口号，而是 48 周以后可能出现的组织结果。",
    "十一、判断一家公司是不是 ANC，看五个问题",
    "未来判断一家公司是不是 AI Native Company，不应该看它买了多少大模型账号，也不应该看员工每天写多少 Prompt，而应该问五个问题。",
    "第一，老板能不能不等待三层汇报，直接理解一线真实发生的事情？",
    "第二，员工能不能不依赖领导协调，直接获得完成任务需要的 Context、Skills、数据和工具？",
    "第三，公司的关键能力是掌握在几个老员工脑中，还是已经成为所有员工和 Agent 都能调用的组织资产？",
    "第四，一项工作是否合格，依赖「领导看一眼」，还是已经存在明确、可执行、可追溯的 Evals？",
    "第五，一个人获得资源和决策权，是因为他永久占据某个职位，还是因为他正在对一个明确结果负责？",
    "如果这些问题仍然依赖组织层级，那么这家公司最多是在使用 AI。",
    "只有当信息不再依赖中层搬运，方法不再依赖个人垄断，任务可以由 Agent 执行，质量可以由 Evals 验证，责任可以围绕结果动态重组，它才真正开始成为 AI Native Company。",
    "结语：管理不会消失，管理层会消失",
    "传统公司是一座金字塔。",
    "信息从底层逐级向上，权力从顶层逐级向下。中层站在每个节点上，负责压缩信息、传达命令、协调资源和维持流程。",
    "AI Native Company 更像一个持续学习的组织智能。",
    "企业 Context 负责记忆，Skills 负责沉淀方法，Agent 负责执行，Evals 负责判断，权限系统负责控制风险，DRI 对具体结果负责，player-coach 负责人的成长。",
    "所以，0 中层真正取消的不是管理，也不是责任。",
    "它取消的是工业时代的一种组织默认：一个人可以只靠收集信息、召开会议、传达指令和管理别人，永久占据公司的一层。",
    "未来的公司依然会有创始人，依然会有负责人，依然会有经验更丰富、判断力更强的人。但他们的价值不再是站在信息必经之路上，而是定义方向、承担责任、作出判断和培养他人。",
    "在 AI Native Company 里，每个人最终都必须靠近两样东西：要么靠近真实工作，要么靠近真实客户。",
    "剩下的信息搬运，交给 Agent。",
  ],
  en: [
    "An AI Native Company can be defined one step further: a \"zero-middle-management company.\" Zero middle management does not mean no managers, and it does not mean everyone reports directly to the boss. It means the company no longer keeps a permanent layer of people whose main job is aggregating information, passing down instructions, coordinating resources, and supervising process. The coordination work that middle managers used to do gets decomposed into company Context, Skills, Agents, Evals, a permission system, and dynamic DRIs. Managing people still exists — but management no longer automatically comes with a permanent position.",
    "Compressed to one line: traditional companies route information through people; an ANC routes information through systems. Traditional companies bind power to positions; an ANC binds power to outcomes.",
    "Two clarifications up front.",
    "First, zero middle management is not zero management. A company still needs strategy, delegation, arbitration, talent development, conflict resolution, and risk governance. What disappears is the management layer whose main value is moving information around. What stays are the people accountable for outcomes.",
    "Second, zero middle management is not a layoff plan. It is what a mature organization looks like after its capabilities have grown. If a company has no Context, Skills, Agents, Evals, permissions, or audit, firing the middle layer will not produce an AI Native Company — just a company that has lost the ability to coordinate itself.",
    "1. Org charts were always an information technology",
    "Why does every company, past a certain size, inevitably grow a middle layer?",
    "The root cause is not that bosses love bureaucracy. It is that human bandwidth is finite.",
    "A founder can directly understand what five people are doing, but cannot continuously understand what five hundred people do every day. As the organization grows, the company has no choice but to split people into teams, give each team a lead, and hand several leads to a manager one level up.",
    "Employees report to team leads, team leads report to department managers, managers report to directors, and the director finally compresses everything into a slide deck for the boss. Once the boss decides, instructions travel back down the same chain.",
    "So a traditional org chart looks like a division of power, but is really an information system made of people. Every middle layer performs three functions: compress information, relay instructions, coordinate resources.",
    "Middle management is not accidental redundancy. It was the industrial era's infrastructure for scaling organizations. But the system has one unavoidable flaw: information loses fidelity every time it passes through a layer.",
    "A customer says ten things on site. The frontline employee remembers eight, reports five to the manager, three make it into the weekly report, and what reaches the boss's slide might be a single line: \"The customer has some concerns about the system experience.\"",
    "It works the same way downward. The boss asks for \"higher customer renewal rates.\" A few layers of decomposition later, it becomes daily call quotas, forms to fill, and process metrics that have nothing to do with customer value.",
    "So traditional companies live inside a contradiction: the bigger the company, the more it depends on middle layers; the more middle layers, the further the company drifts from real work and real customers.",
    "There used to be no better option, because organizational information could only be understood, summarized, and relayed by humans. That premise has now changed for the first time.",
    "2. The first thing AI replaces may not be employees, but the information routing layer",
    "Today, most so-called AI transformation means buying every employee a large-model subscription.",
    "Employees use AI to write documents, managers use AI to summarize them, directors use AI to turn summaries into briefings, and the boss uses AI to read the briefing. Everyone looks more efficient, but the company's information structure has not changed at all.",
    "A weekly report that took two hours now takes ten minutes; consolidating reports that took half a day now takes half an hour. The result is not that the company got closer to its customers — it is that the old pyramid can now produce more weekly reports.",
    "That is not an AI Native Company.",
    "An AI Native Company does not install a copilot at every node of the traditional org chart. It asks a different question: do these nodes still need to exist?",
    "If customer feedback, project records, meeting notes, contracts, code, orders, quotes, and financial data are already digital, an Agent can read that raw Context directly and continuously work out what is happening in the company: which project is slipping, what the customer actually asked for, where work is being redone, which decisions have already been made, and who should act next.",
    "The boss no longer waits through three layers of reporting to learn what happened on the front line. Employees no longer need three layers of approval to get the background, methods, and resources a task requires.",
    "So AI's biggest impact on organizations may not be one employee doing the work of two. It is the company no longer needing layer after layer of people to move information around.",
    "Once organizational Context can be understood directly by AI, the middle layer's most important function — information routing — starts losing its reason to exist.",
    "3. Zero middle management does not mean nobody is accountable",
    "The easiest misreading of the \"zero-middle-management company\" is imagining a company with no management and no boss, where hundreds of people fully self-organize.",
    "That is not realistic.",
    "An AI Native Company still needs clearly accountable owners. What changes is not whether responsibility exists, but how responsibility is produced.",
    "In a traditional company, power comes from position. Because you are the department manager, the department's budget, hiring, projects, and information all flow through you. Whatever the company's most important problem is right now, you permanently occupy that layer of the organization.",
    "In an ANC, power comes from outcomes. Because you are responsible for \"deploying the quoting Agent to the front line at 80% adoption within the next 48 days,\" you temporarily hold the power to mobilize the relevant people, data, and systems. When the task ends, the mandate can end too, or move to another problem.",
    "That is the DRI — the Directly Responsible Individual.",
    "A DRI does not need permanent reports, and does not need to own a department before they can solve a problem. They simply carry final responsibility for a specific outcome over a specific period of time.",
    "So a zero-middle-management company is not everyone reporting to the CEO. It is most work no longer being organized through reporting lines, but through tasks, outcomes, and dynamic mandates.",
    "Traditional companies create positions first and pour tasks into them; an ANC lets problems appear first, then organizes people and Agents around the problem.",
    "4. The middle layer is not replaced by one Agent, but decomposed by a system",
    "\"Replace all middle managers with one AI manager\" is another oversimplification.",
    "The middle layer's work breaks down into at least five categories:",
    "| Traditional middle-management function | What takes it over in an ANC |",
    "| --- | --- |",
    "| Collecting status, consolidating progress | Company Context and a continuously updated organizational state |",
    "| Relaying policies and working methods | Skills and standardized workflows |",
    "| Assigning tasks, coordinating resources | Agent orchestration and dynamic DRIs |",
    "| Checking quality, catching anomalies | Evals, monitoring, and audit trails |",
    "| Growing people, resolving conflict | Human player-coaches |",
    "The first four are mostly information processing, process execution, and outcome verification — they can be handed to systems step by step. The last one involves trust, emotion, value judgment, and long-term human growth. It still needs people.",
    "So an ANC does not swap one Agent in for one manager. It builds a new kind of organizational infrastructure.",
    "Company Context replaces layered reporting. Skills replace methods that lived in veterans' oral tradition. Agents replace repetitive task dispatch, information lookup, and process execution. Evals replace \"show it to the boss when you're done.\" Permissions and audit replace the fuzzy control hidden inside personal positions.",
    "The people who genuinely handle human growth, professional judgment, and conflict become player-coaches: participating in real work while helping others grow.",
    "In an ANC, pure managers detached from the front line become rarer and rarer. People who can both create results and help others create results become more and more important.",
    "5. The four kinds of people in a zero-middle-management company",
    "A mature zero-middle-management company keeps roughly four core roles.",
    "First, the Owner. The Owner decides why the company exists, which outcomes matter most, which boundaries must not be crossed, and who makes the final call in a major conflict. AI can help an Owner see more facts, but cannot replace the attribution of responsibility.",
    "Second, the DRI. A DRI receives a scoped mandate around a concrete problem. They might own a 48-hour sprint or a customer outcome that runs for half a year. As long as the task exists, they hold the power to mobilize the relevant resources; when it ends, the mandate is reassigned.",
    "Third, the Builder. Most people in an ANC should be Builders. Engineers, salespeople, consultants, operators, designers, lawyers, and finance can all be Builders. What matters is not the job title but whether they directly create results. With Agents, one person can lead a fleet of Agents and own a larger, more complete slice of outcome.",
    "Fourth, the player-coach. Still on the field playing, while owning professional standards, talent development, and the hard judgment calls. Their influence comes from expertise and earned trust — not from headcount.",
    "So a zero-middle-management company does not demote all managers into individual contributors. It asks managers to become creators again.",
    "6. Block is publicly trying to remove the permanent middle layer",
    "In the public record, the company closest to this organizational form is not Anthropic, and not OpenAI. It is Block, Square's parent company.",
    "In 2026, Jack Dorsey and Sequoia partner Roelof Botha published \"From Hierarchy to Intelligence.\" Their argument: corporate hierarchy fundamentally exists to solve an information-flow problem. Managers need to know what their teams are doing, then aggregate that upward and relay decisions downward along the org chart.",
    "But Block is a remote-first company. Its discussions, decisions, plans, code, issues, and project progress already live in digital systems. Those records can become the raw material for a company world model.",
    "That world model can continuously understand what is being built, which project is stuck, where resources went, which methods are working, and which results are drifting off target.",
    "If AI can continuously maintain that map of the company, the organization no longer needs managers running recurring meetings, chasing updates, and producing briefings just so the company can know what it is doing.",
    "Block proposes three core roles for this: Individual Contributors who directly create results, DRIs who own specific problems and customer outcomes, and player-coaches who work while developing others.",
    "Its public essay contains one very direct line: There is no need for a permanent middle management layer.",
    "That line should not be misread as \"Block is already a fully mature zero-middle-management company.\" Block itself openly admits the transition is early, and that some mechanisms may break before they mature.",
    "The accurate statement is: Block has not finished zero middle management — it is among the first large tech companies to publicly and systematically move toward zero permanent middle management.",
    "Source: Block, \"From Hierarchy to Intelligence\" (block.xyz/inside/from-hierarchy-to-intelligence)",
    "7. Claude is turning this from theory into infrastructure",
    "Block did not just publish an organizational theory essay.",
    "Internally it has deployed Goose, an open-source Agent built on Claude, connecting the model to the company's data, tools, and workflows.",
    "According to Anthropic's published case study, 75% of Block engineers save 8–10+ hours per week; thousands of employees across roles now use Goose; non-technical staff can generate SQL, query data, and automate workflows directly, instead of filing a request with the data team and waiting in the queue.",
    "The most important meaning of those numbers is not \"engineers got more efficient.\"",
    "The real organizational change is this: employees started calling the company's data and tools directly, without needing a manager to coordinate with another department first.",
    "A product manager who wanted usage data on a feature used to contact the data team, explain the request, wait for scheduling, align on definitions, and then receive a report. Now they can have an Agent query the data, generate the SQL, explain the results, and turn the analysis into the next action.",
    "What got removed is not just one data analyst's work — it is the communication, scheduling, approvals, and management that used to surround that work.",
    "Source: Claude × Block case study (claude.com/customers/block)",
    "An even more direct case is LaunchNotes. It hands project data from GitHub, Jira, and Linear to Claude for analysis — auto-generating personalized progress updates, catching anomalies, and understanding engineering context. Incident identification became 5x faster, and meeting time dropped by 50%.",
    "Collecting progress, spotting blockers, running syncs, nudging owners — that is the most common work of engineering middle management. Claude is not \"playing the role of a manager,\" but it has taken over much of the information-gathering and synchronization work managers used to do.",
    "Source: LaunchNotes × Claude case study (claude.com/customers/graph)",
    "Anthropic's internal survey of 132 engineers and researchers shows respondents already use Claude in about 59% of their work, self-reporting roughly 50% productivity gains. The average number of consecutive actions Claude Code executes has grown from about 10 half a year ago to about 20.",
    "Which means Agents are moving from \"helping a person with one step\" toward \"independently owning a stretch of work.\"",
    "Source: Anthropic, \"How AI Is Transforming Work at Anthropic\" (anthropic.com/research/how-ai-is-transforming-work-at-anthropic)",
    "8. Neither Anthropic nor OpenAI is a zero-middle-management company",
    "A factual clarification is needed here.",
    "Anthropic uses Claude deeply and emphasizes high trust, small teams, and individual agency — but it is not a zero-middle-management company. Anthropic still publicly hires Research Managers and Engineering Managers, with responsibilities covering team execution, performance, career development, hiring, and cross-team communication.",
    "OpenAI is not one either. Its public job postings still show multiple layers of managers, regional leads, and global leads. An APAC sales development leader manages frontline SDR managers and sales teams across markets; HRBP roles explicitly coach managers and participate in org design and talent planning.",
    "Square cannot be called a zero-middle-management company on its own either. Square is now a business brand under Block; the org transformation was proposed by the parent company.",
    "So the accurate judgment today is: Anthropic is a deeply AI-powered company, but not a zero-middle-management company. OpenAI is a company that produces AI, but is not one either. Block is one of the most aggressive large companies publicly moving toward zero permanent middle management — and the experiment is not finished.",
    "Which also shows: building the most advanced AI and using AI to rebuild your own organization are two different things.",
    "9. Zero middle management starts from company Context, not from the org chart",
    "Many bosses reading this far will have a first reaction: should I start cutting management layers?",
    "No.",
    "If your company's real information still lives in personal WeChat threads, paper documents, Excel files, employees' heads, and disconnected software, the middle layer is still your most important information connector.",
    "Cut it in that state, and the organization's information will not flow into AI. It will walk out the door with the people.",
    "So an ANC transformation cannot start by redrawing the org chart. It starts by punching through real business.",
    "Pick one business point specific enough to prove value. Send an FDE into the field to understand the real process, connect the necessary data and tools, and ship the first usable system.",
    "Only after employees start using it can the system collect real feedback. Which rules need adding, which permissions must stay closed, which exceptions need a human, which judgments depend on veterans' experience — you only learn these inside the business.",
    "That feedback gets distilled into Context, Skills, and Evals, and only then can Agents gradually take on more complete tasks.",
    "When more and more information no longer depends on reporting, more and more methods no longer depend on oral tradition, and more and more tasks no longer depend on a coordinator, the org structure earns the conditions to flatten naturally.",
    "Do not cut the middle layer first and then build the ANC. Build organizational intelligence first, and let part of the middle layer's functions naturally lose their reason to exist.",
    "10. 48 hours, 48 days, 48 weeks — the road from middle layers to zero",
    "The zero-middle-management company fits inside Lawted's 48 theory.",
    "In 48 hours, an FDE proposes a surface and punches through one point — bypassing traditional project approval, reporting, and cross-department coordination — so the boss directly sees business value. This stage does not change the organization. It proves that some things can be done fast without the original seven or eight roles and layers of collaboration.",
    "In 48 days, the system is deployed to employees. Real usage collects company Context, and the experience scattered across brains, chat logs, and files gets distilled into a knowledge base, Skills, workflows, and Evals. This stage starts distilling the middle layer: the rules, experience, and judgment managers used to hold become capabilities the organization can call repeatedly.",
    "In 48 weeks, validated Agents start owning end-to-end tasks. The company redraws the division of work, responsibility, permissions, and risk between humans and AI, and some permanent departments are replaced by dynamic DRIs and task-based teams. Only this stage truly rebuilds the middle layer.",
    "So the three stages compress into: bypass the middle layer in 48 hours, distill it in 48 days, rebuild it in 48 weeks.",
    "Zero middle management is not a 48-hour slogan. It is an organizational outcome that may appear after 48 weeks.",
    "11. Five questions that tell you whether a company is an ANC",
    "In the future, judging whether a company is an AI Native Company should not depend on how many model subscriptions it bought or how many prompts its employees write per day. Ask five questions.",
    "One: can the boss understand what is really happening on the front line without waiting for three layers of reporting?",
    "Two: can employees get the Context, Skills, data, and tools a task requires without a leader coordinating for them?",
    "Three: do the company's key capabilities live in a few veterans' heads, or have they become organizational assets every employee and Agent can call?",
    "Four: is work judged acceptable because \"the boss took a look,\" or because clear, executable, traceable Evals exist?",
    "Five: does a person get resources and decision rights because they permanently occupy a position, or because they are currently responsible for a concrete outcome?",
    "If these questions still resolve through hierarchy, the company is at best using AI.",
    "Only when information no longer depends on middle-layer relay, methods no longer depend on personal monopoly, tasks can be executed by Agents, quality can be verified by Evals, and responsibility can dynamically reorganize around outcomes — only then does it truly start becoming an AI Native Company.",
    "Coda: management stays, the management layer goes",
    "A traditional company is a pyramid.",
    "Information climbs level by level from the bottom; power descends level by level from the top. Middle managers stand at every node, compressing information, relaying orders, coordinating resources, keeping process alive.",
    "An AI Native Company looks more like a continuously learning organizational intelligence.",
    "Company Context remembers. Skills accumulate methods. Agents execute. Evals judge. The permission system controls risk. DRIs own concrete outcomes. Player-coaches own human growth.",
    "So what zero middle management removes is not management, and not responsibility.",
    "It removes one default assumption of the industrial age: that a person can permanently occupy a layer of the company by collecting information, holding meetings, relaying instructions, and managing others.",
    "Future companies will still have founders, still have owners, still have people with deeper experience and better judgment. But their value will no longer come from standing on the path information must pass through. It will come from setting direction, carrying responsibility, making judgment calls, and growing people.",
    "In an AI Native Company, everyone must ultimately stay close to one of two things: real work, or real customers.",
    "Leave the information hauling to the Agents.",
  ],
};

export default article;
